### ISSUE TITLE
Installer - Not Installing??

### ISSUE THREAD

**Issue by Merith-TK** [SteamDeckHomebrew/decky-loader#114]
I use SSH to access my deck most of the time, occasionally using anydesk, 

and I went to re-install decky after re-imaging my deck (I broke an package) 

And now it wont install??? the files show they exist, however the loader menu does not show up in the Quick Access

**Comment by Merith-TK** [comment]
Ignore me, forgot CEWM

**Comment by Soundtoxin** [comment]
Is it possible to run the Decky Loader installer over ssh for updating it without leaving Game Mode?
