### ISSUE TITLE
When loading the store, the quick access menu is open but not visible

### ISSUE THREAD

**Issue by Jademalo** [SteamDeckHomebrew/decky-loader#115]
If you're on the plugin list and you open the store, the web browser loads above the quick access menu. If you then attempt to install a plugin, the menu is assumed to be opened and the install dialogue appears underneath the web browser. This makes it look like nothing is happening when you click install in the store.

If you press B to close the quick access menu after opening the store, everything works as intended and when you click install the menu will open.

I believe the intended functionality here should be that the quick access menu is closed when the store is opened, rather than "hidden" behind the browser.

**Comment by TrainDoctor** [comment]
> If you're on the plugin list and you open the store, the web browser loads above the quick access menu. If you then attempt to install a plugin, the menu is assumed to be opened and the install dialogue appears underneath the web browser. This makes it look like nothing is happening when you click install in the store.
> 
> If you press B to close the quick access menu after opening the store, everything works as intended and when you click install the menu will open.
> 
> I believe the intended functionality here should be that the quick access menu is closed when the store is opened, rather than "hidden" behind the browser.

This is a good shout and an easy fix on our end. I xan personally say I hadn't encountered scenario and I appreciate your feedback. I want to make sure, are you running a pre-release or the old plugin loader?

**Comment by Jademalo** [comment]
I'm not actually 100% sure, I ran one of the install commands but I can't remember which one. Is there any way to check?

**Comment by TrainDoctor** [comment]
> I'm not actually 100% sure, I ran one of the install commands but I can't remember which one. Is there any way to check?
> 
> EDIT: Store directs me to plugins.deckbrew.xyz, so I assume I'm on the store hotfix release rather than on the pre-release.

Yes. beta.deckbrew.xyz is the one used by the pre-release. 

Open a terminal and paste the following command into it:

>    For users:
        curl -L https://github.com/SteamDeckHomebrew/PluginLoader/raw/legacy/dist/install_release.sh | sh
    For the latest pre-release,
        curl -L https://github.com/SteamDeckHomebrew/PluginLoader/raw/main/dist/install_prerelease.sh | sh
    For testers/plugin developers:
        curl -L https://github.com/SteamDeckHomebrew/PluginLoader/raw/main/dist/install_prerelease.sh | sh

It'll likely be install legacy. Go ahead and see if you can replicate this style of behavior on the pre-release.

**Comment by Jademalo** [comment]
The pre-release seems to be fine! Since it works differently it doesn't seem to have that issue.

When clicking install plugin it kicks me to the home menu and reopens the side panel, so it doesn't seem to get stuck.
When pressing B it closes the store window, and in doing so when it goes to the home menu it reopens the quick access menu.

Interestingly though, I don't seem to be able to install plugins. I click install, it kicks me to the menu, reopens the list, and it doesn't get installed. Shall I make another issue?

**Comment by TrainDoctor** [comment]
> The pre-release seems to be fine! Since it works differently it doesn't seem to have that issue.
> 
> When clicking install plugin it kicks me to the home menu and reopens the side panel, so it doesn't seem to get stuck. When pressing B it closes the store window, and in doing so when it goes to the home menu it reopens the quick access menu.
> 
> Interestingly though, I don't seem to be able to install plugins. I click install, it kicks me to the menu, reopens the list, and it doesn't get installed. Shall I make another issue?

This is due to a known and now accounted for packaging bug, but the new packages haven't been deployed yet apologies.

**Comment by TrainDoctor** [comment]
Since the change in behavior has been addressed seemingly, I'll close this issue.
