### ISSUE TITLE
Feature - SwitchBru like browser service

### ISSUE THREAD

**Issue by Merith-TK** [SteamDeckHomebrew/decky-loader#119]
So I am an fan of [SwitchBru's DNS](https://dns.switchbru.com/) page on my Switch, and I noticed that the plugin store just opens an built in web browser from the steam deck, 

would it be possible that you guys could make an similar service, so we dont have to launch with the full overhead of an standard web browser which takes alot more resources,

**Comment by NGnius** [comment]
Maybe I'm misunderstanding what you're asking for, but the Steam UI is basically a fully-featured web browser already -- it's using [CEF](https://en.wikipedia.org/wiki/Chromium_Embedded_Framework) to display the UI. You can't really escape from the browser overhead.

**Comment by beebls** [comment]
SteamOS itself _is_ a web browser, all the UI elements are just react components, the OS is essentially a chromium container.

The way that the loader and plugins work is they all simply render react components.

The loader would need to page a server to grab the data on available plugins, so by that point it doesn't really provide any advantage switching to some kind of offline application.

**Comment by Merith-TK** [comment]
What I meant was, in DeckyLoader when you click on the "Plugin Store" icon, it opens an web page directly within Game Mode, using an webview that is already built into steam itself, 

What I am asking for, is an feature that opens up an webpage like SwitchBru, inside this already existing embedded browser,

**Comment by TrainDoctor** [comment]
This feature falls under the scope and nature of a plugin rather than something we would build into decky-loader. Thank you for your suggestion.

**Comment by Merith-TK** [comment]
how would one go about making this into an plugin then?

**Comment by DraconicNEO** [comment]
I know this is a late reply but we do have a Web browser plugin here in the store in case you're still looking, it's not by the Decky Team, it's third party, but it works well and gets the job done.
