### ISSUE TITLE
Plugin Install is not working

### ISSUE THREAD

**Issue by MarcoSolo23** [SteamDeckHomebrew/decky-loader#122]
I installed the latest version of decky-loader. When I hit the store icon in the Plugins section, and I hit install on a plugin, it asks if I want to install it, but then it doesn't install or show any pending installation.

**Comment by TrainDoctor** [comment]
What version are you using? You can find that version by going to the cog in the top left and then going to settings. It will be in the top center of the screen. If the cog wheel is not there then you are using the legacy release which we do not support.

**Comment by MarcoSolo23** [comment]
Think I might have been on the legacy. Switched to pre-release and it works now.
