### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by traynor1987** [SteamDeckHomebrew/decky-loader#137]
Hi,

I've enabled devices mode and CEF Remote Debugging. Restarted. Went to desktop mode.

Pasted this into konsole:

`curl -L https://github.com/SteamDeckHomebrew/decky-loader/raw/main/dist/install_prerelease.sh | sh`

It says curl: no link specified.

See photo attached. Any ideas? Password has been set as well.

![20220812_032320](https://user-images.githubusercontent.com/16270479/184276052-200a3e91-3695-4090-bfba-e7ab4c5c8a82.jpg)

Thanks :)

**Comment by TrainDoctor** [comment]
Ah that's my fault I forgot to attach a binary to that tag as it was a placeholder but I forgot the script doesn't check if they binary actually exists. I'll add the binary asap.

**Comment by TrainDoctor** [comment]
This is resolved with recent updates. I also resolved an issue where the old loader couldn't update from the old version numbering scheme to the new one.

**Comment by traynor1987** [comment]
Thank you...I knew metriod prime 2 on gamecube would work at 60 fps if I lowered the CPU threads. Went from 39 FPS to 60 FPS. Absolute legend you and whoever made power tools.

**Comment by TrainDoctor** [comment]
> Thank you...I knew metriod prime 2 on gamecube would work at 60 fps if I lowered the CPU threads. Went from 39 FPS to 60 FPS. Absolute legend you and whoever made power tools.

PowerTools is made by @NGnius so all praise goes to him. 👍🏻
