### ISSUE TITLE
Add Class Names or IDs to the Decky Store Componenets

### ISSUE THREAD

**Issue by joamjoamjoam** [SteamDeckHomebrew/decky-loader#140]
If using an image as a home screen it is hard to read the test on the Decky store. It would be nice if they had classes so they could be themed with CSS Loader to make it easier to read and match the rest of the theme.

Here's an Example:
![image](https://user-images.githubusercontent.com/4205452/185029901-36a3cd56-4634-4f38-91f3-e5d05d0e9417.png)

**Comment by TrainDoctor** [comment]
Based on discussion, the desire is to give the cards a unique classname so that they can be given specific theme tags (and as a result readable text).

**Comment by botatooo** [comment]
Maybe prefixing them with something like `SDH-Store_`?

**Comment by TrainDoctor** [comment]
Addressed in https://github.com/SteamDeckHomebrew/decky-loader/commit/5960c11d60bccb732ead19fdb0b4547806f70f70.
Will close this issue once these changes go live in a pre-release.
