### ISSUE TITLE
Decky missing after steam client update 

### ISSUE THREAD

**Issue by jctace** [SteamDeckHomebrew/decky-loader#141]
Updated to steam preview version 1660766017, build date wed aug 17 12:41 pm, and decky no longer appears. 

Tried reinstalling multiple times and manually invoking the service but when running journalctl -u plugin_loader.service the log of "Plugin loader isn't present in Steam anymore, reinjecting" is thrown over and over.

**Comment by jctace** [comment]
Looks like the steamwebhelper is using 8080 which is probably why its not loading the service

**Comment by alosarjos** [comment]
+1. After today preview update, the plugin section is not longer showing up on the right side menu.

**Comment by jctace** [comment]
`Aug 17 14:21:01 steamdeck PluginLoader[11721]: aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:8080 ssl:default [Connect call failed ('127.0.0.1', 8080)]
Aug 17 14:21:04 steamdeck PluginLoader[11721]: [injector][DEBUG]: ClientConnectorError excepted.
Aug 17 14:21:04 steamdeck PluginLoader[11721]: [injector][DEBUG]: Steam isn't available yet. Wait for a moment...
Aug 17 14:21:04 steamdeck PluginLoader[11721]: [injector][DEBUG]: Traceback (most recent call last):
Aug 17 14:21:04 steamdeck PluginLoader[11721]:   File "aiohttp/connector.py", line 986, in _wrap_create_connection
Aug 17 14:21:04 steamdeck PluginLoader[11721]:   File "asyncio/base_events.py", line 1064, in create_connection
Aug 17 14:21:04 steamdeck PluginLoader[11721]:   File "asyncio/base_events.py", line 1049, in create_connection
Aug 17 14:21:04 steamdeck PluginLoader[11721]:   File "asyncio/base_events.py", line 960, in _connect_sock
Aug 17 14:21:04 steamdeck PluginLoader[11721]:   File "asyncio/selector_events.py", line 500, in sock_connect
Aug 17 14:21:04 steamdeck PluginLoader[11721]:   File "asyncio/selector_events.py", line 535, in _sock_connect_cb
Aug 17 14:21:04 steamdeck PluginLoader[11721]: ConnectionRefusedError: [Errno 111] Connect call failed ('::1', 8080, 0, 0)
Aug 17 14:21:04 steamdeck PluginLoader[11721]: The above exception was the direct cause of the following exception:
Aug 17 14:21:04 steamdeck PluginLoader[11721]: Traceback (most recent call last):
Aug 17 14:21:04 steamdeck PluginLoader[11721]:   File "injector.py", line 68, in get_tabs
Aug 17 14:21:04 steamdeck PluginLoader[11721]:   File "aiohttp/client.py", line 535, in _request
Aug 17 14:21:04 steamdeck PluginLoader[11721]:   File "aiohttp/connector.py", line 542, in connect
Aug 17 14:21:04 steamdeck PluginLoader[11721]:   File "aiohttp/connector.py", line 907, in _create_connection
Aug 17 14:21:04 steamdeck PluginLoader[11721]:   File "aiohttp/connector.py", line 1206, in _create_direct_connection
Aug 17 14:21:04 steamdeck PluginLoader[11721]:   File "aiohttp/connector.py", line 1175, in _create_direct_connection
Aug 17 14:21:04 steamdeck PluginLoader[11721]:   File "aiohttp/connector.py", line 992, in _wrap_create_connection
Aug 17 14:21:04 steamdeck PluginLoader[11721]: aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:8080 ssl:default [Connect call failed ('::1', 8080, 0, 0)]
Aug 17 14:21:06 steamdeck PluginLoader[11721]: [injector][DEBUG]: ClientConnectorError excepted.
Aug 17 14:21:06 steamdeck PluginLoader[11721]: [injector][DEBUG]: Steam isn't available yet. Wait for a moment...
Aug 17 14:21:06 steamdeck PluginLoader[11721]: [injector][DEBUG]: Traceback (most recent call last):
Aug 17 14:21:06 steamdeck PluginLoader[11721]:   File "aiohttp/connector.py", line 986, in _wrap_create_connection
Aug 17 14:21:06 steamdeck PluginLoader[11721]:   File "asyncio/base_events.py", line 1064, in create_connection
Aug 17 14:21:06 steamdeck PluginLoader[11721]:   File "asyncio/base_events.py", line 1049, in create_connection
Aug 17 14:21:06 steamdeck PluginLoader[11721]:   File "asyncio/base_events.py", line 960, in _connect_sock
Aug 17 14:21:06 steamdeck PluginLoader[11721]:   File "asyncio/selector_events.py", line 500, in sock_connect
Aug 17 14:21:06 steamdeck PluginLoader[11721]:   File "asyncio/selector_events.py", line 535, in _sock_connect_cb
Aug 17 14:21:06 steamdeck PluginLoader[11721]: ConnectionRefusedError: [Errno 111] Connect call failed ('::1', 8080, 0, 0)
Aug 17 14:21:06 steamdeck PluginLoader[11721]: The above exception was the direct cause of the following exception:
Aug 17 14:21:06 steamdeck PluginLoader[11721]: Traceback (most recent call last):
Aug 17 14:21:06 steamdeck PluginLoader[11721]:   File "injector.py", line 68, in get_tabs
Aug 17 14:21:06 steamdeck PluginLoader[11721]:   File "aiohttp/client.py", line 535, in _request
Aug 17 14:21:06 steamdeck PluginLoader[11721]:   File "aiohttp/connector.py", line 542, in connect
Aug 17 14:21:06 steamdeck PluginLoader[11721]:   File "aiohttp/connector.py", line 907, in _create_connection
Aug 17 14:21:06 steamdeck PluginLoader[11721]:   File "aiohttp/connector.py", line 1206, in _create_direct_connection
Aug 17 14:21:06 steamdeck PluginLoader[11721]:   File "aiohttp/connector.py", line 1175, in _create_direct_connection
Aug 17 14:21:06 steamdeck PluginLoader[11721]:   File "aiohttp/connector.py", line 992, in _wrap_create_connection
Aug 17 14:21:06 steamdeck PluginLoader[11721]: aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:8080 ssl:default [Connect call failed ('::1', 8080, 0, 0)]
Aug 17 14:21:16 steamdeck PluginLoader[11721]: [main][INFO]: Plugin loader isn't present in Steam anymore, reinjecting...
Aug 17 14:21:21 steamdeck PluginLoader[11721]: [main][INFO]: Plugin loader isn't present in Steam anymore, reinjecting...
Aug 17 14:21:26 steamdeck PluginLoader[11721]: [main][INFO]: Plugin loader isn't present in Steam anymore, reinjecting...
Aug 17 14:21:31 steamdeck PluginLoader[11721]: [main][INFO]: Plugin loader isn't present in Steam anymore, reinjecting...
Aug 17 14:21:36 steamdeck PluginLoader[11721]: [main][INFO]: Plugin loader isn't present in Steam anymore, reinjecting...
Aug 17 14:21:41 steamdeck PluginLoader[11721]: [main][INFO]: Plugin loader isn't present in Steam anymore, reinjecting...
Aug 17 14:21:45 steamdeck systemd[1]: Stopping SteamDeck Plugin Loader...
Aug 17 14:21:45 steamdeck PluginLoader[11721]: ======== Running on http://127.0.0.1:1337 ========
Aug 17 14:21:45 steamdeck PluginLoader[11721]: (Press CTRL+C to quit)
Aug 17 14:21:45 steamdeck systemd[1]: plugin_loader.service: Main process exited, code=exited, status=1/FAILURE
Aug 17 14:21:45 steamdeck systemd[1]: plugin_loader.service: Failed with result 'exit-code'.
Aug 17 14:21:45 steamdeck systemd[1]: Stopped SteamDeck Plugin Loader.
Aug 17 14:21:45 steamdeck systemd[1]: plugin_loader.service: Consumed 1.284s CPU time.
Aug 17 14:21:46 steamdeck systemd[1]: Started SteamDeck Plugin Loader.
Aug 17 14:21:47 steamdeck PluginLoader[14088]: main.py:52: DeprecationWarning: There is no current event loop
Aug 17 14:21:47 steamdeck PluginLoader[14088]: [selector_events][DEBUG]: Using selector: EpollSelector
Aug 17 14:21:47 steamdeck PluginLoader[14088]: [loader][INFO]: plugin_path: /home/deck/homebrew/plugins
Aug 17 14:21:47 steamdeck PluginLoader[14088]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins', wd=1, mask=IN_ATTRIB|IN_ISDIR, cookie=0, name=>
Aug 17 14:21:47 steamdeck PluginLoader[14088]: [inotify_buffer][DEBUG]: in-event <InotifyEvent: src_path=b'/home/deck/homebrew/plugins', wd=1, mask=IN_ATTRIB|IN_ISDIR, cookie=0, name=>
Aug 17 14:21:47 steamdeck PluginLoader[14088]: [loader][INFO]: import plugins from /home/deck/homebrew/plugins
Aug 17 14:21:54 steamdeck PluginLoader[14088]: [main][INFO]: Plugin loader isn't present in Steam anymore, reinjecting...
Aug 17 14:21:59 steamdeck PluginLoader[14088]: [main][INFO]: Plugin loader isn't present in Steam anymore, reinjecting...

**Comment by TrainDoctor** [comment]
It looks like with the most recent update upgraded the version of webpack being used. We're working on addressing the issue asap.

**Comment by TrainDoctor** [comment]
> It looks like with the most recent update upgraded the version of webpack being used. We're working on addressing the issue asap.

As of v2.0.5-pre13 this issue is now resolved. If decky-loader is not showing up just re-run the install pre-release script. (See the README).
