### ISSUE TITLE
Decky Store not booting

### ISSUE THREAD

**Issue by evelritual** [SteamDeckHomebrew/decky-loader#145]
SteamOS Version: 3.3.1
Decky Version: v2.0.5-pre13

New steam deck with a fresh Decky installation. Install went off without a hitch. When opening the Plugin menu using the (...) button and clicking the "store" icon, steam loading logo with rotating circle pops up and loads forever. Rebooting steam deck does not fix. Steam Deck is still operational during this.

I've left it on for ~30 minutes, tried a few times with reboots, and can't seem to get past this screen.

Please let me know if I can supply any more details that may help!

**Comment by TrainDoctor** [comment]
We're currently dealing with issues related to the plugin-store itself. I've restarted the backend plugin store and it should be running now. Please confirm the plugin store's status as the restart was roughly ~20 minutes ago.

**Comment by evelritual** [comment]
Store looks good hitting from a chrominuim browser just now via this link:
https://plugins.deckbrew.xyz
Restarted steam deck and attempted to launch store again and it works. Thank you!

**Comment by TrainDoctor** [comment]
> Store looks good hitting from a chrominuim browser just now via this link: https://plugins.deckbrew.xyz Restarted steam deck and attempted to launch store again and it works. Thank you!

While on the right track, https://beta.deckbrew.xyz/ is where the software for the latest pre-releases goes and plugins is simply for the legacy loader now. Glad to hear it's working for you.
