### ISSUE TITLE
Show each plugin's version number (in settings)

### ISSUE THREAD

**Issue by vrman123** [SteamDeckHomebrew/decky-loader#146]
There is currently no way to find the current version of a plugin you are using from within the UI.
This is troublesome as you need to know what version you have before you can check if there is a newer version available.
Even if a better system for updating plugins was implemented it would probably be best to have some kind of version indicator in the UI. 

![19-08-2022 11:17](https://user-images.githubusercontent.com/48649272/185598728-59483c1d-0c71-4b82-9733-590a9336824d.png)
quick mockup done with &nbsp and a second span with gray color ^

This would involve editing [decky-loader/frontend/src/components/settings/pages/plugin_list/index.tsx](https://github.com/SteamDeckHomebrew/decky-loader/blob/main/frontend/src/components/settings/pages/plugin_list/index.tsx)

I'm not sure where you'd grab the version number from, so I decided I would just make an issue instead of poking around looking for version numbers.

**Comment by botatooo** [comment]
This has been resolved as of [`8b3f569`](https://github.com/SteamDeckHomebrew/decky-loader/commit/8b3f569a09db9daf7748426f916a66591159928f) alongside other things. A release should come soon enough.
![image](https://user-images.githubusercontent.com/63275405/185811784-faf5bfa6-368e-42fb-ad06-4fdba15f5c47.png)
