### ISSUE TITLE
Unable to remove "duplicate" leftover plugin entry (uninstall command in Decky Settings does not work)

### ISSUE THREAD

**Issue by Ryunam** [SteamDeckHomebrew/decky-loader#148]
Hi! First and foremost, thank you for developing this tool and extending the functionality of the Deck menu in Gaming Mode. 

I am opening this issue although I am unsure if the problem I am encountering is related to the loader or, on the other hand, might be plugin-specific. If it turns out to be the latter, let me know and I will promptly move this issue to the respective plugin repository.

I had installed quite some time ago an older version of the "Power Tools" plugin, dating back to when UI navigation through the integrated controller on the Deck was not supported yet. After some of the most recent updates pushed by Valve, I updated both the Decky loader (pre-release version) and the aforementioned plugin through the Plugin Store, but this led to the Decky menu retaining multiple entries for the same plugin. See here:

![20220819161022_1](https://user-images.githubusercontent.com/17614150/185645838-442d4c7f-0c14-4436-9935-2f15dcf0cc77.jpg)

There are some slight differences between the two entries: the icon is different and it seems the most recent version of the plugin does **not** have a space in its name, while the older one does in fact have a space between "Power" and "Tools".

Furthermore, if I click on the older version (the one with the space), it does not seem to be working at all with the current Decky framework:

![20220819161045_1](https://user-images.githubusercontent.com/17614150/185646920-4558ab3c-1e85-4e2c-beab-db8898ffe6a8.jpg)

So, in order to remove the duplicate leftover entry (the older version) and only keep the newer one, I tried going into **Decky Settings -> Plugins**, then clicked on the **...** button related to the leftover entry and selected the **Uninstall** option.

Unfortunately though, this does not seem to work. The uninstall command does not seem to be doing anything at all and the duplicate entries remain unchanged.

I also tried to look inside `~/homebrew/plugins` as per instructions in this repo, but I can only spot one subfolder which has the name `PowerTools` (without any space) and which I presume to be associated with the newer version of the plugin, rather than the older one.

Any suggestion or pointer you can give me with regards to either uninstalling the older entry manually, or performing a complete removal of the plugin and then only reinstalling the newer version, will be much appreciated!

**Comment by vrman123** [comment]
Just in case you haven't: try restarting the steam deck and attempting to uninstall again. Sometimes that'll fix the issue, although that is probably unlikely to work here.

My best guess would be deleting the `PowerTools` folder inside of `~/homebrew/plugins` and then (if it gets rid of both PowerTools menus successfully) reinstalling PowerTools.

If it's still broken after this (unlikely?), I would just run the uninstall script (`curl -L https://github.com/SteamDeckHomebrew/decky-loader/raw/main/dist/uninstall.sh | sh`) and reinstalling decky.

- Not a dev

**Comment by Ryunam** [comment]
Thank you so much for the timely answer! I am glad to confirm that restarting the Deck did in fact address this problem entirely and remove the leftover entry. Wish I had thought of such a simple solution before opening this!
