### ISSUE TITLE
Can't write /home/deck/homebrew/plugins folder

### ISSUE THREAD

**Issue by s951736** [SteamDeckHomebrew/decky-loader#153]
I followed the instruction and installed Decky Loader, but the plugins folder do not let me write file into it, nor can I delete the plugin folder.
I tried restart the Steam Deck, but the issue still remain. Also tried manually set the permission in GUI, but it's still unwriteable.
What do I miss?
Thanks.

**Comment by vrman123** [comment]
Just so you're aware, you don't need to manually write into the plugins folder to install most plugins, as they're available from the built in plugin store.

Editing the folder's permissions in the GUI _should_ work, as it has for me in the past. To edit them, right click on the plugins folder, press properties, press permissions then set all values to 'can view and modify content'. It's important to note that (at least at for now) the plugins folder gets its permissions reset every time Decky Loader boots up (when you restart/change to game mode), so you'll need to do this whenever you want to write into it.

If this doesn't work, feel free to follow up and I'll try help figure out what's wrong :)
