### ISSUE TITLE
Plugin Loader icon replaced by 'help' icon in quick menu

### ISSUE THREAD

**Issue by abarlas** [SteamDeckHomebrew/decky-loader#162]
After updating to OS version 3.3.1 in the beta channel, the plugin loader has now disappeared and been replaced by a help icon. The plugins themselves are still working, however I have no way of accessing the loader. Is there a way to bring it back without reinstalling?

![plugin_loader_sd](https://user-images.githubusercontent.com/42995829/187260839-4b0a6288-3af7-4bcc-867b-c67982cabacb.jpeg)

**Comment by vrman123** [comment]
That help icon is always there, you probably just don't notice it normally. It looks like decky needs an update to work. You can update from the konsole by running: `curl -L https://github.com/SteamDeckHomebrew/decky-loader/raw/main/dist/install_prerelease.sh | sh`

**Comment by abarlas** [comment]
> That help icon is always there, you probably just don't notice it normally. It looks like decky needs an update to work. You can update from the konsole by running: `curl -L https://github.com/SteamDeckHomebrew/decky-loader/raw/main/dist/install_prerelease.sh | sh`

Updating from Konsole has brought back the icon under the 'help' icon. Thank you.
