### ISSUE TITLE
Loader - Plugin updater updates files but does not fully update UI

### ISSUE THREAD

**Issue by TrainDoctor** [SteamDeckHomebrew/decky-loader#165]
Creating this issue on behalf of @Ben_OnAir.

Running version v2.0.5-pre-18 Ben was able to consistently reproduce decky-loader's UI not actually updating despite the underlying files having been updated.

This occurred installing DeckFaqs 1.0.0 and upgrading to the latest version as well as vibrantDeck and a few other plugins.

Ben was able to consistently reproduce the issue and did so while I observed via a discord screen share which I also recorded.

Relevant logs:
[console-logs.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/9447711/console-logs.txt)
[loader.log](https://github.com/SteamDeckHomebrew/decky-loader/files/9447712/loader.log)

**Comment by AAGaming00** [comment]
Should be fixed in 3700dd7
