### ISSUE TITLE
Loader - Use server-generated ids or package.json name for plugin identification.

### ISSUE THREAD

**Issue by mirobouma** [SteamDeckHomebrew/decky-loader#167]
Currently, if you would update the name of a plugin in plugin.json, it will break the update checking process. In my case i would like to change my plugin name from "MusicControl" to "Music Control". By changing the way the loader identifies a plugin, we can ensure in the future we should be able to modify the user-facing display name without breaking compatibility.

Possible solutions:
- Generate server-side id's for plugins for update checking / plugin validation
- Use package.json name instead (Not user facing so less likely to change)
- Add an "id" field to plugin.json that will be preferred for comparisons if it is set

**Comment by OdinVex** [comment]
With GUIDs, then perhaps even a cross-plugin communication with 'to/from' GUIDs, very recommended. ;) Relying on text has never done software very well.

**Comment by TrainDoctor** [comment]
We spent some time internally on this and have decided that we can modify enough with our CI and backend tools that GUIDs/ID strings would add more complexity to the plugin development process.
