### ISSUE TITLE
Plugin Loader fails to install plugins due to "caller, callee, and arguments properties used on strict mode functions"

### ISSUE THREAD

**Issue by erie-lake-erie** [SteamDeckHomebrew/decky-loader#174]
I have tried installing various plug-ins to no avail. When prompted to install some application, say `ApplicationName`, I receive a 
```
Install Plugin?

ApplicationName Version [object Object]
[ Install ]
[ Cancel  ]
```
message. Touching the install button does nothing, and this popup doesn't embed itself fully in the side tab either as expected. Using Chrome, I receive
```python
Exception: TypeError: 'caller', 'callee', and 'arguments' properties 
on strict mode functions at Function.invokeGetter (<anonymous>:3:28)
```
Correspondingly, the `install_plugins` utility method encounters a `405` response code ostensibly because of the `strict-origin-when-cross-origin` referrer policy used.

**Comment by AAGaming00** [comment]
Are you trying to use the web store by chance?

**Comment by Forinil** [comment]
@erie-lake-erie I had the same problem after installing the latest release. Installing the latest **pre**-release fixed the issue.

I guess the release is broken. That would also explain why the README says to install the pre-release for normal usage - which I thought was a typo.

**Comment by TrainDoctor** [comment]
Ah this is because the old stable release is no longer supported. Please use the latest pre-release. Once a new stable release comes you can switch to the stable branch.
