### ISSUE TITLE
Plugin store install button does nothing.

### ISSUE THREAD

**Issue by IAmSHOCK** [SteamDeckHomebrew/decky-loader#179]
I tried installing plugins through the plugin store, but the button does nothing when pressed. I managed to install 2 plugins manually but cssloader and bluetooth plugin I wasn't able to.

**Comment by TrainDoctor** [comment]
If you're using the legacy version you need to upgrade to the latest pre-release.

**Comment by TrainDoctor** [comment]
Also please provide version, steam deck branch version and any changes you made beforehand.

**Comment by JaxonWright** [comment]
I am getting a 403 error when trying this. Seems like someone screwed up the build because it's trying to access localhost:1337

**Comment by TrainDoctor** [comment]
That's intentional. You have another service conflicting on that port. Determine what it is abd you can change the port or disable that service/program.

**Comment by agbishop** [comment]
Seeing the same 403 error. The only service I see running is "PluginLoader" on 1337

**Comment by Vortelf** [comment]
Not OP, but I'm experiencing the same issue. Latest Steam Beta and latest version of this([v2.1.0-pre4](https://github.com/SteamDeckHomebrew/decky-loader/releases/tag/v2.1.0-pre4)).
[plugin_loader.service.log](https://github.com/SteamDeckHomebrew/decky-loader/files/9634095/plugin_loader.service.log)

**Comment by TrainDoctor** [comment]
> Not OP, but I'm experiencing the same issue. Latest Steam Beta and latest version of this([v2.1.0-pre4](https://github.com/SteamDeckHomebrew/decky-loader/releases/tag/v2.1.0-pre4)). [plugin_loader.service.log](https://github.com/SteamDeckHomebrew/decky-loader/files/9634095/plugin_loader.service.log)
> 
> Edit: Sorted my issue - I have VPN on my network and it seems like the CDN of the plugin repository is blocking the access to it. Switched the network and managed to install the plugins that went missing.
> 
> An issue that remains is that when you try to update a plugin, the service deletes the old version of the plugin without verifying that the new version is downloaded and ready to be installed.

Thanks for the feedback, we'll work on getting the download into a tmp dir and then deleting/overwriting. Cheers.

**Comment by IAmSHOCK** [comment]
I'm using steam deck stable version and the decky loader pre-release version 2.1.0-pre4.
I'm using my regular wifi internet connection.

**Comment by PartyWumpus** [comment]
@IAmSHOCK i see you've closed the issue. did you sort it out?

**Comment by IAmSHOCK** [comment]
I'm not able to install plugins through the browser, but I found the store button on the top right corner of the decky loader.
The "Install/Uninstall plugins" is not clear on that part (Using the shopping bag button in the top right corner, you can go to the offical "Plugin Store")

**Comment by IAmSHOCK** [comment]
IMO it should say on the decky loader because when I click the link (Plugin Store) it takes me to a website where each plugin as the option to install.

**Comment by PartyWumpus** [comment]
understandable, people have had this confusion before. Will recommend a change
