### ISSUE TITLE
Plugins CDN is inaccessible from Turkey

### ISSUE THREAD

**Issue by anVlad11** [SteamDeckHomebrew/decky-loader#187]
There is no error in UI, it just opens the Decky Loader menu when i click "Install" button in Plugin Store inside Decky Loader

I'm able to install plugins manually

Here is the part of an output of `journalctl` when i'm trying to install any plugin from UI (it's Remote Play Whatever in this case)
```
Sep 26 13:27:24 anvlad11-deck PluginLoader[964]: [browser][DEBUG]: Fetching https://cdn.tzatzikiweeb.moe/file/steam-deck-homebrew/versions/caec43ed565e78e68240145da7514c0b85b938a4f1cc53401008107221cfd9ff.zip
Sep 26 13:27:26 anvlad11-deck PluginLoader[964]: [browser][CRITICAL]: Could not fetch from URL. <!DOCTYPE html>
Sep 26 13:27:26 anvlad11-deck PluginLoader[964]: <html lang="en-US">
Sep 26 13:27:26 anvlad11-deck PluginLoader[964]: <head>
Sep 26 13:27:26 anvlad11-deck PluginLoader[964]: <title>Access denied</title>
```
I see the same response with "Error code 1020" from Cloudflare if i open plugin download url on my desktop, but if route traffic through Digital Ocean instance in Germany, i'm able to download it

Cloudflare Ray ID: 750b4f41a82f83af

![image](https://user-images.githubusercontent.com/7249212/192254975-5ef08a43-2d73-4ba1-b1e9-0565469b4abd.png)

But with my current network configuration i'm unable to route SteamDeck traffic via DO selectively, so can't fix it on my side now.

**Comment by TrainDoctor** [comment]
I'm not sure what we can do about this ourselves and I will not use a locally hosted server there. We'll keep our eyes on it.

**Comment by TrainDoctor** [comment]
According to @marios8543 this issue should now be resolved with updated cloudflare routing on our end. 👍
