### ISSUE TITLE
Navigation to plugin list view from plugin does not work via "go back" (press B)

### ISSUE THREAD

**Issue by FrogTheFrog** [SteamDeckHomebrew/decky-loader#188]
When you're in a plugin going back does not bring you the the plugin list view as expected. Instead the focus seems to be given to the SP window underneath.

**Comment by TrainDoctor** [comment]
Due to how the QAM works, it's unlikely this can be easily implemented in the desired form.

**Comment by AAGaming00** [comment]
Implemented on pre-release.
