### ISSUE TITLE
Add optional developer menu toggle

### ISSUE THREAD

**Issue by TrainDoctor** [SteamDeckHomebrew/decky-loader#189]
Current scope: Toggle enables/disables Valve developer mode.
Potential further scope, modify environment variables related to decky for tweaking logging, testing and debugging etc.

**Comment by botatooo** [comment]
Do we know which module this is in?

**Comment by TrainDoctor** [comment]
> Do we know which module this is in?

It appears under the normal settings menu, so I'd say under general settings etc.
