### ISSUE TITLE
Going to the plugin menu causes the deck to "freeze"

### ISSUE THREAD

**Issue by danodemano** [SteamDeckHomebrew/decky-loader#191]
As soon as I navigate to the plugins menu the only button that works is the power button and I have to reboot. I can't close the menu, back out, or even continue to the store. I installed the latest stable. Not sure how to troubleshoot. I have the 512GB version if it matters. OS is up to date.

**Comment by PartyWumpus** [comment]
Try installing the pre-release version of decky instead

**Comment by PartyWumpus** [comment]
run the uninstall script first, then run the pre-release install script

**Comment by danodemano** [comment]
That got it! Uninstall, reboot, install pre-release, reboot, good to go. Thanks!!
