### ISSUE TITLE
Easier install/uninstall via a .desktop or .sh file (similar to EmuDeck)

### ISSUE THREAD

**Issue by PartyWumpus** [SteamDeckHomebrew/decky-loader#193]
This seems like a no-brainer, and i've seen it tossed around as an idea by many people.
After some thinking, i've realised there's a few questions that need to be thought about before it's done:

1. is it better to make one file that asks the user which version to install or is it better to have several files (one for each branch) or is it better to have one file that only installs stable, and make changing branches mainly done from within Decky
2. should uninstalling be part of the installer or a seperate file or part of decky as suggested in #147 (more than one of these is a perfectly reasonable option too)
3. what's the best way to format the file: is it better to do it like EmuDeck where the .desktop file just runs curl and the script is just grabbed off the internet or should the code be included with the downloaded file? (if the script(s) are included it'll work offline but be more complex, and possibly better suited as a .sh file instead of a .desktop)
4. what's a suitable level of complexity: is it worth putting a lot of extra work in for progress bars etc or should it be kept simple

i'm sure there's other things that need to be considered too.

**Comment by PartyWumpus** [comment]
basic installer file: https://cdn.discordapp.com/attachments/960281551868952618/1026191793802453043/Decky.desktop 
basic uninstaller file: https://cdn.discordapp.com/attachments/960281551868952618/1026193314422210651/Decky_Uninstall.desktop

**Comment by Godsbane** [comment]
1. We ended up going with one per branch so there wasn't confusion.
2. Both should be options. What if the user has a problem and for whatever reason can't get to the ui? A separate uninstall path is a good option in this case.
3. The benefit to pulling off the github is agility, but you are then dependent on internet.
4. progress bars and such can be implemented with zenity fairly easily. We used it a lot in EmuDeck. You can pipe progress to it once it's instantiated (better with known milestones during installation/uninstall), or do what dragoon did and loop it forever until you are done just to show activity that isn't a script scrolling by.

**Comment by TrainDoctor** [comment]
> 3\. The benefit to pulling off the github is agility, but you are then dependent on internet.

We're looking into including fallback scripting to address that.

> 1. We ended up going with one per branch so there wasn't confusion.

My thought was a basic installer script that changes what files systemd service it installs based on arguments.

> 2\. Both should be options. What if the user has a problem and for whatever reason can't get to the ui? A separate uninstall path is a good option in this case.

A UI uninstaller has proved to be a complete PITA so we're forgoing it for now against even my own desire but it's proven easier to not do one with direct UI integration.

**Comment by tombuben** [comment]
In general, I'd prefer if the distribution was signed. Please don't just release a bash script that runs sudo commands and downloads random binaries from the release folder of a github repo without checking it was published by the person who made the script...

**Comment by TrainDoctor** [comment]
We might eventually return to this idea but I'm closing this issue as stale until someone expresses an interest in working on it.
