### ISSUE TITLE
Games crashing

### ISSUE THREAD

**Issue by BrooklynTheDogg** [SteamDeckHomebrew/decky-loader#195]
Im unable to determine if this is a decky or powertools issue or the way they interact but it only started in the last day or so. 

One of the two is cause the deck verified games shadow of mordor to crash. Upon uninstall game works properly. Just wondering if somehow someone can look into it. Thank you

**Comment by TrainDoctor** [comment]
Quoting from a discussion that's been ongoing for a while, I'll pin this to the top.

> This is not a decky loader issue. It's due to a few issues with gamescope, the Wayland compositor valve uses.
> Our tool only surfaced the issue. I'd appreciate some faith that I'm not talking out of my ass.
> https://github.com/Plagman/gamescope/issues/613#issuecomment-1248903453

**Comment by BrooklynTheDogg** [comment]
Super dumb question. Whats gamescope? I only had decky and power tools installed when i had the issue. I appreciate the follow up. Thank you

**Comment by TrainDoctor** [comment]
> Super dumb question. Whats gamescope? I only had decky and power tools installed when i had the issue. I appreciate the follow up. Thank you

Not a dumb question at all, gamescope is part of the stack of software that shows you the windows for the games you play in game mode. Basically, nothing we in the team have control over.

**Comment by BrooklynTheDogg** [comment]
Thanks for getting back to me. Appreciate it. Just seemed weird cause it hasnt happened to me until yesterday and wouldnt even let me load game.

**Comment by TrainDoctor** [comment]
> Thanks for getting back to me. Appreciate it. Just seemed weird cause it hasnt happened to me until yesterday and wouldnt even let me load game.

Seems to be that it varies game to game, so that fits the lack of pattern.

**Comment by AAGaming00** [comment]
Fixed on prerelease.
