### ISSUE TITLE
Plugin menu not loading

### ISSUE THREAD

**Issue by Wintersdark** [SteamDeckHomebrew/decky-loader#197]
Installed as per directions.  Sudo password set and used, install appears to proceed without problems.  

Developer mode on, CEF remote debugging enabled.  I am not running Crankshaft, or Syncthing.

When I reboot, there's no plugin menu on the quick access menu. 

journalctl -u plugin_loader.service outputs:
```


Oct 03 20:20:58 steamdeck systemd[1]: Started SteamDeck Plugin Loader.
Oct 03 20:20:59 steamdeck PluginLoader[22822]: main.py:63: DeprecationWarning: There is no current event loop
Oct 03 20:20:59 steamdeck PluginLoader[22822]: [loader][INFO]: plugin_path: /home/deck/homebrew/plugins
Oct 03 20:20:59 steamdeck PluginLoader[22822]: [updater][INFO]: /home/deck/homebrew/services
Oct 03 20:20:59 steamdeck PluginLoader[22822]: [updater][INFO]: Current branch is not set, determining branch from version...
Oct 03 20:20:59 steamdeck PluginLoader[22822]: [updater][INFO]: Current version determined to be pre-release
Oct 03 20:20:59 steamdeck PluginLoader[22822]: [loader][INFO]: import plugins from /home/deck/homebrew/plugins
Oct 03 20:21:30 steamdeck PluginLoader[22822]: [updater][INFO]: Current branch is not set, determining branch from version...
Oct 03 20:21:30 steamdeck PluginLoader[22822]: [updater][INFO]: Current version determined to be pre-release
Oct 03 20:21:30 steamdeck PluginLoader[22822]: [updater][INFO]: Updated remote version information
Oct 03 20:21:42 steamdeck PluginLoader[22822]: [main][INFO]: Plugin loader isn't present in Steam anymore, reinjecting...
Oct 03 20:22:02 steamdeck PluginLoader[22822]: [main][INFO]: Plugin loader isn't present in Steam anymore, reinjecting...
Oct 03 20:22:02 steamdeck PluginLoader[22822]: [main][INFO]: Failed to inject JavaScript into tab
Oct 03 20:22:02 steamdeck PluginLoader[22822]: Traceback (most recent call last):
Oct 03 20:22:02 steamdeck PluginLoader[22822]:   File "main.py", line 127, in inject_javascript
Oct 03 20:22:02 steamdeck PluginLoader[22822]:   File "injector.py", line 91, in inject_to_tab
Oct 03 20:22:02 steamdeck PluginLoader[22822]:   File "injector.py", line 87, in get_tab
Oct 03 20:22:02 steamdeck PluginLoader[22822]: ValueError: Tab SP not found
Oct 03 20:22:04 steamdeck systemd[1]: Stopping SteamDeck Plugin Loader...
Oct 03 20:22:04 steamdeck PluginLoader[22822]: Traceback (most recent call last):
Oct 03 20:22:04 steamdeck PluginLoader[22822]:   File "plugin.py", line 15, in <module>
Oct 03 20:22:04 steamdeck PluginLoader[22822]:   File "multiprocessing/context.py", line 247, in set_start_method
Oct 03 20:22:04 steamdeck PluginLoader[22822]: RuntimeError: context has already been set
Oct 03 20:22:04 steamdeck PluginLoader[22822]: [22822] Failed to execute script 'plugin' due to unhandled exception!
Oct 03 20:22:04 steamdeck PluginLoader[22822]: ======== Running on http://127.0.0.1:1337/ ========
Oct 03 20:22:04 steamdeck PluginLoader[22822]: (Press CTRL+C to quit)
Oct 03 20:22:04 steamdeck systemd[1]: plugin_loader.service: Main process exited, code=exited, status=1/FAILURE
Oct 03 20:22:04 steamdeck systemd[1]: plugin_loader.service: Failed with result 'exit-code'.
Oct 03 20:22:04 steamdeck systemd[1]: Stopped SteamDeck Plugin Loader.
Oct 03 20:22:04 steamdeck systemd[1]: plugin_loader.service: Consumed 1.038s CPU time.
```
Uname -a

```
Linux steamdeck 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3 #1 SMP PREEMPT Mon, 08 Aug 2022 22:27:56 +0000 x86_64 GNU/Linux
```
Thanks for any advice you can provide!

**Comment by TrainDoctor** [comment]
> Installed as per directions. Sudo password set and used, install appears to proceed without problems.
> 
> Developer mode on, CEF remote debugging enabled. I am not running Crankshaft, or Syncthing.
> 
> When I reboot, there's no plugin menu on the quick access menu.
> 
> journalctl -u plugin_loader.service outputs:
> 
> ```
> 
> 
> Oct 03 20:20:58 steamdeck systemd[1]: Started SteamDeck Plugin Loader.
> Oct 03 20:20:59 steamdeck PluginLoader[22822]: main.py:63: DeprecationWarning: There is no current event loop
> Oct 03 20:20:59 steamdeck PluginLoader[22822]: [loader][INFO]: plugin_path: /home/deck/homebrew/plugins
> Oct 03 20:20:59 steamdeck PluginLoader[22822]: [updater][INFO]: /home/deck/homebrew/services
> Oct 03 20:20:59 steamdeck PluginLoader[22822]: [updater][INFO]: Current branch is not set, determining branch from version...
> Oct 03 20:20:59 steamdeck PluginLoader[22822]: [updater][INFO]: Current version determined to be pre-release
> Oct 03 20:20:59 steamdeck PluginLoader[22822]: [loader][INFO]: import plugins from /home/deck/homebrew/plugins
> Oct 03 20:21:30 steamdeck PluginLoader[22822]: [updater][INFO]: Current branch is not set, determining branch from version...
> Oct 03 20:21:30 steamdeck PluginLoader[22822]: [updater][INFO]: Current version determined to be pre-release
> Oct 03 20:21:30 steamdeck PluginLoader[22822]: [updater][INFO]: Updated remote version information
> Oct 03 20:21:42 steamdeck PluginLoader[22822]: [main][INFO]: Plugin loader isn't present in Steam anymore, reinjecting...
> Oct 03 20:22:02 steamdeck PluginLoader[22822]: [main][INFO]: Plugin loader isn't present in Steam anymore, reinjecting...
> Oct 03 20:22:02 steamdeck PluginLoader[22822]: [main][INFO]: Failed to inject JavaScript into tab
> Oct 03 20:22:02 steamdeck PluginLoader[22822]: Traceback (most recent call last):
> Oct 03 20:22:02 steamdeck PluginLoader[22822]:   File "main.py", line 127, in inject_javascript
> Oct 03 20:22:02 steamdeck PluginLoader[22822]:   File "injector.py", line 91, in inject_to_tab
> Oct 03 20:22:02 steamdeck PluginLoader[22822]:   File "injector.py", line 87, in get_tab
> Oct 03 20:22:02 steamdeck PluginLoader[22822]: ValueError: Tab SP not found
> Oct 03 20:22:04 steamdeck systemd[1]: Stopping SteamDeck Plugin Loader...
> Oct 03 20:22:04 steamdeck PluginLoader[22822]: Traceback (most recent call last):
> Oct 03 20:22:04 steamdeck PluginLoader[22822]:   File "plugin.py", line 15, in <module>
> Oct 03 20:22:04 steamdeck PluginLoader[22822]:   File "multiprocessing/context.py", line 247, in set_start_method
> Oct 03 20:22:04 steamdeck PluginLoader[22822]: RuntimeError: context has already been set
> Oct 03 20:22:04 steamdeck PluginLoader[22822]: [22822] Failed to execute script 'plugin' due to unhandled exception!
> Oct 03 20:22:04 steamdeck PluginLoader[22822]: ======== Running on http://127.0.0.1:1337/ ========
> Oct 03 20:22:04 steamdeck PluginLoader[22822]: (Press CTRL+C to quit)
> Oct 03 20:22:04 steamdeck systemd[1]: plugin_loader.service: Main process exited, code=exited, status=1/FAILURE
> Oct 03 20:22:04 steamdeck systemd[1]: plugin_loader.service: Failed with result 'exit-code'.
> Oct 03 20:22:04 steamdeck systemd[1]: Stopped SteamDeck Plugin Loader.
> Oct 03 20:22:04 steamdeck systemd[1]: plugin_loader.service: Consumed 1.038s CPU time.
> ```
> 
> Uname -a
> 
> ```
> Linux steamdeck 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3 #1 SMP PREEMPT Mon, 08 Aug 2022 22:27:56 +0000 x86_64 GNU/Linux
> ```
> 
> Thanks for any advice you can provide!

Are you running the latest preview or beta branches on the deck?

There's a known issue at least on the preview branch with the new beta that added custom bootloader animation support that borked decky's ability to inject into the QAM, but all other functionality has stayed intact.

**Comment by Wintersdark** [comment]
That could be the case.  I'm running beta, I believe (see uname output) and I DID get a decoy update notification.  However, without the QAM menu, how can I install/use plugins?

If I revert to release version, install and configure plugins, then go back to beta will they (theoretically) continue working?  Or will the SteamOS version changing wipe out decky and require a reinstall?

**Comment by TrainDoctor** [comment]
This isn't an issue relating to the pre-release branch of decky-loader. Changing branches on the deck won't effect decky luckily. Going back to the beta will just bring the issue back.
If continuing to have decky is important to you, swap over to the stable steam deck branch. Otherwise, we're actively attempting to diagnose and fix the issue (while still getting sleep).

**Comment by Wintersdark** [comment]
For sure.  Welp, I'm more interested in Decky than the beta SteamOS version now that the last set of input changes have made it to stable, so I'll go that way.

Thank you for your assistance and all your work here, it's very much appreciated.
