### ISSUE TITLE
The Decky tab is no longer visible in the QAM on the latest Steam Beta.

### ISSUE THREAD

**Issue by JediRhymeTrix** [SteamDeckHomebrew/decky-loader#202]
The "plug" icon in the QAM doesn't show up but the plugins seem to be working fine. CSS loader themes, audio loader sounds, etc. that were enabled before the update are all working.

_Sent from my Galaxy Note9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Mezque** [comment]
Known issue, there should be a fix soon because there is a merge request with a fix pending atm.

**Comment by JediRhymeTrix** [comment]
@Mezque yes, i just realised that my issue duplicates a couple of closed issues. I'm not sure why they've been closed before the fix is out, but I guess that's up to the maintainers. I'm gonna go ahead and close this one. Thanks!

_Sent from my Galaxy Note9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by TrainDoctor** [comment]
> @Mezque yes, i just realised that my issue duplicates a couple of closed issues. I'm not sure why they've been closed before the fix is out, but I guess that's up to the maintainers. I'm gonna go ahead and close this one. Thanks!
> 
> _Sent from my Galaxy Note9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

They've been closed as duplicates of another issue I pinned in the hopes folks would notice it.
