### ISSUE TITLE
v2.2.2-pre1 Borked Quick Access?

### ISSUE THREAD

**Issue by GeneStarwind09** [SteamDeckHomebrew/decky-loader#203]
I upgraded to the latest prerelease and Decky vanished from quick access. I tried a reinstall and nothing. I'll try switching to stable tomorrow but just figured I'd give you a heads-up.

**Comment by TrainDoctor** [comment]
v2.2.2-pre1 is indentical to v 2.2.1 on stable.

**Comment by GeneStarwind09** [comment]
I tried an uninstall of Decky and then an install of stable. I can see that it installed because I get the notification upon boot saying an update is available. However, it's not in quick access.

**Comment by GeneStarwind09** [comment]
I uninstalled Decky and then installed the stable version. I can tell that it installed because I get the notification saying there's an update. However, it isn't in quick access.

**Comment by TrainDoctor** [comment]
Please restart your deck if you haven't already. Just in case.

**Comment by PartyWumpus** [comment]
If you're still getting the notification that there's an update you're probably not on the newest version? Try reinstalling/updating by tapping on the notification

**Comment by TrainDoctor** [comment]
According to testers, this issue should be fully resolved on pre-release v2.2.3-pre1. Please install this version via the pre-release install script if you can't get the update notification. @re11ding and @GeneStarwind09.

**Comment by re11ding** [comment]
It worked! It's no longer disappearing from what I can tell. Thanks for fixing that up!

**Comment by GeneStarwind09** [comment]
Worked for me too, cheers.
