### ISSUE TITLE
No way to check version numbers while checking for an update

### ISSUE THREAD

**Issue by becauseimgray** [SteamDeckHomebrew/decky-loader#204]
It's a small request, but could the version numbers still be shown while decky is checking for an update?

I've had it to where its automatically checking for an update(I don't even have to hit the "check for updates" button) and its taking a while. When I go to check the version number against the one on github, I have no way of doing so, as it doesn't display what version of decky I am running while its still checking. I imagine for people who are on-the-go, this is a much more common issue, since checking could be happening during spotty or poor internet sessions.

**Comment by TrainDoctor** [comment]
Hey, can you test for this behavior by swapping between the latest stable and pre-release versions of Decky Loader? If so if you could get a recording that would be great. Simply swap over to the stable branch, install it. Then swap over to pre-release and monitor if the current version is hidden as you described when you first filed the issue. Thanks!

**Comment by TrainDoctor** [comment]
Closed as current behavior shows current version even when checking for updates.
