### ISSUE TITLE
Can't reinstall Decky

### ISSUE THREAD

**Issue by manuelx98** [SteamDeckHomebrew/decky-loader#205]
Recently I updated my Steam Deck and Decky vanished from SteamUI, even if some things still worked, like my theme and the custom SFXs. So I went to Desktop mode and tried reinstalling it, but I got many unknown errors and I don't know what to do. Tried with sudo too but nothing changed. I'm not sure of the version I was using since I can't check it now, but I was using the Stable branch. Below the errors:

`(deck@steamdeck ~)$ curl -L https://github.com/SteamDeckHomebrew/decky-loader/raw/main/dist/install_release.sh | sh`
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current`
`                                 Dload  Upload   Total   Spent    Left  Speed`
`  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0`
`100  1559  100  1559    0     0   4334      0 --:--:-- --:--:-- --:--:--  4334`
`Installing Steam Deck Plugin Loader release...`
`sh: line 4: /home/linuxbrew/.linuxbrew/bin/getent: No such file or directory`
`mkdir: cannot create directory '/homebrew': Permission denied`
`mkdir: cannot create directory '/homebrew': Permission denied`
`Installing version v2.2.1...`
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current`
`                                 Dload  Upload   Total   Spent    Left  Speed`
`  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0`
`  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file /homebrew/services/PluginLoader: No such `
`Warning: file or directory`
`  0 21.7M    0  1369    0     0   2151      0  2:56:21 --:--:--  2:56:21  4062`
`curl: (23) Failure writing output to destination`
`chmod: cannot access '/homebrew/services/PluginLoader': No such file or directory`
`sh: line 19: /homebrew/services/.loader.version: No such file or directory`
`Created symlink /etc/systemd/system/multi-user.target.wants/plugin_loader.service -> /etc/systemd/system/plugin_loader.service.
`

**Comment by manuelx98** [comment]
> That's pretty weird. If Decky is still partly working (as in themes still applying etc) you should be able to update by tapping on the 'update decky' notification that pops up when you boot into game mode. Otherwise, run the uninstall script and then try re-running the install script.

After the errors I rebooted and now the themes and SFXs are gone. I tried the uninstall script but same errors:
`(deck@steamdeck ~)$ curl -L https://github.com/SteamDeckHomebrew/decky-loader/raw/main/dist/uninstall.sh | sh`
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current`
`                                 Dload  Upload   Total   Spent    Left  Speed`
`  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0`
`100   582  100   582    0     0    996      0 --:--:-- --:--:-- --:--:-- 24250`
`[sudo] password for deck: `
`Uninstalling Steam Deck Plugin Loader...`
`sh: line 4: /home/linuxbrew/.linuxbrew/bin/getent: No such file or directory`
`Removed /etc/systemd/system/multi-user.target.wants/plugin_loader.service.`
`rm: cannot remove '/homebrew/services/PluginLoader': No such file or directory`
`(1)(deck@steamdeck ~)$ curl -L https://github.com/SteamDeckHomebrew/decky-loader/raw/main/dist/install_release.sh | sh`
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current`
`                                 Dload  Upload   Total   Spent    Left  Speed`
`  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0`
`100  1559  100  1559    0     0   8928      0 --:--:-- --:--:-- --:--:--  8928`
`Installing Steam Deck Plugin Loader release...`
`sh: line 4: /home/linuxbrew/.linuxbrew/bin/getent: No such file or directory`
`mkdir: cannot create directory '/homebrew': Permission denied`
`mkdir: cannot create directory '/homebrew': Permission denied`
`Installing version v2.2.1...`
`  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current`
`                                Dload  Upload   Total   Spent    Left  Speed`
`  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0`
`  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file /homebrew/services/PluginLoader: No such `
`Warning: file or directory`
`  0 21.7M    0   876    0     0   1888      0  3:20:56 --:--:--  3:20:56  4921`
`curl: (23) Failure writing output to destination`
`chmod: cannot access '/homebrew/services/PluginLoader': No such file or directory`
`sh: line 19: /homebrew/services/.loader.version: No such file or directory`
`Created symlink /etc/systemd/system/multi-user.target.wants/plugin_loader.service -> /etc/systemd/system/plugin_loader.service.
`

**Comment by manuelx98** [comment]
> hmm it's failing to create the directories because it doesn't have permission.
> 
> I'm not totally sure if it works, but try putting the sudo in-between the `|` and `sh`
> 
> `curl -L https://github.com/SteamDeckHomebrew/decky-loader/raw/main/dist/uninstall.sh | sudo sh` and `curl -L https://github.com/SteamDeckHomebrew/decky-loader/raw/main/dist/install_release.sh | sudo sh`

Nothing changed unfortunately, same output in both.

**Comment by NGnius** [comment]
Do you have another user on your steam deck? Looks like it's trying to use `linuxbrew` for some user stuff

**Comment by HollyCeuin** [comment]
I am also having this issue, though the solution manuelx98 is not applicable to my deck
