### ISSUE TITLE
Per User/Account Plugin Settings

### ISSUE THREAD

**Issue by Sky-rym** [SteamDeckHomebrew/decky-loader#207]
Having to disable and enable the themes or sounds I want in the settings with a shared deck is tedious so I would just like to have plugin settings be on a per user basis.

**Comment by FormBurden** [comment]
I agree with this. Would be a great feature.

+1

**Comment by TrainDoctor** [comment]
While definitely advantageous, this would be tricky to implement and we have our focus pretty split at the moment.
Open to PRs on this one.

**Comment by TrainDoctor** [comment]
Still open to PRs for this but I'm closing this as stale since our team hasn't had anyone express an interest in working on such a feature.
