### ISSUE TITLE
Plugins after restarting Steam Deck in dock mode do not work

### ISSUE THREAD

**Issue by TheKerevas** [SteamDeckHomebrew/decky-loader#209]
Restarting Steam Deck connected to an external screen the plugins do not load and sometimes Decky does not load either. Restarting Steam Deck with no external display connected and then connecting the display everything works

Decky Stable version 2.2.1

**Comment by nabel0** [comment]
Can you try to just plug the HUB/Dock in with nothing else connected (no HDMI,  Ethernet, etc) and restart the deck.

**Comment by nabel0** [comment]
Im using an Anker Power Expand 8-in-1 USB-C Hub (Model A8383)

[loader.log](https://github.com/SteamDeckHomebrew/decky-loader/files/9735221/loader.log)

**Comment by Godsbane** [comment]
Tested using an insignia switch dock with a usb extender, and MCY 7 in 1 Multiport USB C Hub.
SteamOS Stable, Decky Stable
cssloader
vibrantdeck
powertools
system toolbox
pause games
mangoHUD

[insignialoader.log](https://github.com/SteamDeckHomebrew/decky-loader/files/9735600/insignialoader.log)

**Comment by nabel0** [comment]
> Tested using an insignia switch dock with a usb extender, and MCY 7 in 1 Multiport USB C Hub. SteamOS Stable, Decky Stable cssloader vibrantdeck powertools system toolbox pause games mangoHUD
> 
> [insignialoader.log](https://github.com/SteamDeckHomebrew/decky-loader/files/9735600/insignialoader.log)

Do you get the same problem?

**Comment by TheKerevas** [comment]
I use a Sabrent 5 port hub, there is only HDMI and power connected, nothing else. I have to try with only the HUB connected

**Comment by Patient6038** [comment]
I'm getting this same issue but without dock mode. Recently formatted my deck back to factory settings, on the latest update of steamOS (stable 3.3.2) and after rebooting, (once installed) it does work (which was decky v2.2.1). But then if I reboot again after that, it doesnt load and doesnt show up in the quick menu. The only way to keep it loaded is to reinstall it every time for me.

**Comment by TrainDoctor** [comment]
> I'm getting this same issue but without dock mode. Recently formatted my deck back to factory settings, on the latest update of steamOS (stable 3.3.2) and after rebooting, (once installed) it does work (which was decky v2.2.1). But then if I reboot again after that, decky doesnt load and doesnt show up in the quick menu. The only way to keep it loaded is to reinstall it every time for me.

Are you running CSSLoader?

**Comment by TrainDoctor** [comment]
According to testers, this issue should be solved on pre-release v2.2.3-pre1. Please install this version via the pre-release install script if you can't get the update notification.

**Comment by TrainDoctor** [comment]
> According to testers, this issue should be solved on pre-release v2.2.3-pre1. Please install this version via the pre-release install script if you can't get the update notification.

@Patient6038 @TheKerevas @Godsbane

**Comment by TheKerevas** [comment]
> According to testers, this issue should be solved on pre-release v2.2.3-pre1. Please install this version via the pre-release install script if you can't get the update notification.

Many thanks, as soon as I can install this version and try to see if it doesn't happen to me anymore

**Comment by TheKerevas** [comment]
I confirm that it does not happen to me anymore, I have the stable 2.2.3, so it has been fixed. Thank you very much
