### ISSUE TITLE
Large Library UI issue with 5 per line and backgrounds

### ISSUE THREAD

**Issue by staticnation** [SteamDeckHomebrew/decky-loader#210]
Video of the issue:
https://www.youtube.com/watch?v=lgNAGu7zkKM

Thread where plugins were identified as the cause:
https://www.reddit.com/r/DeckSupport/comments/xyg86x/comment/irh7zam/

**Comment by TrainDoctor** [comment]
This is an issue for the relevant plugin developer.

**Comment by staticnation** [comment]
Fair, I just wanted to report it (so it's a known issue), do you happen to know the Github for the CSS plugin?
