### ISSUE TITLE
QAM lags whenever decky is installed

### ISSUE THREAD

**Issue by PartyWumpus** [SteamDeckHomebrew/decky-loader#213]
not sure of the cause, or how long this has been occurring for, but thought it was worth opening an issue anyway. Occurs on all branches right now.

**Comment by pdcook** [comment]
Can confirm that it's been occuring since at least late September.

**Comment by TrainDoctor** [comment]
Good news, we should have a pre-release out soon to address the lag in the QAM and the gamescope crashes in the same action.

**Comment by pdcook** [comment]
> Good news, we should have a pre-release out soon to address the lag in the QAM and the gamescope crashes in the same action.

Amazing! You guys are great.

**Comment by AAGaming00** [comment]
Fixed on pre-release.
