### ISSUE TITLE
Support i18n

### ISSUE THREAD

**Issue by david082321** [SteamDeckHomebrew/decky-loader#219]
Did you have any plan to support other languages?

**Comment by PartyWumpus** [comment]
issue #78

**Comment by TrainDoctor** [comment]
> Take a look at issue #78

This is a request to support spoken/written human languages, which we don't have a plan laid out for at the moment but we're open to PRs on the matter. We have a ton of moving components on this project so adding localization would be great, but would further split our focus to a degree we can't sustain.

**Comment by RodoMa92** [comment]
I'm taking a look right now to this, testing different strategies, as soon as I can make a working prototype I'll open a PR for RFC on the matter.

**Comment by RodoMa92** [comment]
My progress can be found on [this](https://github.com/RodoMa92/decky-loader/tree/i18n) branch of my fork, if anyone is interested on the progress or want to help me.

**Comment by Lrss** [comment]
@RodoMa92 Are you open to contributions of other language translations right now, or would you rather wait till the feature is stable?

**Comment by RodoMa92** [comment]
For languages it's better to wait until I've at least nailed down a foundation, in order to avoid to waste people time.

**Comment by AAGaming00** [comment]
> My progress can be found on [this](https://github.com/RodoMa92/decky-loader/tree/i18n) branch of my fork, if anyone is interested on the progress or want to help me.

We've discussed this internally and we plan on using selfhosted Weblate for translation contributions, please try to make this compatible with it

**Comment by AAGaming00** [comment]
Also instead of using http to fetch translations it might make more sense to dynamic import them from the localhost backend

and if we ever want to split them out of the pluginloader build we can handle downloading and importing them in the backend and importing them

**Comment by RodoMa92** [comment]
> Also instead of using http to fetch translations it might make more sense to dynamic import them from the localhost backend
> 
> and if we ever want to split them out of the pluginloader build we can handle downloading and importing them in the backend and importing them

Yea, I was evaluating on how to handle that. I think for now to add a static route in the backend python server for dev. Further down I'll see which other approach I can use, but I'm not really a frontend guy, so I'm open to suggestions on that.

**Comment by RodoMa92** [comment]
I finally have an initial working prototype. All strings have been extracted, the decky backend now serve the corresponding json files needed for localization, the language is synced with the Steam browser language (if the language of the Steam client change, the UI localization also change to that language (translation permitting)), and AFAICS the settings page is perfectly working now. As soon as I have additional time I'll open a pull request for comments.

**Comment by RodoMa92** [comment]
The RFC is up as of now, #361, if someone want to take a look at it.

Marco.

**Comment by RodoMa92** [comment]
The feature is now in the prerelease, I think this can be closed now 😄

**Comment by david082321** [comment]
Fix by #361
