### ISSUE TITLE
[BUG] Toaster does not initialize in the latest Prerelease version

### ISSUE THREAD

**Issue by Ciaxur** [SteamDeckHomebrew/decky-loader#220]
In the latest prerelease version [v2.3.0-pre1][1], the `node.stateNode`, [here](https://github.com/SteamDeckHomebrew/decky-loader/blob/6e3c05072cb507e2a376b7019836bea7bf663cb0/frontend/src/toaster.tsx#L44), is null, thus causes the following uncaught exception:
```sh
Uncaught (in promise) TypeError: Cannot set property 'render' of null
    at Toaster.init
```

I suspect the change (by @AAGaming00) to the `toaster.tsx`, [here](https://github.com/SteamDeckHomebrew/decky-loader/pull/211/files#diff-d7170148e39f6c73c12db35463435661a8b5fd8929525ac57a49e108da6776c7L41), was unintentional as the toaster revert in commit 3ac0abc, reverts the node's value of `instance.sibling.child` -> `instance.return.return`.

[1]: https://github.com/SteamDeckHomebrew/decky-loader/releases/tag/v2.3.0-pre1

**Comment by TrainDoctor** [comment]
> In the latest prerelease version [v2.3.0-pre1](https://github.com/SteamDeckHomebrew/decky-loader/releases/tag/v2.3.0-pre1), the `node.stateNode`, [here](https://github.com/SteamDeckHomebrew/decky-loader/blob/6e3c05072cb507e2a376b7019836bea7bf663cb0/frontend/src/toaster.tsx#L44), is null, thus causes the following uncaught exception:
> 
> ```shell
> Uncaught (in promise) TypeError: Cannot set property 'render' of null
>     at Toaster.init
> ```
> 
> I suspect the change (by @AAGaming00) to the `toaster.tsx`, [here](https://github.com/SteamDeckHomebrew/decky-loader/pull/211/files#diff-d7170148e39f6c73c12db35463435661a8b5fd8929525ac57a49e108da6776c7L41), was unintentional as the toaster revert in commit [3ac0abc](https://github.com/SteamDeckHomebrew/decky-loader/commit/3ac0abc82bd266eecb7c5f468481e364790be665), reverts the node's value of `instance.sibling.child` -> `instance.return.return`.

Thanks for the report, go ahead and give the pre-release I put out and see if that resolved the issue.

**Comment by Ciaxur** [comment]
Awesome, thanks for the fast response! Confirmed updating to the latest prerelease [v2.3.0-pre2](https://github.com/SteamDeckHomebrew/decky-loader/releases/tag/v2.3.0-pre2), fixed the issue and Toaster is toasting :).
