### ISSUE TITLE
add a css override to make suspend videos play full screen

### ISSUE THREAD

**Issue by ask-compu** [SteamDeckHomebrew/decky-loader#222]
the fix on steamdeckrepo's website is
```
Navigate to /home/deck/.local/share/Steam/steamui/css/ using Dolphin.
Open 3991.css with Notepadqq.
Find {flex-grow:0;width:300px;height:300px} in the file and replace it with {flex-grow:1;width:0100%;height:0100%}.
```
can't this be done automatically by an override?

there is also a js mod that allows longer boot videos
```
Navigate to ~/.local/share/Steam/steamui/ using Dolphin.
Open library.js with Notepadqq.
Find (s,1e4,[]) in the file and replace 1e4 (10 seconds) with 2e4 (20 seconds), or however long you need.
```
however the steam os beta reportedly already increases this limit to 30 seconds so the js mod probably won't be needed

**Comment by TrainDoctor** [comment]
This issue is not for the decky-loader team and is for the Animation Changer dev(s).
https://github.com/TheLogicMaster/SDH-AnimationChanger/tree/f29d591e8ae1e0e827d93dd5b6fb24a8e7cf2ac7

**Comment by ask-compu** [comment]
oh sorry, i must've used the wrong browser tab when making the issue
