### ISSUE TITLE
Start using new `image_url` field for getting the image for the plugin in the store listing.

### ISSUE THREAD

**Issue by gbdlin** [SteamDeckHomebrew/decky-loader#224]
Currently, image URL is constructed from plugin name. New `image_url` field was introduced in the store API, so we can swap the image if needed. Store view in loader should start using this field instead of constructing the URL on it's own.

**Comment by TrainDoctor** [comment]
Now utilized as of 2e6b3834da357c7e81821ce60bad36f54dd9fa6e.
