### ISSUE TITLE
Send header with decky version when querying store for list of plugins

### ISSUE THREAD

**Issue by gbdlin** [SteamDeckHomebrew/decky-loader#225]
We need a way to track if there is a significant number of users still using older versions of decky to properly plan removal deprecated features from the storefront. For that, decky has to send it's version to the storefront. This should be achieved by sending a custom header with each request containing the version number. Please come up with a suitable header name.

**Comment by AAGaming00** [comment]
I propose `X-Decky-Version: x.y.z`

For the future I suggest we return some kind of status code and add handling client-side for when the version is too old to prompt an update. For current outdated versions without this handling I suggest returning one plugin named "please update decky in settings" or something like that.

**Comment by TrainDoctor** [comment]
Added as of https://github.com/SteamDeckHomebrew/decky-loader/commit/c546a818f116d3344da1a9c866555036fcb9a7cc.
