### ISSUE TITLE
Edit order of plugins 

### ISSUE THREAD

**Issue by Martan404** [SteamDeckHomebrew/decky-loader#226]
I don't like the way my plugins are organized by time of install. It would be nice if we could change it ourselves

**Comment by TrainDoctor** [comment]
We're aware and working with a plugin developer to incorporate such functionality. This is a duplicate of discussion #175 but I'll leave it up and pin it so we don't get more duplicates.

**Comment by TrainDoctor** [comment]
This will be closed by #378.
