### ISSUE TITLE
with new steam deck beta and prieview broke decky.

### ISSUE THREAD

**Issue by blastermaster77** [SteamDeckHomebrew/decky-loader#228]
Now decky loader does not appear with the new update, back to stable. https://store.steampowered.com/news/app/1675200?emclan=103582791470414830&emgid=3414317363013182309

**Comment by TrainDoctor** [comment]
Thanks for the report, for now we recommend users swap to stable steamos for the moment. We're tracking the issue and any logs you can provide would be greatly appreciated.

**Comment by BananaAcid** [comment]
Addition: The settings button is gone, but the injections / CEF still work. CSS Loader still does its job.

**Comment by suchmememanyskill** [comment]
I have some obvservations:
- Steam changed some of their tab names.
![unknown](https://user-images.githubusercontent.com/38142618/197175096-67cfedf8-aed0-45bc-a934-22b66fccc86c.png)
- Decky does not seem to get loaded at all in the frontend
![Screenshot 2022-10-21 122343](https://user-images.githubusercontent.com/38142618/197175257-54597466-78a8-4fe7-bab0-a8e042df72fa.jpg)
- Decky's steam reload is borked

Log with no plugins. The failed to inject SP thing is probably due to decky failing to restart steam, so until i restarted steam not a lot happened
[decky.log](https://github.com/SteamDeckHomebrew/decky-loader/files/9838182/decky.log)

**Comment by JediRhymeTrix** [comment]
@suchmememanyskill you might be onto something here. The QAM and Steam menu aren't being skinned by CSS Loader themes, but the rest of the system UI is. The issue might have something to do with the change in the identifiers for the menus.

**Comment by suchmememanyskill** [comment]
> @suchmememanyskill you might be onto something here. The QAM and Steam menu aren't being skinned by CSS Loader themes, but the rest of the system UI is. The issue might have something to do with the change in the identifiers for the menus.

I've already made sure this weird tab update won't affect themes (re-mapping the tab targets), it's in the latest dev branch of cssloader. For decky i think it's another issue

**Comment by TrainDoctor** [comment]
AA is currently working on deep re-writes to the backend towards fixing this. Update soon:tm:.

**Comment by subworx** [comment]
Yay, looking forward to this :) With current stable OS and beta client, decky doesn't work at all, even in the background - e.g. protondb badges are gone.

**Comment by Zodiaksl** [comment]
Hope progress is going well guys. All of the Steam Deck community is cheering you along and we hope to hear good news soon! :smile:

**Comment by AAGaming00** [comment]
This is fixed in the latest prerelease of decky.

**Comment by L0WR1D3Rz** [comment]
Decky isn't working on latest preview. I tried uninstalling decky, reboot, install latest pre-release / release (tried both) , reboot and nothing. Decky doesn't startup. Any fix?

**Comment by TrainDoctor** [comment]
> Decky isn't working on latest preview. I tried uninstalling decky, reboot, install latest pre-release / release (tried both) , reboot and nothing. Decky doesn't startup. Any fix?

Pre-release will inject inconsistently into the QAM. AA is working on a further patch to address this issue and get the estimated %15 (roughly) of times when Loader fails to inject to the QAM. Please sleep/unsleep the deck, try restarting the steam client and or the deck as a whole.

**Comment by L0WR1D3Rz** [comment]
Thank you Traindoctor

**Comment by thefunkygibbon** [comment]
am i right in thinking that this sort of thing is going to be an ongoing issue unless Valve makes some changes to the OS which allows for this sort of plugin feature?   I assume crankshaft has the same issues and there isn't any other way to make things more compatible from the plugin manager perspective?

**Comment by PartyWumpus** [comment]
> am i right in thinking that this sort of thing is going to be an ongoing issue unless Valve makes some changes to the OS which allows for this sort of plugin feature?

It seems likely (to me) that the amount of breaking changes made by valve will decrease over time as they get closer to their final vision of steamOS.
In my opinion they probably shouldn't make a full offical plugin system, both because that requires a lot of work from them and it will likely just add limits to the features of plugins. It would probably also slow steamOS development significantly.

> I assume crankshaft has the same issues and there isn't any other way to make things more compatible from the plugin manager perspective?

Crankshaft does have these same issues, although Decky using react to inject instead of directly manipulating the DOM does seem to make it easier to fix issues.

**Comment by james2432** [comment]
QAM doesn't seem to be getting injected more than 90% of the time. It doesn't matter if I sleep deck, reboot or fully power off. The plugins seem to be loading correctly as the cssloader is styling correctly, it's just hidden from the QAM, which sucks for using powertools

**Comment by TrainDoctor** [comment]
This should be fully addressed in the decky pre-release v2.3.1-pre2. Please provide any feedback and clarification/confirmation.

**Comment by james2432** [comment]
seems harder to make it fail at all(haven't been able to make it fail yet) 🤘

**Comment by thefunkygibbon** [comment]
> seems harder to make it fail at all(haven't been able to make it fail yet) 🤘

guess you're not running beta steamos/client then?    my decky disappeared again a day after installing it .. hadn't even got an update in that time so i've no idea where it went!?

**Comment by james2432** [comment]
> > seems harder to make it fail at all(haven't been able to make it fail yet) 🤘
> 
> guess you're not running beta steamos/client then? my decky disappeared again a day after installing it .. hadn't even got an update in that time so i've no idea where it went!?

decky 2.3.1-pre3 now
steamos latest preview 

still no issues with QAM not showing up like before

**Comment by TrainDoctor** [comment]
> > seems harder to make it fail at all(haven't been able to make it fail yet) 🤘
> 
> guess you're not running beta steamos/client then? my decky disappeared again a day after installing it .. hadn't even got an update in that time so i've no idea where it went!?

Please install the latest pre-release via install script again. There was a bug with a recent release where when it updated it pulled non-existent files as the systemd service.

**Comment by zhzy0077** [comment]
A quick heads up. SteamOS 3.4 gets promoted from Beta to Stable a few hours ago https://store.steampowered.com/news/app/1675200?emclan=103582791470414830&emgid=3646258449514531838

Will decky stable work if I hit upgrade button?

**Comment by TrainDoctor** [comment]
> A quick heads up. SteamOS 3.4 gets promoted from Beta to Stable a few hours ago https://store.steampowered.com/news/app/1675200?emclan=103582791470414830&emgid=3646258449514531838
> 
> Will decky stable continue to work if I upgraded to 3.4?

We're not aware or any issues. Many of our users run on the preview branch which was on 3.4 long before it even was close to stable.
