### ISSUE TITLE
Plugin Python Backend Unload Hook

### ISSUE THREAD

**Issue by TheLogicMaster** [SteamDeckHomebrew/decky-loader#229]
Currently, there doesn't seem to be any way of detecting plugin backend unloading, which is problematic when disposing of native resources. There's the `onDismount` hook in the frontend, which could be used to call a backend API function, but that doesn't seem to be sufficient. That probably wouldn't work when redeploying and both are getting reloaded. I think an `_unload` hook would be useful here.

**Comment by TrainDoctor** [comment]
Now implemented as of 6346da6fe54d39e972de2abca0dc38c29aa29ce9, with minor but probably not with sufficient documentation.
