### ISSUE TITLE
Reload Plugin Action in plugins list should also reload backend

### ISSUE THREAD

**Issue by TheLogicMaster** [SteamDeckHomebrew/decky-loader#230]
Currently, the reload action in the plugins list seems to just reload the front-end, and I don't see any server API which would facilitate a backend plugin reload in the first place. This would be an easy way to completely reload the plugin module without redeploying or restarting. Should just be a matter of adding an additional API endpoint that connects to the plugin loader.

**Comment by TrainDoctor** [comment]
> +1. I'm on the latest preview build and decky isn't working anymore. Icon doesn't appear after having followed the steps correctly. Is this actively being worked on?

This is not the issue relevant to what your experiencing. Please install the latest pre-release of decky-loader if you're on beta or preview branches of SteamOS.

**Comment by L0WR1D3Rz** [comment]
I accidentally posted it in the wrong issue thread apologies. Your solution doesn't solve it. Decky isn't working on latest preview. I tried uninstalling decky reboot install latest pre-release, reboot and nothing. Decky doesn't startup. I'll post this in the right thread now also.

**Comment by TrainDoctor** [comment]
https://github.com/SteamDeckHomebrew/decky-loader/blob/88cf90439bd5542c6c0ae91303821f6c0a49b1e1/backend/main.py#L87

todo:
Define new route with handler function, then:
1. stop plugin 
2. delete from plugin array
3. re-add plugin to array
4. start plugin 
5. JS will call route (js will be handled by AA)

**Comment by TrainDoctor** [comment]
Started initial work on this feature on the [SteamDeckHomebrew/decky-loader/tree/train/backend-reloads](https://github.com/SteamDeckHomebrew/decky-loader/tree/train/backend-reloads)

**Comment by TrainDoctor** [comment]
@AAGaming00 this is resolved with websockets correct?

**Comment by AAGaming00** [comment]
should be
