### ISSUE TITLE
Plugin Backend Instantiation

### ISSUE THREAD

**Issue by TheLogicMaster** [SteamDeckHomebrew/decky-loader#231]
Plugins having methods but being treated as if they are class methods but called as normal functions is just a hack. This leads to having to explicitly pass `self` as a parameter when calling any plugin methods, which ruins any IDE parameter inspections and is just not ideal. Better options would be instantiating the Plugin classes or marking methods as either static or class methods. This would be an easy change in the loader, but would require a mechanism for determining whether it's a "legacy" plugin or not (Not the existing concept of a legacy plugin in the loader...) and allow simple changes to existing plugins to enable usage as normal Python methods. This could be in the form of an option/manifest version in the `plugin.json` file or could be a name change in the module itself, such as `InstancePlugin`. It's possible to work around this issue in plugins by creating a proxy of sorts, but is still not ideal. There's also likely other side effects of using a class as an instance without instantiating it. 

If given a detection mechanism, I could implement this change.

**Comment by TrainDoctor** [comment]
Definitely a worthwhile suggestion but not something we have time to work on in the near future and have tagged it appropriately. Hopefully we can address this when the team finds the time.
