### ISSUE TITLE
Plugin Request - Change brightness when charging/not charging

### ISSUE THREAD

**Issue by davidcourtneypower** [SteamDeckHomebrew/decky-loader#233]
Apologies if this is the incorrect forum or format for posting this plugin idea:
It would be a nice feature/plugin to have your steam deck brightness automatically set to 100% when charging if it isn't 100% already.
Likewise brightness would return to previous value when no longer charging.
(maybe desired charging/not charging values could be set in a settings menu for the plugin).

Thank You!

**Comment by TrainDoctor** [comment]
While definitely an interesting idea, we don't accept plugin requests. Thanks for the enthusiasm regardless.
