### ISSUE TITLE
Custom Boot Animations wont work with Decky Loader

### ISSUE THREAD

**Issue by elNino0916** [SteamDeckHomebrew/decky-loader#236]
So I installed Decky-Loader and that deleted my custom boot animation. I re-pasted the boot animation and then the boot animation would work, but i can´t find the decky icon in the quick access menu, but the plugins are working.
Is this normal?

**Comment by TrainDoctor** [comment]
This is an issue to do with tab modification by plugins. We're actively working to address this.

**Comment by TrainDoctor** [comment]
Closing in favor of moving the relevant issue to the relevant plugin developer's page since this should now be fixed in recent revisions to decky-frontend-lib.
