### ISSUE TITLE
Steam Big Picture 2.0 Support For Windows?

### ISSUE THREAD

**Issue by BearGamesStudio** [SteamDeckHomebrew/decky-loader#237]
would it be possible to port a (possibly stripped down) version of Decky Loader for the new big picture for windows? it has the exact same ui as the steam deck. if not, I understand. but it'd be quite nice for us fellow non steam deck owners. Thank you for reading. :)

**Comment by PartyWumpus** [comment]
Response from a dev about to porting to windows (on discord)
![decky1](https://user-images.githubusercontent.com/48649272/198582274-85b54ba4-cda2-4ec6-b014-fab90a6801b7.png)

Decky can currently already run on desktop Linux with not too much work. (some plugins don't work)
![image](https://user-images.githubusercontent.com/48649272/198583429-5c31bde0-4fdb-4e9b-98d7-6ba122b979f0.png)
I doubt decky will get much support on desktops.

**Comment by BearGamesStudio** [comment]
ah, understandable, hopefullly some unofficial windows support will happen or something, only time will tell.

**Comment by BearGamesStudio** [comment]
is it at least possible to install this on windows? doens't matter how limited it might be on windows. if not, how do you install this on desktop linux?

**Comment by shawny43** [comment]
I don't understand why we should not just copy BetterDiscord idea and doing some injection with sorta similar way to Skins for Steam. Maybe there some work around that could work. Steam is coded on similar way to ElectronJS, React or others apps web based. There something we could do over there. For desktop users this could be the trick, right? Tell me if i got wrong.

**Comment by TrainDoctor** [comment]
The core Steam Client is has existed for decades. I can't even begin to summarize how incorrect your assessment is.
