### ISSUE TITLE
Hang when shutting down until systemd timeout

### ISSUE THREAD

**Issue by Kevadroz** [SteamDeckHomebrew/decky-loader#243]
This is probably my fault. but whenever I shut down my system (Arch Linux, Steam Deck) plugin_loader.service does not exit gracefully and I have to either wait the whole timeout or force halt with the power button.

This may be a problem with my installation but anyways, help?

**Comment by TrainDoctor** [comment]
We do not provide support for non-SteamOS installs. I suggest re-running the plugin installer as recent issues arose due to a mistake with the configuration of the plugin_loader.service unit to see if that helps. We don't have the scope or the scale to provide support outside of the deck itself.

**Comment by Kevadroz** [comment]
Bummer. I configured the service to use SIGKILL on shutdown as a workarround.

**Comment by AAGaming00** [comment]
Confirmed on SteamOS.

**Comment by TrainDoctor** [comment]
Profiler needed to determine source of timeout issues.

**Comment by desantienator** [comment]
@Kevadroz  can you share the workaround please?

**Comment by Kevadroz** [comment]
> @Kevadroz can you share the workaround please?

Add "KillSignal=SIGKILL" under [Service].

**Comment by TrainDoctor** [comment]
> > @Kevadroz can you share the workaround please?
> 
> Add "KillSignal=SIGKILL" under [Service].

I'll be adding this to the official installer systemd service files and closing the issue as this should resolve the issue for now.
