### ISSUE TITLE
SettingsManager puts json in ~/homebrew and not ~/homebrew/settings

### ISSUE THREAD

**Issue by Witherking25** [SteamDeckHomebrew/decky-loader#246]
here:
https://github.com/SteamDeckHomebrew/decky-loader/blob/db7bb236d87fab6163612a61ae62a4e5389d92cd/backend/settings.py#L13
you are not including "/settings" in the json path, so it puts it in the ~/homebrew directory.
i would assume settings go in settings directory, right?

**Comment by TrainDoctor** [comment]
Note: Considerations for backwards compat needed, some plugins already exist that assume incorrect placement of output json and will need to be accommodated.

**Comment by Witherking25** [comment]
they would have to hand that i believe. i have 2 plugins that do this, but since they go through settings manager, the json would just have to be moved. you could just have settings manager move all jsons into settings/

**Comment by TrainDoctor** [comment]
Resolved in aec7063
