### ISSUE TITLE
Show "Back" in footer in the QAM while in-game and in a plugin's menu.

### ISSUE THREAD

**Issue by AAGaming00** [SteamDeckHomebrew/decky-loader#249]
![81a7f7a0-a97f-4524-ab16-c0074fa220a0.jpg](https://user-images.githubusercontent.com/42613600/200181610-9819ef28-27b7-469f-99dc-6e5764bbc96f.jpg)

This should show "B: Back", it currently does not which is misleading.

**Comment by AAGaming00** [comment]
This doesn't seem as simple as I thought. Something is blocking the "Back" item from showing up in the QAM, even if explicitly defined in `actionDescriptionMap`

**Comment by AAGaming00** [comment]
Also this is a pain to debug right now as the QAM footer is currently invisible when in-game due to a positioning issue on the latest Steam update.

**Comment by TrainDoctor** [comment]
@AAGaming00 close this since I'm pretty sure this is long since resolved.

**Comment by AAGaming00** [comment]
they deleted the qam footer by accident lmao
