### ISSUE TITLE
How do you install decky on hardware that isn't a steam deck?

### ISSUE THREAD

**Issue by BearGamesStudio** [SteamDeckHomebrew/decky-loader#250]
is it at least possible to install this on windows? doens't matter how limited it might be on windows. if not, how do you install this on desktop linux?

**Comment by TrainDoctor** [comment]
No, it is not possible to install on windows at the current moment.

**Comment by PartyWumpus** [comment]
You should just be able to use the regular installer on desktop linux. You might need to install jq or other parts used in the installer, as they may not be installed on your machine.

**Comment by TrainDoctor** [comment]
> if not, how do you install this on desktop linux?
A decently up to date desktop linux distro should fit the bill.

**Comment by BearGamesStudio** [comment]
i've tried installing it on pop! os, but i get this error that says "sh: 3: [: Illegal number:".

**Comment by TrainDoctor** [comment]
> i've tried installing it on pop! os, but i get this error that says "sh: 3: [: Illegal number:".

It looks like you're typing the incorrect character. You need to use ``|`` instead of ``[``.

**Comment by BearGamesStudio** [comment]
i copy pasted the code from the readme.md, that of which uses the correct symbol

**Comment by TrainDoctor** [comment]
> i copy pasted the code from the readme.md, that of which uses the correct symbol

Please post the output of your log here. I suspect a tool used by the script does not exist or is older than what the script expects.

**Comment by BearGamesStudio** [comment]
i'm so sorry if this is an dumb question, but how do i get konsole to output logs?

**Comment by TrainDoctor** [comment]
> ... how do i get konsole to output logs?

Not a dumb question at all, especially if you're new to linux.

Steps to grab logs to help us diagnose the issue:

1. Reboot your deck fully (this is to clean up the logs that are grabbed).
2. Open Konsole in desktop mode (or if you have ssh access run it after logging in via ssh).
3. Run ``cd ~`` to ensure you are located at ``/home/deck`` when running the next command.
4. Run ``journalctl -b0 -u plugin_loader.service > backend.log``, which will generate ``backend.log`` at ``/home/deck/backend.log``.
5. Grab the file and upload it to this thread.

**Comment by BearStudiosDev** [comment]
Did those commands, ended up with an empty log file. Just saying, I’m not on deck, I’m on a PC, using pop os.

**Comment by TrainDoctor** [comment]
> Did those commands, ended up with an empty log file. Just saying, I’m not on deck, I’m on a PC, using pop os.

The file should still be there but in your user directory so ``/home/yourusername/``. If you can't get the logs that's okay. I'd like to help but I can't spend a lot of time going out of my way, apologies.

**Comment by BearStudiosDev** [comment]
My apologies, I can’t get the log file. I’m stumped.

**Comment by BearStudiosDev** [comment]
So, Holoiso just came out with an update that fixes it, I’m gonna go test decky there, I’ll report back once I’ve tested.

**Comment by JohnGhostly** [comment]
> Member

Im having the same issue. The log file generated simply says -- No entries --
