### ISSUE TITLE
Plugins with erroring frontends do not appear in plugin list and cannot be uninstalled

### ISSUE THREAD

**Issue by Skullkiddd** [SteamDeckHomebrew/decky-loader#251]
On startup a error message is shown on the right corner for a removed plugin (mangohud).
The plugin is not in the plugin list anymore

**Comment by AAGaming00** [comment]
When a plugin frontend fails to load it no longer shows up in the plugin list. You can work around this hy finding the files of that plugin in ~/homebrew and deleting them.

A good solution for this would to be to push a placeholder into the plugins array instead and have it's content just show the error and inform the user they can uninstall/update it in settings.

**Comment by Skullkiddd** [comment]
> 

Works with sudo rm - r (plugin folder), in context menu move to trash is greyed out.

Thanks for workaround

**Comment by TrainDoctor** [comment]
Erroring plugins will now show up with the error they encounter in the plugin array with an error icon and can be uninstalled like any other functioning plugin as of 093b064.
