### ISSUE TITLE
Bootloop when I have multiple accounts

### ISSUE THREAD

**Issue by unicornsandcandies** [SteamDeckHomebrew/decky-loader#255]
Since the newest steam deck stable update, my device is going bootloop when decky starts (i see it for example because my menu music from css loader starts playing) on a start screen when I have to pick an account. Everything starts normal to the choose an account menu but decky starts in the background and is crashing everything to the point of boot animation loading again. I have three accounts and only use one but I need the other two and unfortunately there's no way to autolog to my account only so I'm stuck with this issue.

**Comment by DarkSide1305** [comment]
Do you have SteamlessTimes installed? If yes there is a known problem about Bootloops that is currently being worked on to be fixed

**Comment by unicornsandcandies** [comment]
> Do you have SteamlessTimes installed? If yes there is a known problem about Bootloops that is currently being worked on to be fixed

Yeah, I had this. I've managed to click my profile before decky launched and there was an update for steamlesstimes. I've installed it and now everything seems to work the way it worked before. It works for now
