### ISSUE TITLE
Decky icon disappears when restarting steam

### ISSUE THREAD

**Issue by ch604** [SteamDeckHomebrew/decky-loader#256]
After restarting steam (steam button, power, restart steam), the decky icon disappeared, and the only solution was to completely reboot the deck. Not sure if this is caused by the service not starting in the right order?

**Comment by TrainDoctor** [comment]
Please refile this issue with the new issue template and provide the logs and information it requests. This way we can attempt to replicate and debug the issue. Thanks in advance.
