### ISSUE TITLE
Loader - Auto updates for the plugin loader

### ISSUE THREAD

**Issue by SpyrexDE** [SteamDeckHomebrew/decky-loader#26]
To get all users to the newest release there should be a check on startup if the loader is up to date. When it isn't just run the install command.

**Comment by AAGaming00** [comment]
Checklist for implementing update notifications and an updater into the loader:
Backend:
- [ ] Method to check if the current installation of the loader is up to date, and return the current version, latest version, and patch notes to the frontend
- [ ] Method to update the current installation of the loader, restart it, and reload SP (without restarting Steam)
Frontend:
- [ ] Check on startup and periodically (every couple hours) with the backend for a new available version
- [ ] Notify the user with a toast notification that there is a new version available
- [ ] A button-text combo in general settings to:
     - [ ] Show the latest and current version of the loader.
     - [ ] Offer a button to trigger an update if one is available 
     - [ ] Show patch notes

**Comment by TrainDoctor** [comment]
> Checklist for implementing update notifications and an updater into the loader: Backend:
> 
>     * [ ]  Method to check if the current installation of the loader is up to date, and return the current version, latest version, and patch notes to the frontend
> 
>     * [ ]  Method to update the current installation of the loader, restart it, and reload SP (without restarting Steam)
> 
> 
> Frontend:
> 
>     * [ ]  Check on startup and periodically (every couple hours) with the backend for a new available version
> 
>     * [ ]  Notify the user with a toast notification that there is a new version available
> 
>     * [ ]  A button-text combo in general settings to:
>       
>       * [ ]  Show the latest and current version of the loader.
>       * [ ]  Offer a button to trigger an update if one is available
>       * [ ]  Show patch notes

Will move this comment to a new issue for clarity's sake. Thanks @AAGaming00.
