### ISSUE TITLE
Some plugins not work

### ISSUE THREAD

**Issue by jperchom** [SteamDeckHomebrew/decky-loader#260]
Some pluguins like Vibrant or CSSloader cannot be instaled. Can you help me? need more information?

**Comment by TrainDoctor** [comment]
> Some pluguins like Vibrant or CSSloader cannot be instaled. Can you help me? need more information?

Please refile this issue following the instructions of the new issue template. We need the logs and information that the new issue template requests in order to debug your issue. Thanks for your patience and understanding.
