### ISSUE TITLE
Decky loader not working

### ISSUE THREAD

**Issue by KrOOb-5** [SteamDeckHomebrew/decky-loader#261]
After installing the last update from steam deck, decky loader icon dissapeared and its not working. Im on Stable version.

**Comment by KrOOb-5** [comment]
After testing it on beta. It works fine

**Comment by ncanavan** [comment]
On beta here and after updating to the newest version decky disappeared from qam. Using prerelease, latest version.

**Comment by ncanavan** [comment]
And it's back after going to desktop and back. Not sure what happened.

**Comment by TrainDoctor** [comment]
@ncanavan @KrOOb-5 please give the latest stable release a try on Stable SteamOS and grab logs via ``cd ~ && journalctl -b0 -u plugin_loader.service``. We can't debug much without these logs. Thanks.

**Comment by NanotechMagus** [comment]
Hey, I'm having this issue on my SD as well

SteamOS Version: 3.3.2
Decky Channel: Release

Tried to install Decky Loader and it's not showing up in Steam.  Here's the logs
[decky_pluginloader_output.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/10050124/decky_pluginloader_output.txt)

**Comment by MisterSheeple** [comment]
I'm having the same problem. The logs seem to indicate a lot of connection refusal errors. I'm going to try installing Decky again, because I'm guessing this is something Valve changed in a new OS update

**Comment by TrainDoctor** [comment]
No one has been able to re-create the issue in our testing group. Closing this issue for now.
