### ISSUE TITLE
Decky didnt update a plugin, after restart it was installed

### ISSUE THREAD

**Issue by DarkSide1305** [SteamDeckHomebrew/decky-loader#262]
**Description**
Decky didnt update a plugin after trying multiple times, after a restart it was automatically installed

**To Reproduce**
Not sure, it just... happened randomly

**Expected behavior**
The plugin should update without having to restart or trying multiple times

**Logs**
[backendlog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/10050415/backendlog.txt)

**Additional context**
Have you modified the read-only filesystem at any point?  
No

And additional info is, that I was on 2.4.1 and it didnt happen just a few minutes ago on the same version with a different plugin, so it seems to not be consistent

**Comment by TrainDoctor** [comment]
This was more than likely an issue with the plugin itself, which in the past few months was discovered and the source of the issue fixed on the plugin's side and removed. Closing as stale.
