### ISSUE TITLE
Can't load proxy settings by using the given command to download and install decky-loader.

### ISSUE THREAD

**Issue by gylove1994** [SteamDeckHomebrew/decky-loader#263]
**Description**
Can't load proxy settings by using the given command to download decky-loader.

**To Reproduce**
1. Follow the readme to set up until using the given command download and install decky-loader.
2. Use the command download decky-loader.
3. Due to proxy settings not loading, download failure.

**Expected behavior**
the given command can load proxy settings to download and install the decky-loader.

**Additional context**
Have you modified the read-only filesystem at any point?  
Yes.

**Way to fix**
Add flag ``-E`` to ``exec sudo "$0" "$@"``in scripts to load the user's env can fix the problem. 

I will try to make a PR to fix it.

**Comment by TrainDoctor** [comment]
We have no plans to support proxies
