### ISSUE TITLE
Fantastic no longer working after updating to Decky Loader 2.4.5

### ISSUE THREAD

**Issue by v-flashpoint** [SteamDeckHomebrew/decky-loader#264]
Hi all,

I updated my Decky Loader last night to version 2.4.5, and ever since then the Fantastic plugin hasn't been able to control my fans. Instead I've been back to the standard (and mostly useless) Steam version that spins up crazily every few seconds.

I'm using v0.3.4 of Fantastic, and have tried reinstalling the plugin, restarting the Steam Deck, and rolling back to an earlier version of the plugin, but nothing's worked. 

Not sure if I've just ended up updating when I shouldn't have, as I noticed my Decky Loader was set to update on the prerelease branch rather than stable, but I wanted to let you guys know in the hope it's not just me!

I've attached a screenshot to show the issue.

**Screenshots**
![steamuserimages-a akamaihd](https://user-images.githubusercontent.com/99752646/203944646-59a4bcf8-0950-4776-89bb-eb5b9dde2348.jpg)

**To Reproduce**
1. Install the latest version of Fantastic (0.3.4) and Decky Loader (2.4.5)
2. Set fan speed to max at the lower end of the graph.
3. See the fan stay at 0 (or keep revving up then dropping back to zero seconds later in line with the existing useless Steam fan controller)

**Expected behavior**
The fan controller should be able to control the fans

**Version information**
 - SteamOS Version: 3.3.2 build 20221005.1
 - Selected Update Channel: Prerelease, but after the issue changed last night to stable.

**Logs**
Will try and fetch the logs tonight

**Additional context**
Have you modified the read-only filesystem at any point?  
Not to my knowledge, unless I had to do that to install this.

**Comment by TrainDoctor** [comment]
This issue more than likely lies with Fantastic and mot decky loader. please file an issue with the relevant GitHub page.
