### ISSUE TITLE
Is there a way to let decky go through proxy?

### ISSUE THREAD

**Issue by liuziangexit** [SteamDeckHomebrew/decky-loader#266]
My country baned raw.githubusercontent.com and many other similar binary distributing website, I think thats the reason why i can't install any plugin in decky. Is there a way to make it use proxy?

**Comment by liuziangexit** [comment]
Or maybe does anyone know how to make the whole steamos go through web proxy, that will be even better!
I tried to set http proxy in steamos play mode settings, but it only affact the steam process.

**Comment by AAGaming00** [comment]
We have no plans to support proxies. Setting a WireGuard VPN in desktop mode network settings should work.

**Comment by KrisCris** [comment]
For anyone interested, I made a fork that accepts proxy: https://github.com/KrisCris/decky-loader/actions/runs/9510781551

Replace `~/homebrew/services/PluginLoader`, fix the permission, add proxy settings in `~/homebrew/settings/loader.json`, e.g. `"proxy_url": "socks5://127.0.0.1:7890"`, then restart the service.

**Comment by TrainDoctor** [comment]
> For anyone interested, I made a fork that accepts proxy: https://github.com/KrisCris/decky-loader/actions/runs/9510781551
> 
> Replace `~/homebrew/services/PluginLoader`, fix the permission, add proxy settings in `~/homebrew/settings/loader.json`, e.g. `"proxy_url": "socks5://127.0.0.1:7890"`, then restart the service.

I'm not sure why you're forked and not contributed upstream. Proxies are highly insecure compared to other forms thus our lack of support.
