### ISSUE TITLE
[Feature Request] Plugin to automate adding text input to steam controller settings

### ISSUE THREAD

**Issue by Benjamin-Berger** [SteamDeckHomebrew/decky-loader#267]
Many games require you to log in with a password that does not get saved. In order to automate this process one has to build a binding that reads something like (assuming password is "Password123"

button press a: send p
additional button press a - fire delay 50ms: send a
additional button press a - fire delay 100ms: send s
additional button press a - fire delay 150ms: send s

and so on. Would be superb if there was a way to automate this such that I can just enter text and it would build the key bindings for me. Happy to build it myself if theres a discord where i can get help working with steam decks API

**Comment by PartyWumpus** [comment]
This isn't the right place to request plugins. The discord is listed in the readme, but [here's the link](https://discord.gg/ZU74G2NJzk)

**Comment by TrainDoctor** [comment]
> This isn't the right place to request plugins. The discord is listed in the readme, but [here's the link](https://discord.gg/ZU74G2NJzk)

Just for clarity, plugin requests aren't allowed in general.
