### ISSUE TITLE
Bug on the latest prerelease

### ISSUE THREAD

**Issue by GarnetSunset** [SteamDeckHomebrew/decky-loader#270]
**Description**
[A clear and concise description of what the bug is.]

**To Reproduce**
Reinstall the prerelease version

**Expected behavior**
Should load!

**Version information**
 - SteamOS Version: ``Linux steamdeck 5.13.0-valve21.3-1-neptune #1 SMP PREEMPT Mon, 03 Oct 2022 23:17:36 +0000 x86_64 GNU/Linux``
 - Selected Update Channel: Beta 

**Logs**
[backendlog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/10182282/backendlog.txt)

**Additional context**
Have you modified the read-only filesystem at any point?  
Yes, BTRFS

**Comment by TrainDoctor** [comment]
We're aware, this is a bug with the version of python used in decky uses a later version of glibc than the deck provides. We're working to establish what version of python we can use that uses glibc that the deck provides on stable.

**Comment by marios8543** [comment]
Fixed on latest pre-release https://github.com/SteamDeckHomebrew/decky-loader/releases/tag/v2.4.6-pre2
