### ISSUE TITLE
Decky last update bug

### ISSUE THREAD

**Issue by KrOOb-5** [SteamDeckHomebrew/decky-loader#271]
**Description**
[A clear and concise description of what the bug is.]

**To Reproduce**
I updated decky, and nothing happened.
I proceeded to restart stam deck, but the update was still stuck maybe if I restarted steam deck I could try update decky again.
Decky icon and plugins have disappeared from stems deck

**Expected behavior**
I should be able to start again the update of decky. 

**Version information**
 - I have the last Steam OS version in the stable setting
 
**Additional context**
Decky it's not appearing neither in stable or beta settings 

Have you modified the read-only filesystem at any point?  
[Yes or No.]
No

**Comment by realJustinLee** [comment]
https://github.com/SteamDeckHomebrew/decky-loader/issues/272 a quick fix for you.

**Comment by marios8543** [comment]
Fixed on latest pre-release https://github.com/SteamDeckHomebrew/decky-loader/releases/tag/v2.4.6-pre2
