### ISSUE TITLE
Decky not showing up in quick setting menu after updated to the latest pre release 

### ISSUE THREAD

**Issue by realJustinLee** [SteamDeckHomebrew/decky-loader#273]
**Description**
Decky not showing up in quick setting menu after updated to the latest pre release 

**To Reproduce**
1. Update to latest pre release
2. Go to gaming mode
2. Click on ‘…’
3. No Decky icon

**Expected behavior**
Decky icon visible 

**Version information**
 - SteamOS Version: ``5.13.0-valve35-1-neptune``
 - Selected Update Channel: Preview.

**Additional context**
Have you modified the read-only filesystem at any point?  
No

**Comment by TrainDoctor** [comment]
Please include the output of running ``cat ~/homebrew/services/.loader.version``.

Please run the install stable script and then switch over to pre-release to see if the issue re-occurs.

**Comment by realJustinLee** [comment]
> Please include the output of running `cat ~/homebrew/services/.loader.version`.
> 
> Please run the install stable script and then switch over to pre-release to see if the issue re-occurs.

@TrainDoctor 
Actually installing the [Prerelease v2.4.6-pre1](https://github.com/SteamDeckHomebrew/decky-loader/releases/tag/v2.4.6-pre1) would fix the problem.

Since I'm using the preview channel of steam os, I would say this might be the mismatched version of glibc which the latest pre-release fixed for the stable version.

I would propose this project include two separate versions for steamOS stable and steamOS preview, since in steamOS 3.4 and 3.3 their kernels are very different from each other.

**Comment by TrainDoctor** [comment]
Testing of 2.4.6-pre3 indicates this issue is now resolved from one angle, but we are aware of a new issue related to restarting the steam client causing decky to not re-inject, which is unrelated to this issue.
