### ISSUE TITLE
Feature Request: Two separate versions of the release for steamOS stable and steamOS preview

### ISSUE THREAD

**Issue by realJustinLee** [SteamDeckHomebrew/decky-loader#274]
I would propose this project include two separate versions of the release for steamOS stable and steamOS preview since in steamOS 3.4 and 3.3 their kernels are very different from each other.

And the implementation for the current version was quite easy (just revert [this](https://github.com/SteamDeckHomebrew/decky-loader/compare/v2.4.6-pre1...v2.4.6-pre2) would do for the latest steamOS preview).

**Comment by TrainDoctor** [comment]
> I would propose this project include two separate versions of the release for steamOS stable and steamOS preview since in steamOS 3.4 and 3.3 their kernels are very different from each other.
> 
> And the implementation for the current version was quite easy (just revert [this](https://github.com/SteamDeckHomebrew/decky-loader/compare/v2.4.6-pre1...v2.4.6-pre2) would do for the latest steamOS preview).

Maintaining two separate versions/releases of decky is not really viable for us.
