### ISSUE TITLE
Plugins dissapeared of Decky and not accesible

### ISSUE THREAD

**Issue by helliongame** [SteamDeckHomebrew/decky-loader#278]
**Description**

after update SteamOS , Decky only shows Powertools. The other plugins are not showed
**To Reproduce**
1. Open Decky with  [...]   key
2.Only shows Powertool
3. the other scrips like Vibrantdeck or CSS are working because the themes  and colored keyboard are applied, but it cant be reconfigured because decky dont show it
4. I tryed to reinstall Decky , delete the pluguin folder and reinstall all plugins , without result

**Version information**
 - SteamOS Version: 3.3.5 stable
 - Selected Update Channel: stable
 - Decky version: Stable

**Additional context**
Have you modified the read-only filesystem at any point?  
no

**Comment by TrainDoctor** [comment]
Please include the logs using ``cd ~ &&
journalctl -u plugin_loader.service > loaderlogs.txt``.
We cannot really help you without these logs.

**Comment by helliongame** [comment]
sorry but when i execute this command on console , it didnt show me anything ...

Greetings

**Comment by TrainDoctor** [comment]
Closing in favor of #279 as the overarching issue for the root issue.

**Comment by helliongame** [comment]
The 279 solution dont solve this issue. I restarted the Deck several times , and only appear powertools , the others pluggins dont appear and i cant configure them
