### ISSUE TITLE
Updating decky loader suddenly restarts the Steam Deck without warning

### ISSUE THREAD

**Issue by rhossack** [SteamDeckHomebrew/decky-loader#281]
**Description**
I was playing an emulator. I see a popup saying there's a decky loader update available. I go to update it. During the update, seemingly as part of the process, it restarts the Steam Deck. With absolutely no indication that that is going to happen.

**Version information**
 - SteamOS Version: 3.3.2, 20221005.1
 - Selected Update Channel: Stable

**Additional context**
Have you modified the read-only filesystem at any point?  
No

**Comment by rhossack** [comment]
This might be a feature request to put some sort of "warning: this will restart the steam deck. are you sure you want to update right now?" message.

But this is also a feature request to default the stable version of Decky Loader to the Stable release channel. I didn't notice that it was set to prerelease until after the update.

**Comment by TrainDoctor** [comment]
What version of decky loader were you updating from and to?
Also, Valve recently changed the functionality of the function we called from simply restarting the steam ui itself to restarting the steam client. We'll try to get a fix ready asap but I can't provide a timeline atm.

**Comment by TrainDoctor** [comment]
> This might be a feature request to put some sort of "warning: this will restart the steam deck. are you sure you want to update right now?" message.

We'll look into this time allowing.

> But this is also a feature request to default the stable version of Decky Loader to the Stable release channel. I didn't notice that it was set to prerelease until after the update.

This isn't really possible as the user decides what release pattern of decky they use via first install via the script and subsequently via the drop-down between Stable and Pre-Release.

**Comment by AAGaming00** [comment]
> What version of decky loader were you updating from and to?
> Also, Valve recently changed the functionality of the function we called from simply restarting the steam ui itself to restarting the steam client. We'll try to get a fix ready asap but I can't provide a timeline atm.

What happened here is that Valve broke our only way to restart the UI, making it crash, so we switched to restarting Steam until they fix it.

**Comment by rhossack** [comment]
> What version of decky loader were you updating from and to? Also, Valve recently changed the functionality of the function we called from simply restarting the steam ui itself to restarting the steam client. We'll try to get a fix ready asap but I can't provide a timeline atm.

Current stable to current prerelease.

> This isn't really possible as the user decides what release pattern of decky they use via first install via the script and subsequently via the drop-down between Stable and Pre-Release.

I followed the instructions to install the stable release. Got a pop-up saying pre6 was out, and didn't realize that it wasn't stable. Checked afterward and the update drop-down was on the prerelease channel, which doesn't make sense as a default setting for the stable version of the plugin.

> What happened here is that Valve broke our only way to restart the UI, making it crash, so we switched to restarting Steam until they fix it.

That's fine, but it's pure luck that I hadn't made much progress in the game I was playing when the deck suddenly restarted during the decky loader update. It really sucks when you restart automatically with no opportunity to stop and save first, and the nature of the mid-game pop-up implies that updating can be done silently in the background. When you update Steam OS, you're given a "restart" button, so if you have a game in the background you have plenty of opportunity to save your progress before you commit to the power cycle.

**Comment by TrainDoctor** [comment]
This has now been fixed in recent releases. Closing.

**Comment by 123ika** [comment]
Had it happen when updating to v2.8.2 , did not expect my deck to restart and thought something bad happened, I'm on stable update channel and stable system update channel

**Comment by TrainDoctor** [comment]
Decky only restarts the Steam Deck UI. Please include logs for the backend and frontend logs grabbed from the developer section of decky loader.
