### ISSUE TITLE
decky loader disappeared after steamos updated

### ISSUE THREAD

**Issue by BigHeadDog79** [SteamDeckHomebrew/decky-loader#283]
cant seem to get decky loader to show up when i pressed ... after i updated the steamos to the latest version. reboot, restart deck also the same.

**Comment by TrainDoctor** [comment]
> cant seem to get decky loader to show up when i pressed ... after i updated the steamos to the latest version. reboot, restart deck also the same.

Please follow the original issue template and include logs, steamos version and all the other info it requests, and post this info on #279, since this is a duplicate issue.
