### ISSUE TITLE
Decky Loader plugin tab can't fit very long names (mostly testing store related)

### ISSUE THREAD

**Issue by OuterWinnie** [SteamDeckHomebrew/decky-loader#285]
**Description**
If you have a plugin with a really long name installed, the plugin menu scrolls to the right and gets stuck there until you change to another tab (from Plugins to General per example).

**To Reproduce**

(You need to have installed plugins with a really long name, like SteamGrid from the testing store)
2. Go to the Decky Loader menu
3. Go to settings and then "plugins"

**Expected behavior**
Should display the names without needing to scroll i assume.

**Screenshots**

![20221217004041_1](https://user-images.githubusercontent.com/6392320/208209745-a91abfeb-6fbf-4fbe-9d46-3953fc33ae55.jpg)

**Version information**
 - SteamOS Version: 3.4 202221214.100
 - Selected Update Channel: Preview

**Comment by TrainDoctor** [comment]
With new uploads to the testing store, the CI now abbreviates the hash into 8 characters.
