### ISSUE TITLE
Decky plugins on testing store won't update

### ISSUE THREAD

**Issue by Pixxel123** [SteamDeckHomebrew/decky-loader#288]
**Description**
Decky pop up appears saying there are plugin updates available. as well as plugins having the dot indicator in the menu, but clicking on them to update does nothing. This is on Decky Pre-release. The plugins in question are Animation Changer and SteamGridDB.

**To Reproduce**
1. Open Decky settings, go to the plugin list.
2. Click on the download button for any plugin that has an update.
3. Nothing will happen, only the QAM is opened without the plugin being updated.
4. I have also tried restarting both the Steam Client and the Steam Deck itself to see if updates go through, and they do not.

**Expected behavior**
A pop up should appear indicating that the plugin is being downloaded and is updated.

**Version information**
 - SteamOS Version: `5.13.0-valve35-1-neptune #1 SMP PREEMPT Sat, 03 Dec 2022 01:08:00 +0000 x86_64 GNU/Linux`
 - Selected Update Channel: Preview

**Logs**
[backend.log](https://github.com/SteamDeckHomebrew/decky-loader/files/10253836/backend.log)

**Additional context**
Have you modified the read-only filesystem at any point?  
No

**Comment by TrainDoctor** [comment]
This issue has been fixed with a recent deployment to the testing store. Thanks for the report.
