### ISSUE TITLE
The implication of enabling 'CEF Remote Debugging'

### ISSUE THREAD

**Issue by zhzy0077** [SteamDeckHomebrew/decky-loader#289]
First off, it's really an amazing tool and thanks for making it happen!

I'm a bit confused of enabling 'CEF Remote Debugging' in the instruction. By searching it in the Internet, it seems to be something relating to browser debugging. 

My question is, as a user of decky loader, by _user_ I mean, installing plugins and using them, is it necessary for me to enable 'CEF Remote Debugging' in Developer menu?

**Comment by WerWolv** [comment]
It is necessary as Decky uses it to inject its code into Steam (which is basically just a browser).
You don't need to do anything else with it afterwards though, just enable it and leave it enabled and you're good.

**Comment by zhzy0077** [comment]
> It is necessary as Decky uses it to inject its code into Steam (which is basically just a browser). You don't need to do anything else with it afterwards though, just enable it and leave it enabled and you're good.

Thanks for the prompt response. Just wondering if it exposes the debugging interface to local network w/o authentication? I don't see a place to set bind address or password.

**Comment by PartyWumpus** [comment]
it does not. Normally it does, but decky disables that when it's installed. If you look in decky settings you can re-enable the CEF forwarding. There is no password, and the port used is 8080 (or possibly 8081?)

**Comment by jynbug** [comment]
Honestly I'm having trouble blocking this damn CEF remote debugging because my stoner roommate won't turn it off. Can you help me figure out how to block the nonstop 255 broadcast to every IP every second in my entire household

**Comment by TrainDoctor** [comment]
> Honestly I'm having trouble blocking this damn CEF remote debugging because my stoner roommate won't turn it off. Can you help me figure out how to block the nonstop 255 broadcast to every IP every second in my entire household

We now no longer enable CEF forwarding by default. So unless your roommate installed Decky and explicitly enabled CEF forwarding rather than just CEF Debugging after install then we can't really help you other than telling you to talk with them and hopefully they will listen. Not much we can do, sorry.
