### ISSUE TITLE
Decky - Animation Loader module - Browse Animations not working

### ISSUE THREAD

**Issue by tschudenizer** [SteamDeckHomebrew/decky-loader#290]
Hello there,
I tried the following with the stable release and the pre-release versions of Decky-Loader:
I installed the module Animation Changer and when I try to browse animations
and try to select a boot animation via A-button then the current screen goes out of focus (i.e. what is on the screen is difficult to read), nothing happens, when I push A-button again,
a difficult-to-read error message appears, I think it reads
"Something went wrong while displaying this content. Refresh"
and until the next restart the Steam content stays out of focus on all screens
except the Steam and Quick menus, they are displayed in focus.
What is going on there?
SteamOS is current and on the Preview Channel, Decky-Loader is Pre-Release 2.4.6-pre5 (I originially tried the Release version of Deck too, didn't work
either, uninstalled it) and then tried Pre-Release version of Decky-Loader,
Pre-Release 2.4.6-pre5, attempted uninstall via the uninstall-script several times.

Tried it both with the Deck connected via Steam Deck dock to an external display and without being connected to a dock / external display.
Is this a known problem and is there a way to fix this?

Kind regards,
          Tschudenizer
and

**Comment by TrainDoctor** [comment]
This is an issue that you should report to the developer directly, thanks for the report regardless
