### ISSUE TITLE
Unable to install "HLTB for Deck" v1.2.0

### ISSUE THREAD

**Issue by zhzy0077** [SteamDeckHomebrew/decky-loader#291]
**Description**
It fails to install without any prompt. https://github.com/hulkrelax/hltb-for-deck/issues/7

**To Reproduce**
1. Go to Store.
2. Click on "HLTB for Deck"
3. Click Install
4. Nothing happens

**Expected behavior**
The plugin is installed.

**Screenshots**
[If applicable, add screenshots to help explain your problem.]

**Version information**
 - SteamOS Version: 3.3
 - Selected Update Channel: Stable

**Logs**
```
Dec 20 14:19:40 steamdeck PluginLoader[11593]: [browser][INFO]: Installing HLTB for Deck (Version: 1.2.0)
Dec 20 14:19:40 steamdeck PluginLoader[11593]: [browser][CRITICAL]: Could not fetch from URL. {
Dec 20 14:19:40 steamdeck PluginLoader[11593]:   "code": "not_found",
Dec 20 14:19:40 steamdeck PluginLoader[11593]:   "message": "File with such name does not exist.",
Dec 20 14:19:40 steamdeck PluginLoader[11593]:   "status": 404
Dec 20 14:19:40 steamdeck PluginLoader[11593]: }
```

**Additional context**
Have you modified the read-only filesystem at any point?  
No.

**Investigation so far**
1. Plugin server, a.k.a., 'https://plugins.deckbrew.xyz/plugins' returns "HLTB for Deck" as below block:
```json
    {
        "id": 26,
        "name": "HLTB for Deck",
        "author": "hulkrelax",
        "description": "A plugin to show you game lengths according to How Long To Beat",
        "image_url": "https://cdn.tzatzikiweeb.moe/file/steam-deck-homebrew/artifact_images/HLTB%20for%20Deck.png",
        "tags": [
            "backlog",
            "how long to beat",
            "utility"
        ],
        "versions": [
            {
                "name": "1.2.0",
                "hash": "93ea240f6f287091c66602b2ba246bfba2c680e89893023ae88edde0488c405a"
            },
            {
                "name": "1.1.1",
                "hash": "fd11409afd13dd16e0568349c868a5765c78f3e47506e0217baf76b3057b968d"
            },
            {
                "name": "1.1.0",
                "hash": "2e3ee4ae7cb822ef05c75ff492c5492371b17cf40ccabc115020363676802c06"
            },
            {
                "name": "1.0.1",
                "hash": "dbc2954e45340b8b9015d54faa721250efc76207f0f97c76873548bf442a0149"
            },
            {
                "name": "1.0.0",
                "hash": "746e7540d077f64ef1b0a9168d3c95c03ce0d017aebc4ffd1be13f6d7d8132bd"
            }
        ]
    },
```
2. All versions except 1.2.0 can be downloaded via `https://cdn.tzatzikiweeb.moe/file/steam-deck-homebrew/versions/{hash}.zip`
3. `https://cdn.tzatzikiweeb.moe/file/steam-deck-homebrew/versions/93ea240f6f287091c66602b2ba246bfba2c680e89893023ae88edde0488c405a.zip` gives a 404. It reflects the 404 I see in log.

**Comment by nabel0** [comment]
I can confirm this on my side to..The installation in the "Default" Store for "HLTB for Deck" is not working.
The same thig happens for the latest "AutoFlatpaks 1.3.0" update also.
I'll guess those two uploads to the store are broken.

**Comment by shigutso** [comment]
Same issue here.
Reported on HLTB-for-deck github but looks like the issue is on Decky's side
https://github.com/hulkrelax/hltb-for-deck/issues/7

**Comment by TrainDoctor** [comment]
In future please file such issues on the plugin database repo. The HLTB plugin has been re-uploaded and now installs as expected from the main store. Thanks for the reports.
