### ISSUE TITLE
SteamDeck screen goes black but i can hear and navigate

### ISSUE THREAD

**Issue by JohnnyToon** [SteamDeckHomebrew/decky-loader#300]
**Description**
[When opening my steam deck the screen goes black after a few moments, i can still hear and navigate throught steam, i wanted  to delete the vibrant plugin because it wasnt doing anything when i was changing saturation amd gamma so i decided to unistall it but wasn't happening clicking upon uniatall nothing was happening so upon restarting my steam deck the colors when back to those ive choose and thats when the screen goes to black occured, im super new to pc and this kind of stuff so please helo and keep it simple cause im not good with all this techy stuff thats why im only responding with the description and not filling the rest cause i dont know that stuff.

**Comment by TrainDoctor** [comment]
We cannot help you without the logs and update channel information. Please complete the bug report as requested.
