### ISSUE TITLE
PluginLoader fails to connect to React DevTools

### ISSUE THREAD

**Issue by alecstuhr** [SteamDeckHomebrew/decky-loader#306]
**Description**
After enabling React DevTools in the Decky Developer options PluginLoader tries to connect to the DevTools instance on my PC but fails after 5 minutes with a timeout error

**To Reproduce**
1. Open Decky settings
2. Go to the Developer section
3. Enter the IP of the PC running DevTools and toggle the switch to enable DevTools
4. Wait for Decky to restart Steam
5. See 'Connecting to React DevTools at 192.168.0.11' in the PluginLoader logs and 5 minutes later 'Failed to connect to React DevTools'

**Expected behavior**
PluginLoader should connect to React DevTools

**Version information**
 - SteamOS Version: ``Linux steamdeck 5.13.0-valve21.3-1-neptune #1 SMP PREEMPT Mon, 03 Oct 2022 23:17:36 +0000 x86_64 GNU/Linux``
 - Selected Update Channel: Stable

**Logs**
[PluginLoader.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/10326705/PluginLoader.txt)

**Additional context**
Have you modified the read-only filesystem at any point?  
No

PluginLoader should be able to reach DevTools, I checked it by running ``curl 192.168.0.11:8097`` on the Deck

**Comment by AAGaming00** [comment]
Known issue. Should be fixed in latest main branch changes

**Comment by AAGaming00** [comment]
I've tested this locally and it seems to consistently work.
