### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by jefferio** [SteamDeckHomebrew/decky-loader#307]
Hi guys

I get this after following the installation guide

 curl -L https://github.com/SteamDeckHomebrew/... | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0sh: line 7: syntax error near unexpected token `newline'
sh: line 7: `<!DOCTYPE html>'
100 13041    0 13041    0     0  11844      0 --:--:--  0:00:01 --:--:-- 11855
curl: (23) Failure writing output to destination

What have I done wrong? Hopefully something simple!

**Comment by PartyWumpus** [comment]
try running `curl -L https://github.com/SteamDeckHomebrew/decky-loader/raw/main/dist/install_release.sh | sh` instead?

**Comment by jefferio** [comment]
> try running `curl -L https://github.com/SteamDeckHomebrew/decky-loader/raw/main/dist/install_release.sh | sh` instead?

God knows what I had copied and pasted! Thank you PartyWumpus, worked a charm 👍 :-)
