### ISSUE TITLE
Installation doesn’t look to have failed but doesn’t seem to have worked 

### ISSUE THREAD

**Issue by tblomega** [SteamDeckHomebrew/decky-loader#309]
I have had my SteamDeck sense july, been ‘aware’ of decky-loader sense shortly before due to YouTube but only now bothering to try and install it to check it out.

Steam OS version 3.4.4

I went to desktop mode and typed the install command given on this projects main page the curl -L stuff. After entering the password it looked to do things and no errors were given.

I returned to gaming mode however and nothing has changed, reboot, and still no change, return to desktop mode type the command again it does stuff again (I may have imagined seeing an extra bit naming decky-loader being downloaded that I didn’t recall seeing that exact line of text the first time) again however no errors. Gaming mode still has no extra option in the … menu and rebooting did not change that.

I am unsure how to begin troubleshooting this.

In case it matters I have the 512 version steamdeck but SteamOS only gets 150gigs of the with the remainder being partitioned separately as BTRFS as there is a decent windows driver for BTRFS and I have windows on a SD card partition (also about 150gig of 1TB, the other partition there is also BTRFS) so that steam in both SteamOS and windows can use the same installation files for whatever games

**Comment by vburlion** [comment]
Same issue here. Latest decky release on 3.4.4

**Comment by PartyWumpus** [comment]
First, please check the [common issues in the readme](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)

If none of those apply, please send a screenshot of your terminal output and a screenshot of the command you ran. (You can just run it again for these)

Then, please run ``cd ~ && journalctl -u plugin_loader.service > deckylogs.txt`` and upload the resulting file which can be found at ``/home/deck/``.

**Comment by vburlion** [comment]
`(deck@steamdeck ~)$ curl -L https://github.com/SteamDeckHomebrew/decky-loader/raw/main/dist/install_release.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2919  100  2919    0     0   2336      0  0:00:01  0:00:01 --:--:-- 24123
[sudo] password for deck: 
Installing Steam Deck Plugin Loader release...
Installing version v2.4.5...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 20.4M  100 20.4M    0     0  5613k      0  0:00:03  0:00:03 --:--:-- 9381k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   376  100   376    0     0   2799      0 --:--:-- --:--:-- --:--:--  2805
Grabbed latest release service.
Created symlink /etc/systemd/system/multi-user.target.wants/plugin_loader.service → /etc/systemd/system/plugin_loader.service.
(deck@steamdeck ~)$ 
`

[deckylogs.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/10333804/deckylogs.txt)

Thank you!

**Comment by tblomega** [comment]
I feel dumb… so I was inspired to install this based on a video where the guy was going over the things you could do with it and skimmed through the installation part. I came here to grab the correct url and other installation command parameters and only lightly skimmed the into around that command….

I utterly missed the developer mode and cef bits and that is totally on my. Upon properly reading the link partywampus provided regarding common issues and enabling developer mode and the cef thing the plugin menu was magically present.

now to find where I go to turn in my nerd card for being so dumb…

**Comment by TrainDoctor** [comment]
Happy you were able to "read the manual" and fix your issue. Closing this issue.
