### ISSUE TITLE
Steam Deck Beta breaks Decky Loader

### ISSUE THREAD

**Issue by ruineka** [SteamDeckHomebrew/decky-loader#314]
After rebooting Steam updated and now Decky Loader no longer works. Switching to stable for now since it's not broke on the Beta channel.

Steps to reproduce behavior:
1. Enable Steam Deck Beta
2. Notice after the update you no longer see Decky Loader menus
3. Returning to stable Decky Loader continues to work

SteamOS Version: 3.5 (20230104.1000)
Steam Version: 1672959434
Steam Client Build Date: Thu, Jan 5 1:24PM UTC -06:00

OS Update Channel: Main
Steam Client Update Channel: Steam Deck Beta

Journalctl log: 
[deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/10357100/deckylog.txt)

**Comment by realJustinLee** [comment]
Same here

**Comment by NGnius** [comment]
Update which caused this: https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/3653013849007354968

**Comment by TrainDoctor** [comment]
Can you please collect logs according to the bug report template? We can't do much with "it's broken".

**Comment by ruineka** [comment]
> Can you please collect logs according to the bug report template? We can't do much with "it's broken".

Apologizes, I was submitting the issue with my phone and was a bit caught up so getting the logs were impossible at the time. The ticket has been updated with included log and information.

**Comment by lvctr** [comment]
Exact same course of action that caused this for me.
`journalctl` logs: [deckylogs.txt](https://cdn.discordapp.com/attachments/960284126701813770/1060767128954880021/deckylogs.txt)
Hope this helps in any way.

**Comment by TrainDoctor** [comment]
Pre-release coming asap, please install the latest pre-release via loader or install script and provide info and logs if it did/did not work.

**Comment by ruineka** [comment]
> Pre-release coming asap, please install the latest pre-release via loader or install script and provide info and logs if it did/did not work.

Great news! Will do, thanks!

**Comment by ruineka** [comment]
The changes appears to have fixed the issue.

**Comment by TrainDoctor** [comment]
Testers
