### ISSUE TITLE
Suggestion: access plugin settings from decky settings, hide selected plugins from quick access

### ISSUE THREAD

**Issue by rlach** [SteamDeckHomebrew/decky-loader#317]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)

### Bug Report Description

Currently all installed plugins appear in quick access menu. Many of the plugins have one-time configuration, and then you can forget about them, or need to be adjusted rarely. For example steamgrid plugin only has social network links in its settings, and users very rarely have a reason to go into settings for non-steam game times. Emuchievents, once you log in, you don't have to setup anything ever again and so on.

By keeping everything in quick access it's very hard to quickly find plugins you want to quickly access, like bluetooth plugin. I'm aware of upcoming hand-sorting changes https://github.com/SteamDeckHomebrew/decky-loader/pull/277 which will allow users to have important plugins on top, but it still will end up with huge clutter in quick access, making it less user friendly.

### Expected Behaviour

In Decky Settings -> Plugins on the list, next to each plugin, there should be two new buttons:
* cogwheel-icon - enters settings for the plugin, the same menu as currently in quick access settings. 
* eye-icon/crossed-eye icon - toggles visibility of the plugin in quick access menu.

Alternatively plugin settings could be under '...' button, but I think visibility icon should be always visible, to quickly tell which plugins are hidden.

### SteamOS version

SteamOS 3.4.4 stable

### Selected Update Channel

Stable

### Have you modified the read-only filesystem at any point?

No

**Comment by TrainDoctor** [comment]
I don't think we will go with this solution but we've definitely want to do plugin re-ordering and it's been unofficially in development for a while and I have time to get that on the fast track soon™. Hopefully sorting will fill your needs. Thanks for submitting a feature request regardless.

**Comment by PartyWumpus** [comment]
I think this (or a similar feature) could be good. Some plugins really are just one time (or no time) setups, like vibrantdeck or steamgriddb. There's little need to display these if the user doesn't want to see them, so adding a (clear) way of hiding them would be nice. Being able to still access them while hidden would also be very convenient, but not necessary.

**Comment by TrainDoctor** [comment]
Definitely a good point, this will stay a "help wanted" issue so anyone willing and able to contribute such a feature will be free to do so, but I have no plans to coordinate the team to work on this issue ourselves at the moment.

**Comment by JohnnyCrazy** [comment]
This should be live for quite some time now
