### ISSUE TITLE
[BUG] Newest release was titled 'Prelease'

### ISSUE THREAD

**Issue by PartyWumpus** [SteamDeckHomebrew/decky-loader#319]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)

### Bug Report Description

Release 2.4.8 was named Prerelease 2.4.8 for some reason.

### Expected Behaviour

The version should automatically be named 'Release 2.4.8' instead.

### SteamOS version

EndevourOS :)

### Selected Update Channel

Stable

**Comment by PartyWumpus** [comment]
Issue is possibly a little weirder than that (although this is possibly seperate).
The releases went 2.4.**6**-pre5, then 2.4.**7**-pre1 and then 2.4.**8**
Not sure why it would jump version number? (also, last release was 2.4.5)

To be fair, the version numbers don't really matter as long as they go up...

**Comment by TrainDoctor** [comment]
> Issue is possibly a little weirder than that (although this is possibly seperate). The releases went 2.4.**6**-pre5, then 2.4.**7**-pre1 and then 2.4.**8** Not sure why it would jump version number? (also, last release was 2.4.5)
> 
> To be fair, the version numbers don't really matter as long as they go up...

The jump in version number was intentional and can be done through CI.

**Comment by TrainDoctor** [comment]
Fixed ages ago. Forgot to mark as completed.
