### ISSUE TITLE
[BUG] 'xml' Python module not able to be used from plugin backend

### ISSUE THREAD

**Issue by isiah-lloyd** [SteamDeckHomebrew/decky-loader#322]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)

### Bug Report Description

When trying to use the standard xml library from `main.py` a ModuleNotFoundError is raised. This seems like a bug to me as other python standard modules import fine. 

How to reproduce: 
In main.py:
`import xml.etree.ElementTree`
or 
`import xml.dom`

(Interestingly, `from xml.sax.saxutils import quoteattr as quote_xml_attr` works?)

### Expected Behaviour

xml module is able to be imported and used

### SteamOS version

3.4.4

### Selected Update Channel

Stable

**Comment by TrainDoctor** [comment]
For now solution provided by bug author is to bundle module with plugin.

**Comment by Xriuk** [comment]
For anyone else coming acrosss this. You can use external modules/libraries like xmltodict by including them in the py_modules folder
