### ISSUE TITLE
[Request] Use Fuzzy Checking for Steam Tab for Injection w/ URL verification

### ISSUE THREAD

**Issue by TrainDoctor** [SteamDeckHomebrew/decky-loader#323]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

Basically, current code does not search for the new steam tab and in place of that code we should do a fuzzy search for "Steam" in the "tab" name and if found, verify the URL matches a pattern (steamloopbackhost) and then inject from there. If a tab is not found with steam in the title we then search for the URL pattern through all tabs.

**Comment by leeoniya** [comment]
some fuzzy search comparisons: https://github.com/leeoniya/uFuzzy#a-biased-appraisal-of-similar-work
