### ISSUE TITLE
Delete/reset all per-game settings

### ISSUE THREAD

**Issue by nex86** [SteamDeckHomebrew/decky-loader#331]
### Please confirm

- [ ] I have searched existing issues
- [ ] This issue is not a duplicate of an existing one
- [ ] This is not a request for a plugin

### Feature Request Description

I need to remove or reset all per-game settings because I decided to use one global setting that works for me.
How does one do it the easy way?
I heard something about messing with debugging in localstorage but didn’t understand how to…
Yes I did try reinstalling the plugin. This didn’t get rid of the settings 

Ps: talking about VibrantDeck

**Comment by TrainDoctor** [comment]
This is not the place to report such an issue. Please seek the vibrant deck repository.
