### ISSUE TITLE
[BUG] Plugins disappeared after updating until reboot

### ISSUE THREAD

**Issue by KrisCris** [SteamDeckHomebrew/decky-loader#332]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)

### Bug Report Description

After plugin updates, some of them disappeared from the installed list and the quick access panel, not even showing up after reinstalling, until I rebooted the system.

I can't recall which of them were missing, but IIRC the audio loader is definitely one of them.

### Expected Behaviour

All the plugins should show up.

### SteamOS version

3.4.4

### Selected Update Channel

Prerelease

### Have you modified the read-only filesystem at any point?

NO

### Logs

[deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/10378540/deckylog.txt)

**Comment by TrainDoctor** [comment]
Please try to replicate the issue and try to determine what plugins are being not loaded, this will help us to narrow down the issue.

**Comment by KrisCris** [comment]
Is there a way to downgrade a plugin? Otherwise, it might be tricky to reproduce the issue until some plugins release updates...

**Comment by TrainDoctor** [comment]
> Is there a way to downgrade a plugin? Otherwise, it might be tricky to reproduce the issue until some plugins release updates...

Copied from my tag to you on discord.
![image](https://user-images.githubusercontent.com/11465594/211457924-7ade27e3-bc72-4204-aa29-176643c18290.png)

**Comment by KrisCris** [comment]
So, I downgraded the following plugins:
1. VibrantDeck,
2. Audio Loader,
3. Memory Deck,
4. MoonDeck

and upgraded them in the same order, and all of them disappeared.

**Comment by TrainDoctor** [comment]
> So, I downgraded the following plugins:
>
> ...
> 
> then upgraded them in the same order, and all of them disappeared.

``journalctl -b0 -u plugin_loader.service > log.txt`` to grab the logs from when you downgraded and upgraded please.

**Comment by KrisCris** [comment]
[deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/10378857/deckylog.txt)

The log is a bit messy, I initially downgraded plugins without uninstalling them and upgraded, but failed to reproduce the issue. So I uninstalled them, installed older versions, then upgraded them, and the issue appeared.

**However, when I tried to reproduce it again (since I want to get a clean dump of the log), tried a couple of times but couldn't reproduce it anymore :/**

**Comment by Equilibri0** [comment]
same issue, updating to a new steamOS beta and updated the deckyloader, it dissapears.

**Comment by TrainDoctor** [comment]
> same issue, updating to a new steamOS beta and updated the deckyloader, it disappears.

Please provide logs. This information ia useless without logs.

**Comment by TrainDoctor** [comment]
> Not really. 'Not Found' in the PluginLoader file was rather helpful (suggestive of a network-related issue during an update, my guess, with contents overwritten with garbage.) Perhaps your Decky Loader should use a two-stage loader. Perhaps a first-stage loader that heals a second-stage 'actual software' of Decky Loader.

If you'd like to see a feature added to decky loader, you're always welcome to submit a pull request. Thanks.

**Comment by geeksville** [comment]
i think this actually might be a dup of #390 (I didn't find this one originally when I was looking)

**Comment by TrainDoctor** [comment]
This has been fixed since #391 was merged. Please let us know if this fix did not work for you.
