### ISSUE TITLE
[BUG] Release Notes selection highlight remain on screen during Touch Scroll Behaviour (v2.4.8)

### ISSUE THREAD

**Issue by eastrd** [SteamDeckHomebrew/decky-loader#334]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)

### Bug Report Description

The selection border outline on the Release Notes section will remain on the screen if there’s a touch scroll behaviour after that.

This can be replicated by either:
- Touch screen click into the Release Notes, then back to the loader menu, then touch screen scroll down
- OR, use dpads/joystick to highlight the Release Notes, then use touch screen to scroll down

### Expected Behaviour

The selection highlight should stay with the Release Notes section 

### SteamOS version

SteamOS 3.4.4 Beta

### Selected Update Channel

Stable

### Have you modified the read-only filesystem at any point?

No

### Logs
[deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/10388429/deckylog.txt)

**Comment by AAGaming00** [comment]
This is a bug in valve's focus handling logic that we are using and not something we can/should fix.
