### ISSUE TITLE
[Request] Option to go to GitHub of plugins 

### ISSUE THREAD

**Issue by Rich246** [SteamDeckHomebrew/decky-loader#335]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

I was wondering if it's possible to add a "GitHub" option when looking at plugins (where they can be uninstalled and reloaded)

**Comment by PartyWumpus** [comment]
duplicate of #294, please read that
