### ISSUE TITLE
[BUG] When pressing "Restart Steam" in Gaming Mode, Decky Loader Resets Profiles set by user

### ISSUE THREAD

**Issue by moraroy** [SteamDeckHomebrew/decky-loader#337]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)

### Bug Report Description

If i were to use Boilr for example and simply need to restart Steam in Gaming Mode doing so results in all profiles for non steam games as well as steam games to be reset.

### Expected Behaviour

It should just reset steam without messing with any settings. Resetting Steam in Desktop Mode works like it should. But in Gaming Mode it resets. Is this a Decky Loader Problem? Im thinking maybe the "Restart Steam" code needs to be looked at.

### SteamOS version

Steam OS 3.4.3

### Selected Update Channel

Stable

**Comment by TrainDoctor** [comment]
You have provided no logs and are asking if this is a bug related to decky. BoilR has no association with decky and nothing Decky itself does should effect any other aspect of the Steam game mode UI. Please also update to the latest update and report the bug to the developer of BoilR and establish a list of plugins you're using that could effect Non-Steam games.
