### ISSUE TITLE
[BUG] CCS Loader

### ISSUE THREAD

**Issue by maddogspeighty** [SteamDeckHomebrew/decky-loader#344]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)

### Bug Report Description

My deck updated to the latest preview channel, I've updated to the latest pre release and CSS Loader is no longer working.

The plugin shows but all themes were disabled, enabling them does nothing.

### Expected Behaviour

Themes should show when enabled.

### SteamOS version

SteamOS 3.4.5

### Selected Update Channel

Prerelease

### Have you modified the read-only filesystem at any point?

No.

**Comment by AAGaming00** [comment]
This is not a decky-loader issue, please report this in the CSS Loader repo.
