### ISSUE TITLE
[Request] Persistent Updater

### ISSUE THREAD

**Issue by Jademalo** [SteamDeckHomebrew/decky-loader#355]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

There should be an optional service that will check on boot to see if Decky is correctly installed, and if not reinstall the current version of either release or development.

### Further Description

When running on the Steam client beta branch, every time there is an update I need to manually reinstall Decky. While I assume this is an issue running on the regular branch as well, it's a much bigger problem on the beta branch since updates are so frequent.

At present I have a shortcut on the desktop to do this, but that's obviously inconvenient since it requires going into desktop mode, clicking, manually typing in the password, and then going back to the main deck interface basically every time I use my deck since updates are so frequent.

Would it be possible to implement some sort of service that checks on boot to see if Decky is correctly installed and functional, and if not reinstall it automatically?

Thanks!

**Comment by AAGaming00** [comment]
This only happens on stable if you aren't keeping decky up to date, we are usually far ahead of stable with fixes

Beta doesn't break very often but more often than stable, and we usually fix it quickly

Possibly we could include a button combination to force update decky on startup.

**Comment by Jademalo** [comment]
It tends not to break in terms of bugs etc, the issue I'm finding is that it just disappears from the quick menu until I do a reinstall after every beta update. I've never yet had it persist through an update.

**Comment by AAGaming00** [comment]
> It tends not to break in terms of bugs etc, the issue I'm finding is that it just disappears from the quick menu until I do a reinstall after every beta update. I've never yet had it persist through an update, but reinstalling gets it working again every time.

Perhaps the remote debugging toggle in steam is disabling itself?

**Comment by Jademalo** [comment]
I don't believe so, I don't have to reenable it when reinstalling Decky.

**Comment by BenStein1** [comment]
Same here. Not broken, but plugin menu is missing after every OS update on Beta where I have to reinstall/update Decky from desktop to get it back. I wish there was an automatic way it would maintain that, perhaps similar to the way SteamOS-btrfs does it?

**Comment by TrainDoctor** [comment]
@Jademalo @BenStein1 Please understand that valve breaks decky in such a way that "checking if decky is installed correctly" is not a viable strategy. Valve changes the name of where the JS is executed frequently, this and other related issues is why Decky disappears from the QAM. This cannot be remedied short of Valve no longer renaming the tab where JS is executed constantly. Closing as a "can'tfix" rather than a wontfix.

**Comment by Jademalo** [comment]
Damn, that's a shame to hear, thanks.
