### ISSUE TITLE
[BUG] Decky Loader & Plug-ins Lag/Running Issues?

### ISSUE THREAD

**Issue by Reaper2099** [SteamDeckHomebrew/decky-loader#358]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)

### Bug Report Description

Since Ive downloaded Decky. Decky and any plug-ins I download will either take forever to load/download, or it just wont work at all. It’ll keep trying to find but never load. Ive tried to uninstall and reinstall. Tried reloading plug-ins. Also tried to reset the Steam Deck and redownload Decky. Ive always chosen the stable version. Any assistance would be appreciated… 
PS. I installed Decky on my cousins Steam Deck and his works just fine 😂

### Expected Behaviour

Just want it to load and work for me.

### SteamOS version

3.4.4

### Selected Update Channel

Stable

**Comment by AAGaming00** [comment]
Are you able to access https://cdn.tzatzikiweeb.moe from your Steam Deck?

**Comment by geeksville** [comment]
also possibly a dup of #390?  If he tried installing decky then some plugins but didn't reboot before trying the plugins I could see this happening.

**Comment by TrainDoctor** [comment]
Can you please provide a list of the plugins you are utilizing when you encounter this issue?

**Comment by TrainDoctor** [comment]
Not enough information has been provided to debug this issue. Closing as not planned.
