### ISSUE TITLE
[Request] Sort Installed Plugins

### ISSUE THREAD

**Issue by KingIzzymon** [SteamDeckHomebrew/decky-loader#369]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

Add sort options:

- Favorites
- Alphabetical (Ascending/Descending)
- Date installed (Oldest/Newest)
- Latest updated

### Further Description

With the Decky Loader Library growing so much, this would expediate accessing a desired plugin

**Comment by KingIzzymon** [comment]
Historical Discussion:
- https://github.com/SteamDeckHomebrew/decky-loader/discussions/175
- https://github.com/SteamDeckHomebrew/decky-loader/issues/182

**Comment by PartyWumpus** [comment]
you appear to have missed pull #277 where they say this has been closed in favour of a decky frontend lib.
[This is the change mentioned](https://github.com/SteamDeckHomebrew/decky-frontend-lib/pull/57) which is close to being merged.

**Comment by KingIzzymon** [comment]
@PartyWumpus Thanks I did miss that. I'll close this.

**Comment by ttang4299** [comment]
I'd like this reopened, as it'd be nice to have all the plugins automatically sorted alphabetically instead of having to manually sort them. @PartyWumpus
