### ISSUE TITLE
Decky Loader Store & Settings Page Are Blank w/ 2/17 Beta Update

### ISSUE THREAD

**Issue by wonderwallwoody** [SteamDeckHomebrew/decky-loader#371]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)

### Bug Report Description

With the new release to the Beta branch, the Decky Loader store & settings pages just show a blank page. The right nav off the QAM still seems to work ok.

### Expected Behaviour

The store & settings pages should appear 

### SteamOS version

SteamOS 3.4.4 Beta

### Selected Update Channel

Prerelease

### Have you modified the read-only filesystem at any point?

No

### Logs

[deckylogs.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/10771949/deckylogs.txt)

**Comment by cpuks** [comment]
Same here - cannot access settings & store + few addons like HLTB or Animation Changer throw error that can't be loaded.

**Comment by Jerome99** [comment]
Same here. V2.5.4-pre1 fixes store access and the settings page but a few plugins are non-functional right now. 

![16766952146235963140434966425082](https://user-images.githubusercontent.com/320409/219834572-1b4e3ed3-c3a8-49e7-a0f3-ffaa443c1b39.jpg)

**Comment by TrainDoctor** [comment]
> Same here. V2.5.4-pre1 fixes store access and the settings page but a few plugins are non-functional right now.
> 
> ![16766952146235963140434966425082](https://user-images.githubusercontent.com/320409/219834572-1b4e3ed3-c3a8-49e7-a0f3-ffaa443c1b39.jpg)



> Same here. V2.5.4-pre1 fixes store access and the settings page but a few plugins are non-functional right now.
> 
> ![16766952146235963140434966425082](https://user-images.githubusercontent.com/320409/219834572-1b4e3ed3-c3a8-49e7-a0f3-ffaa443c1b39.jpg)

Please see the releases page, but tldr:

```
...
Unfortunately, there is a more extensive issue with plugins that navigate to external web pages which we cannot fix via a Decky Loader update. We're currently investigating this issue and aiming to fix it, but those plugins will need to be updated individually. Thanks for your patience.

If you'd like to see a plugin you use on get it's updates to everyone faster so everyone can enjoy it, consider testing that plugin! Just follow this link to find out how: https://deckbrew.xyz/testing#decky-plugins
```

**Comment by TrainDoctor** [comment]
Fix is live for Decky Loader. I'll leave this issue open until the fixes for NavigateToExternalWeb and Modals are fixed and upstreamed into DFL as it will be at that point that those issues are not at the feet of plugin developers to fix. Thanks for reporting these issues and providing logs everyone!

**Comment by TrainDoctor** [comment]
It seems outside of vibrant deck, a good majority of plugins have gotten updates out to resolve the mentioned issues. If you want to view what plugins have been updated, click [here](https://github.com/SteamDeckHomebrew/decky-plugin-database/pulls?q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc+label%3Aplugin-update+reason%3Acompleted+closed%3A%3E2023-02-16). I'm closing this issue as resolved for now. If any plugins continue to have issues please report them to the relevant developer. Thanks.
