### ISSUE TITLE
SteamOS - Main Branch - "TypeError: Cannot read property 'bind' of undefined"

### ISSUE THREAD

**Issue by rawdatafeel** [SteamDeckHomebrew/decky-loader#379]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)

### Bug Report Description

On boot, several plugins flash "TypeError: Cannot read property 'bind' of undefined". Affected plugins do not work at all. Their respective buttons in the QAM pop up a large "TypeError" page. 

Attached CEF and Decky Loader logs

**Installed Plugins**

* CSS Loader
* DeckFAQs
* Pause Games
* ProtonDB Badges
* Bluetooth
* Power Tools
* Audio Loader
* VibrantDeck
* MetaDeck
* PDFDeck
* HLTB For Deck
* SteamGridDB
* Volume Mixer

**Affected Plugins**

* DeckFAQs
* ProtonDB Badges
* Bluetooth
* vibrantDeck
* PDFDeck
* HLTB for Deck
* Volume Mixer

### Expected Behaviour

* Looks like something's changed in SteamOS main with how plugins work, no idea what, doesn't seem to affect all plugins, list in above section, 

### SteamOS version

SteamOS Main 3.5, 20230213.1000, 6.1.9-Valve2-1-Neptune-61

### Selected Update Channel

Prerelease

### Have you modified the read-only filesystem at any point?

No

### Logs

[20230213-SteamOS-Main-CEFLog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/10809538/20230213-SteamOS-Main-CEFLog.txt)
[deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/10809539/deckylog.txt)

**Comment by PunkyBust** [comment]
Hello,

Same for the plugin (Save Manager)
![20230226_193538](https://user-images.githubusercontent.com/63625157/221430574-60afac9e-8f2b-4027-90bc-808cc8b5ae5e.jpg)

SteamOS (stable) : 3.4.4
Decky Loader (stable) : 2.6.1

Error appear today, without any action on my side (particular config or file modifications)

Regards.

**Comment by TrainDoctor** [comment]
@rawdatafeel This is a part of the issue described in #380. Plugins will need to update their DFL versions.
@PunkyBust I would report this issue to the plugin developer on their repository because this does not align with any other issues related to this issue/#380. Thanks.

**Comment by PunkyBust** [comment]
> @rawdatafeel This is a part of the issue described in #380. Plugins will need to update their DFL versions. @PunkyBust I would report this issue to the plugin developer on their repository because this does not align with any other issues related to this issue/#380. Thanks.

Ok thanks :)

**Comment by TrainDoctor** [comment]
This has been fixed for weeks, but was left open since plugins were breaking. Plugins have been given ample time to update. Closing.
