### ISSUE TITLE
[BUG] uninstalling a plugin does not delete that plugin's data directory (I'm happy to send in a PR)

### ISSUE THREAD

**Issue by geeksville** [SteamDeckHomebrew/decky-loader#382]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)

### Bug Report Description

While testing my plugin ( https://github.com/geeksville/steamback ).  I noticed that if you uninstall a plugin from the decky UI, it doesn't delete the plugin's data (and log) directory.  In the case of my plugin that directory could be kinda sizable.

Is this intentional?  If not, let me know and I'll send in a PR to change backend/utilities.py to delete the plugin's data/log directories.

### Expected Behaviour

see above

### SteamOS version

3.4.4 stable

### Selected Update Channel

Prerelease

### Logs

not applicable

**Comment by TrainDoctor** [comment]
This is intended behavior.
