### ISSUE TITLE
Link to pre-release wiki page does not work

### ISSUE THREAD

**Issue by mdeguzis** [SteamDeckHomebrew/decky-loader#384]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

See readme, the link there, https://deckbrew.xyz/en/loader-dev/development does not work.

### Expected Behaviour

Link should work

### SteamOS version

N/A

### Selected Update Channel

Stable

### Have you modified the read-only filesystem at any point?

No

### Logs

n/a

**Comment by TrainDoctor** [comment]
Fixed, thanks.
