### ISSUE TITLE
[BUG] Decky Shows Pre-Release Patch Notes when Stable Branch is Selected

### ISSUE THREAD

**Issue by TrainDoctor** [SteamDeckHomebrew/decky-loader#393]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)

### Bug Report Description

As reported by @beebls. Filing the issue so it can be assigned and task assigned.

### Expected Behaviour

Should only show pre-release notes (+ release notes if most recent release is newer than most recent pre-release) when pre-release is the selected branch and show stable release notes only for those on the stable Decky version.

**Comment by beebls** [comment]
Thanks for making this, completely forgot I even reported the issue

**Comment by PartyWumpus** [comment]
I think this was fixed by #429?
