### ISSUE TITLE
[BUG] Decky Loader stopped working after latest preview update

### ISSUE THREAD

**Issue by L0WR1D3Rz** [SteamDeckHomebrew/decky-loader#396]
### Please confirm

- [x] I have searched existing issues
- [x] This issue is not a duplicate of an existing one
- [x] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [x] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

Hi as per the title, deckyloader doesn't work anymore. It doens't load at all. I'm on latest preview firmware on steam deck, and  I am using the latest pre-release version of decky (tried reinstalling it today via desktop mode but it still won't work)

### Expected Behaviour

I guess it should be loading when you start the console,

### SteamOS version

SteamOS 3.4.6 (Preview channel)

### Selected Update Channel

Prerelease

### Have you modified the read-only filesystem at any point?

No

### Logs

[deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/10941194/deckylog.txt)

**Comment by Aulos** [comment]
I have a similar problem on beta channel - the plugin icon is just not showing up.

**Comment by phush0** [comment]
same on beta

**Comment by TrainDoctor** [comment]
There is a fix out on stable.

**Comment by TrainDoctor** [comment]
A pre-release has been released since the installer needs a fix to download the latest stable release when that release is newer than the latest pre-release.
