### ISSUE TITLE
[Request] Not working on Linux desktop

### ISSUE THREAD

**Issue by kepiz** [SteamDeckHomebrew/decky-loader#398]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

Is this working on Linux desktop?
Since there is no button with three points. I can't really open up the menu

**Comment by Fisch03** [comment]
If you are using a Controller, the button combination ist Steam/PS/Guide Button + A. Im pretty sure there is a way to do it on keyboard too but i don't remember how...

**Comment by PartyWumpus** [comment]
ctrl + 2 used to work on keyboard

**Comment by TrainDoctor** [comment]
I think this is also technically a duplicate of #368.

**Comment by PartyWumpus** [comment]
anyway, it works fine on linux desktop
![image](https://user-images.githubusercontent.com/48649272/225987711-bc3b8b0b-90c5-45ca-8205-6c56180b078a.png)

**Comment by kepiz** [comment]
Thank you for the info, I now know how to show up the menu on the right. I installed it but didn't show up. Using kubuntu

**Comment by kepiz** [comment]
[deckylogs.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/11004788/deckylogs.txt)
here you go, so as I understand if I install steam os on my desktop decky loader should work better

**Comment by PartyWumpus** [comment]
I wouldn't install SteamOS on your desktop.
 
It looks like the PluginLoader file isn't in `~/homebrew/services`? Could you try re-running the installer

**Comment by kepiz** [comment]
Thanks I did re run it twice the installer with the .desktop file straight
from the download folder.

**Comment by PartyWumpus** [comment]
Not certain why the installer isn't working, but as it seems the issue is `~/homebrew/services/PluginLoader` not existing, you _should_ just be able to just grab the [most recent PluginLoader release](https://github.com/SteamDeckHomebrew/decky-loader/releases) from the github and put it there. You'll need to `chmod +x` it or set it to executable in some other way. (By default it's owned by root, so I'd probably make it owned by root too)

Sorry for the delay.

**Comment by kepiz** [comment]
Thank you for the extended explanation, I will check it out later and report back

**Comment by kepiz** [comment]
did everything you said , and reinstalled and getting this installation error:
![image](https://user-images.githubusercontent.com/18174709/226140401-28655635-82bc-41e3-b320-2374eafa88fe.png)
also tried to paste that file and start steam, but decky loader wont show up, I find it really strange that it doesnt find the file, if I left it there

**Comment by TrainDoctor** [comment]
> did everything you said , and reinstalled and getting this installation error: ![image](https://user-images.githubusercontent.com/18174709/226140401-28655635-82bc-41e3-b320-2374eafa88fe.png) also tried to paste that file and start steam, but decky loader wont show up, I find it really strange that it doesnt find the file, if I left it there

You need to install jq.

**Comment by PartyWumpus** [comment]
i'll add a check to the .desktop file to see if `jq` exists, can't believe i forgot about this :facepalm:
