### ISSUE TITLE
Decky loader not install error

### ISSUE THREAD

**Issue by marcelobra1** [SteamDeckHomebrew/decky-loader#401]
### Please confirm

- [x] I have searched existing issues
- [x] This issue is not a duplicate of an existing one
- [x] This is not a request for a plugin

### Feature Request Description

Hello, all right, I'm trying to install the decky loader in the stable version of SteamOS (3.4.6) and when running the decky loader in desktop mode, this error appears and it doesn't install at all

Symbolic link created /etc/systemd/system/multi-user.target.wants/plugin_loader.service → /etc/systemd/system/plugin_loader.service.
chown: cannot access '/home/deck/homebrew/services/*': No such file or directory

How can I solve.. thanks

**Comment by TrainDoctor** [comment]
Please resubmit this as a bug report, and include logs.
