### ISSUE TITLE
[BUG] SSL Certificate is expired

### ISSUE THREAD

**Issue by SpartyInDetroit** [SteamDeckHomebrew/decky-loader#402]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [ ] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

The SSL cert is expired for the download link (for both the Download button and the curl method). This causes a browser warning to appear or curl to throw an exception.

### Expected Behaviour

Download should work without issues.

### SteamOS version

SteamOS 3.4.6

### Selected Update Channel

Stable

### Logs

curl -L https://github.com/SteamDeckHomebrew/decky-installer/releases/latest/download/install_relesae.sh | sh
curl: (60) SSL certificate problem: certificate is expired
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not establish a secure connection to it. To learn more about this situation and how to fix it, please visit the web page mentioned above.

**Comment by PartyWumpus** [comment]
This appears to have been an issue on github's side, but also seems to now be fixed.
