### ISSUE TITLE
[BUG] Elden Ring Doesnt launch with decky loader installed

### ISSUE THREAD

**Issue by xt234** [SteamDeckHomebrew/decky-loader#406]
### Please confirm

- [x] I have searched existing issues
- [x] This issue is not a duplicate of an existing one
- [x] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [x] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

Decky Loader

Launch Elden Ring with decky loader installed.
Game Crashes with it installed.

### Expected Behaviour

Game Should Launch But just goes back to the steam deck menu.
I have to uninstall decky loader each time i want to play Elden Ring. This is on Version 1.09 for Elden Ring.

### SteamOS version

SteamOs 3.4.6 Stable

### Selected Update Channel

Stable

### Logs

I Curently dont have my deck at the moment so i cant provide the text file.

**Comment by TrainDoctor** [comment]
Please include logs and recordings of this issue. I highly doubt anything Decky is doing is causing elden ring not to launch. Also please consider changing what version Proton you are running Elden Ring with.

**Comment by xt234** [comment]
it seems like it was an older ish version of power tools that made it not crash tho its working with the recent one.
