### ISSUE TITLE
[BUG] Decky loader fails to install

### ISSUE THREAD

**Issue by johndwalker** [SteamDeckHomebrew/decky-loader#407]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

When I try to install Decky Loader, it fails to start the plugin_loader.service. I have followed the instructions for both the .desktop download as well as the Konsole method. I have tried both stable and prerelease. See the 'logs' section for the installer output.

### Expected Behaviour

It should install successfully.

### SteamOS version

SteamOS 3.4.6 Stable

### Selected Update Channel

Stable

### Logs

[deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/11083490/deckylog.txt)

Here is the install output:

deck@steamdeck ~)$ sudo curl -L https://github.com/SteamDeckHomebrew/decky-installer/releases/latest/download/install_release.sh | sh
[sudo] password for deck: 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  3413  100  3413    0     0   3611      0 --:--:-- --:--:-- --:--:--  3611
Installing Steam Deck Plugin Loader release...
jq: error (at <stdin>:1): Cannot index string with string "prerelease"
Installing version ...
curl: no URL specified!
curl: try 'curl --help' for more information
chmod: cannot access '/home/deck/homebrew/services/PluginLoader': No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   376  100   376    0     0   2005      0 --:--:-- --:--:-- --:--:--  2000
Grabbed latest release service.
Created symlink /etc/systemd/system/multi-user.target.wants/plugin_loader.service → /etc/systemd/system/plugin_loader.service.

**Comment by TrainDoctor** [comment]
The terminal/console method is no longer supported. Can you provide the output of the normal .desktop installer?

**Comment by johndwalker** [comment]
I re-ran the .desktop installer and this time it worked. I am a bit perplexed as I didn't do anything different this time. I guess we can close this.
