### ISSUE TITLE
[BUG] Resolving timed out

### ISSUE THREAD

**Issue by MysticDaedra** [SteamDeckHomebrew/decky-loader#408]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

I have spent hours now trying to install Decky Loader. I am using the stable version of SteamOS, and the release version of the Decky installer. I tried installing via the wiki console method several times as well before discovering that this is no longer supported... might want to update the wiki to reflect that.

Every single time I try to install Decky I get the following message in Konsole:

`curl: (28) Resolving timed out after 15000 miliseconds`
`Something went wrong, please report this if it is a bug`

Now I don't know if this is a bug, but I can say that after trying to install this on several different wifi networks (both my home network and my work network), restarting dozens of times, double- and triple-checking that everything that should be turned on is turned on... and I still can't get it installed. If it isn't a bug, then I need help, because nothing I do seems to work at this point.

### Expected Behaviour

Decky loader should install, I would think.

### SteamOS version

SteamOS 3.4.6 Stable

### Selected Update Channel

Stable

### Have you modified the read-only filesystem at any point?

Nope.

### Logs

No log because Decky isn't installed.

Error message:

`curl: (28) Resolving timed out after 15000 miliseconds`
`Something went wrong, please report this if it is a bug`

**Comment by MysticDaedra** [comment]
I did. That is the entire output:

`curl: (28) Resolving timed out after 15000 miliseconds`
`Something went wrong, please report this if it is a bug`

In two lines in Konsole, just like that.

**Comment by PartyWumpus** [comment]
This error would happen if you're unable to connect to github (specifically [https://github.com/SteamDeckHomebrew/decky-installer/releases/latest/download/user_install_script.sh](https://github.com/SteamDeckHomebrew/decky-installer/releases/latest/download/user_install_script.sh)) within the 15 second timeout window. This should not even take seconds, so best guess is that you are unable to connect to it for some reason. 

(also, there is still a CLI install method, as listed in the readme `curl -L https://github.com/SteamDeckHomebrew/decky-installer/releases/latest/download/install_release.sh | sh` and the one listed in the wiki still appears to work properly on my computer)
