### ISSUE TITLE
[BUG] README does not include essential installation instructions

### ISSUE THREAD

**Issue by dinosoeren** [SteamDeckHomebrew/decky-loader#409]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

Thanks for making this useful tool, but I spent several days trying to debug why decky loader doesn't stay installed after a simple reboot of the steam deck.

I had to go to an [external site](https://www.xda-developers.com/how-install-decky-loader-steam-deck/) (not the github or the wiki) to find out that I had to `Enable Developer Mode` and then `Enable CEF Remote Debugging` in `Developer Options` before installing decky loader would work.

Why isn't this **essential pre-installation step** listed anywhere in the `README`? (yes I checked the common issues.) Without that step included, the claim that decky stays installed is quite misleading.

### Expected Behaviour

README should include all essential installation instructions, including pre-installation steps to Enable CEF Remote Debugging.

### SteamOS version

SteamOS 3.4.6 Stable

### Selected Update Channel

Stable

### Logs

[deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/11130255/deckylog.txt)

**Comment by PartyWumpus** [comment]
You should not need to manually enable CEF debugging, as the installer should automatically enable it. It was in the readme before though.

If you manually needed to enable it then something is broken.

**Comment by dinosoeren** [comment]
Ah ok, thanks for clarifying. I was actually surprised to see `CEF Remote Debugging` was already switched on when I went into `Developer Options` after enabling `Developer Mode`.

So if that option isn't usually enabled by default, then it's possible the installation script _did_ do its job and then `Developer Mode` got disabled somehow.

If that's the case & you can't reproduce the issue, then perhaps consider adding a line in the common issues section of the README advising users to double check that `Developer Mode` and `CEF Remote Debugging` haven't been accidentally disabled. That would've been helpful in this case.

**Comment by PartyWumpus** [comment]
The installer enables the CEF debugging option without enabling developer mode, that is expected behavour. (valve does not enable CEF debugging by default)

**Comment by dinosoeren** [comment]
Interesting. For me decky doesn't stay active in gaming mode unless `Developer Mode` is enabled as well. If I disable `Developer Mode` while keeping `CEF Remote Debugging` switched on and then reboot, the decky UI does not appear in the Steam Options right hand menu. However some of the plugin effects (e.g. theme) still remain active.

**Comment by PartyWumpus** [comment]
That is *extremely* unusual for several reasons. 
- On my desktop pc, developer mode has never been enabled and yet decky still works fine through reboots. 
- If css themes are successfully injecting, then CEF debugging has to be on.
- On my steam deck (stable steamos), disabling developer settings and restarting has no effect. (I even toggled CEF debugging off, then disabled dev settings, then reinstalled and it continued to not have an effect

**Comment by TrainDoctor** [comment]
No other users have reported an issue like this. Closing ad possible extreme corner case and wontfix

**Comment by dinosoeren** [comment]
I would like to report that uninstalling & reinstalling decky Fixed the issue for me, I no longer need Dev Mode enabled. Thanks!
