### ISSUE TITLE
Plug-in channel won’t stay on chosen choice

### ISSUE THREAD

**Issue by knightoftherelm** [SteamDeckHomebrew/decky-loader#418]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

I’m on the latest prerelease and when I try and select Testing Channel for plugins and exit the menu it changes back to the default Channel.

### Expected Behaviour

Selected plug-in channel not staying on selected choice

### SteamOS version

Latest steam update

### Selected Update Channel

Stable

### Have you modified the read-only filesystem at any point?

No

### Logs

NA

**Comment by TrainDoctor** [comment]
Please include some logs or videos otherwise we cannot properly reproduce and fix the issue.

**Comment by knightoftherelm** [comment]
When I’m home later I’ll try and shoot a little video clip of the issue so you can seeOn 6 Apr 2023, at 3:21 pm, TrainDoctor ***@***.***> wrote:﻿
Please include some logs or videos otherwise we cannot properly reproduce and fix the issue.
