### ISSUE TITLE
[Request] Decky Plugin Store: add more sort options (show new releases first)

### ISSUE THREAD

**Issue by dJani97** [SteamDeckHomebrew/decky-loader#419]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

As the Decky Plugin Store expands, I think having more sorting options would be nice.

For example:
- newly released
- recently updated
- most popular

As someone who already browsed through the plugin store a couple of times, I'm mostly interested in what's new.

**Comment by PartyWumpus** [comment]
This was resolved by #547, you can now sort by release date and download count. Sorting by most recently updated would also be possible, although it did not seem useful so was not added.
