### ISSUE TITLE
[BUG] can't install decky loader

### ISSUE THREAD

**Issue by oldanderw** [SteamDeckHomebrew/decky-loader#421]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

I was originally on beta version trying to install deck loader via the shortcut downloaded on the desktop, the installer says it completed but in the konsole it says "failed to connect to bus: no medium found". I have tried the curl command and even switching to stable version on my desktop. 

Failed to connect to bus: No medium found
Failed to connect to bus: No medium found
Removed "/etc/systemd/system/multi-user.target.wants/plugin_loader.service".
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   376  100   376    0     0   2623      0 --:--:-- --:--:-- --:--:--  2629
Created symlink /etc/systemd/system/multi-user.target.wants/plugin_loader.service → /etc/systemd/system/plugin_loader.service.

### Expected Behaviour

It should install and work correctly 

### SteamOS version

SteamOS 3.4.3 stable

### Selected Update Channel

Stable

### Have you modified the read-only filesystem at any point?

I have not Modified the read-only filesystem at any point 

### Logs

Apr 07 09:01:57 steamdeck systemd[1]: Started SteamDeck Plugin Loader.
Apr 07 09:01:57 steamdeck PluginLoader[1174]: [selector_events][DEBUG]: Using selector: EpollSelector
Apr 07 09:01:57 steamdeck PluginLoader[1174]: [loader][INFO]: plugin_path: /home/deck/homebrew/plugins
Apr 07 09:01:57 steamdeck PluginLoader[1174]: [updater][DEBUG]: current branch: -1
Apr 07 09:01:57 steamdeck PluginLoader[1174]: [updater][INFO]: Current branch is not set, determining branch from version...
Apr 07 09:01:57 steamdeck PluginLoader[1174]: [updater][INFO]: Current version determined to be pre-release
Apr 07 09:01:57 steamdeck PluginLoader[1174]: [main][DEBUG]: Loading plugins
Apr 07 09:01:57 steamdeck PluginLoader[1174]: [loader][INFO]: import plugins from /home/deck/homebrew/plugins
Apr 07 09:01:57 steamdeck PluginLoader[1174]: [injector][DEBUG]: Steam isn't available yet. Wait for a moment...
Apr 07 09:02:07 steamdeck PluginLoader[1174]: [loader][INFO]: Hot reload enabled
Apr 07 09:02:29 steamdeck PluginLoader[1174]: [updater][DEBUG]: checking for updates
Apr 07 09:02:29 steamdeck PluginLoader[1174]: [updater][DEBUG]: current branch: -1
Apr 07 09:02:29 steamdeck PluginLoader[1174]: [updater][INFO]: Current branch is not set, determining branch from version...
Apr 07 09:02:29 steamdeck PluginLoader[1174]: [updater][INFO]: Current version determined to be pre-release
Apr 07 09:02:29 steamdeck PluginLoader[1174]: [updater][DEBUG]: determining release type to find, branch is 1
Apr 07 09:02:29 steamdeck PluginLoader[1174]: [updater][DEBUG]: release type: pre-release
Apr 07 09:02:29 steamdeck PluginLoader[1174]: [updater][INFO]: Updated remote version information
Apr 07 09:02:29 steamdeck PluginLoader[1174]: [injector][DEBUG]: Steam isn't available yet. Wait for a moment...
Apr 07 09:03:24 steamdeck PluginLoader[1174]: [main][DEBUG]: Couldn't find GamepadUI tab, waiting...
Apr 07 09:03:29 steamdeck PluginLoader[1174]: [main][INFO]: Loading Decky frontend!
Apr 07 09:03:29 steamdeck PluginLoader[1174]: [main][DEBUG]: Page event: None
Apr 07 09:03:31 steamdeck PluginLoader[1174]: [main][DEBUG]: Page event: Page.windowOpen
Apr 07 09:04:03 steamdeck PluginLoader[1174]: [injector][WARNING]: The Tab SharedJSContext socket has been disconnected while listening for messages.
Apr 07 09:04:03 steamdeck PluginLoader[1174]: [main][INFO]: CEF has disconnected...
Apr 07 09:04:03 steamdeck PluginLoader[1174]: [injector][DEBUG]: Steam isn't available yet. Wait for a moment...
Apr 07 09:04:14 steamdeck PluginLoader[1174]: [main][DEBUG]: Couldn't find GamepadUI tab, waiting...
Apr 07 09:06:12 steamdeck systemd[1]: Stopping SteamDeck Plugin Loader...
Apr 07 09:06:12 steamdeck systemd[1]: plugin_loader.service: Main process exited, code=killed, status=9/KILL
Apr 07 09:06:12 steamdeck systemd[1]: plugin_loader.service: Failed with result 'signal'.
Apr 07 09:06:12 steamdeck systemd[1]: Stopped SteamDeck Plugin Loader.
Apr 07 09:06:12 steamdeck systemd[1]: plugin_loader.service: Consumed 1.085s CPU time.
Apr 07 09:06:13 steamdeck systemd[1]: Started SteamDeck Plugin Loader.
Apr 07 09:06:14 steamdeck PluginLoader[4666]: [loader][INFO]: plugin_path: /home/deck/homebrew/plugins
Apr 07 09:06:14 steamdeck PluginLoader[4666]: [updater][INFO]: Current branch is not set, determining branch from version...
Apr 07 09:06:14 steamdeck PluginLoader[4666]: [updater][INFO]: Current version determined to be stable
Apr 07 09:06:14 steamdeck PluginLoader[4666]: [loader][INFO]: import plugins from /home/deck/homebrew/plugins
Apr 07 09:06:24 steamdeck PluginLoader[4666]: [loader][INFO]: Hot reload enabled
Apr 07 09:06:44 steamdeck PluginLoader[4666]: [updater][INFO]: Current branch is not set, determining branch from version...
Apr 07 09:06:44 steamdeck PluginLoader[4666]: [updater][INFO]: Current version determined to be stable
Apr 07 09:06:44 steamdeck PluginLoader[4666]: [updater][INFO]: Updated remote version information
Apr 07 09:11:12 steamdeck systemd[1]: Stopping SteamDeck Plugin Loader...
Apr 07 09:11:12 steamdeck systemd[1]: plugin_loader.service: Main process exited, code=killed, status=9/KILL
Apr 07 09:11:12 steamdeck systemd[1]: plugin_loader.service: Failed with result 'signal'.
Apr 07 09:11:12 steamdeck systemd[1]: Stopped SteamDeck Plugin Loader.
Apr 07 09:11:12 steamdeck systemd[1]: plugin_loader.service: Consumed 1.028s CPU time.
Apr 07 09:11:13 steamdeck systemd[1]: Started SteamDeck Plugin Loader.
Apr 07 09:11:14 steamdeck PluginLoader[5686]: [loader][INFO]: plugin_path: /home/deck/homebrew/plugins
Apr 07 09:11:14 steamdeck PluginLoader[5686]: [updater][INFO]: Current branch is not set, determining branch from version...
Apr 07 09:11:14 steamdeck PluginLoader[5686]: [updater][INFO]: Current version determined to be stable
Apr 07 09:11:14 steamdeck PluginLoader[5686]: [loader][INFO]: import plugins from /home/deck/homebrew/plugins
Apr 07 09:11:24 steamdeck PluginLoader[5686]: [loader][INFO]: Hot reload enabled
Apr 07 09:11:44 steamdeck PluginLoader[5686]: [updater][INFO]: Current branch is not set, determining branch from version...
Apr 07 09:11:44 steamdeck PluginLoader[5686]: [updater][INFO]: Current version determined to be stable
Apr 07 09:11:45 steamdeck PluginLoader[5686]: [updater][INFO]: Updated remote version information

**Comment by PartyWumpus** [comment]
`Failed to connect to bus` is a harmless error, and likely not the cause of your issue. Try installing the prerelease version of decky instead of the stable one.

**Comment by oldanderw** [comment]
That solved the problem, thank you
