### ISSUE TITLE
FPS Drops/Performance Issues After Installing

### ISSUE THREAD

**Issue by rmcguinn** [SteamDeckHomebrew/decky-loader#430]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [ ] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

I was playing Mirror's Edge at max settings at a locked 60fps. Just received my Steam Deck back from RMA (or a new Steam Deck rather) due to a battery issue yesterday. I had Decky installed on my previous Deck for months without issue, but I hadn't gotten around to it on the replacement deck. 

Anyways, I discovered a cool trick that I wanted to share online. But I needed a way to record my screen. So I downloaded the Decky installer from Github and installed it without issue. Went back into game mode and installed a couple plugins. But I noticed when I launched Mirror's Edge my fps was suddenly struggling to break 50 and the frame times were all over the place. I didn't even have any of the plugins enabled at that point, nor was I screen recording. The only thing that changed is that I installed Decky and restarted the deck. This took me from a 100% locked and buttery smooth 60fps in Mirror's Edge, to a choppy 45ish fps in the same game with the same settings. 

I've since uninstalled Decky, restarted the deck multiple times and verified game files for Mirror's Edge through Steam. So at this point there should be no decky files on my Deck at all. Though at this point I might try and do a deep dive to remove any leftover files since the only variable here seems to be installing Decky. Which is quite strange because I used it previously without any issues on my other Steam Deck. 

Since I don't have Decky installed anymore (as a way to try and troubleshoot this) I don't have any logs to attach. I would assume those have been deleted. But I can reinstall it and post the newly generated logs now if need be I suppose. 

### Expected Behaviour

That Decky has no bearing on game performance. I could see it causing an issue if you have a ton of CSS themes running at the same time or something to that effect. But that wasn't the case here. 

### SteamOS version

SteamOS 3.4.6 Stable

### Selected Update Channel

Stable

### Logs

.

**Comment by PartyWumpus** [comment]
That's very unusual.
Could you tell me:
1. Did you uninstall decky normally or did you just manually remove the files?
2. If you go into developer options, is CEF debugging still enabled in there?

**Comment by rmcguinn** [comment]
Yeah sure thing. 

1. I uninstalled it through the same installer I used to install it. Haven't manually removed anything beyond that. 
2. I did turn off developer options. Just turned it back on and CEF is toggled off.

**Comment by TrainDoctor** [comment]
Honestly, I cannot really in good faith believe that Decky has had any hand in the degradation of performance for you. Decky is not the most performant tool almost assuredly but it's not a resource hog either. I'll be leaving this issue open but this feels largely like a correlation than any causative relationship. I feel in between you installing decky and playing mirrors edge, the system began a filesystem trim and I suspect this could be correlated to the downturn in performance many folks instead attribute to Loader in my experience.

**Comment by rmcguinn** [comment]
Yeah I couldn't tell ya. But all I do know is that I had been playing for a few hours with everything running perfectly. The only thing I did was head over to desktop mode, launched Firefox and then installed Decky through the standard installer. Restarted the Deck, went into game mode and installed a few plugins. Launched Mirror's Edge on the same save and performance took a big hit. 

I didn't change any settings in the QAM, nor in the game. I didn't even connect to a new WiFi network or bluetooth device or anything like that. So I'm having a hard time thinking of what else could have caused the issues in all honesty. But it's not impossible I suppose. Short of doing a full reinstall of SteamOS I'm not too sure how to even go about troubleshooting this. GPU and CPU aren't at 100% usage, changing the wattage or GPU clock doesn't seem to make a difference either. It's pretty strange. Maybe I'll try switching over to the SteamOS Beta channel as a last resort before having to go through and re set everything up again.

**Comment by rmcguinn** [comment]
Well I'm really not sure what to say but it seems like everything is running fine again. I didn't do absolutely anything to try and troubleshoot it. But it's back to 60fps. Very very strange. Guess I'll just wait until after I beat Mirror's Edge and then reinstall Decky. 

Appreciate you guys taking the time though.
