### ISSUE TITLE
[Request] flatpak installation?

### ISSUE THREAD

**Issue by finete** [SteamDeckHomebrew/decky-loader#433]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

It would nicer if you could install the deck loader directly from the discovers app of the desktop mode. if a flatpak is added it would be possible.
Not sure if flatpak has sufficient privileges for decky loader though.

**Comment by TrainDoctor** [comment]
This is not currently in scope for Decky but I appreciate the interest.

**Comment by bleonard252** [comment]
I might be wrong but doesn't Decky need system level permissions to install services and whatnot?

**Comment by TrainDoctor** [comment]
> I might be wrong but doesn't Decky need system level permissions to install services and whatnot?

This is correct yes.

**Comment by TrainDoctor** [comment]
There is no real chance Decky will ship in flatpak form unless some fundamental architectural changes are made. If a developer is willing to assist us to make those changes than I'm sure we'd be happy to accept and target a flatpak but for now this isn't really on the table.
