### ISSUE TITLE
[Request] allow Decky-loader to detect holoiso on steam deck

### ISSUE THREAD

**Issue by crlink271986** [SteamDeckHomebrew/decky-loader#434]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

so I use Holo ISO instead of Steam OS3 (Main reason is no btrfs filesystem restrictions that reset after updates) when i install decky it says this is not a steamdeck but it is you think theres a way to hook onto the hw level for checks (the steam decks controller seems viable as a way to check if it detects the controls (and matches them to valves SN etc ) the steamdeck check will pass

**Comment by PartyWumpus** [comment]
It still works fine if it's not a steam deck, the only difference is that the installer won't set a temporary password for you.
