### ISSUE TITLE
[Request] quick mute toggle

### ISSUE THREAD

**Issue by markstinson** [SteamDeckHomebrew/decky-loader#447]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

Per a recent [steam deck discussion](https://steamcommunity.com/app/1675200/discussions/0/3410928883771631415/) it was pointed out the Steam Deck lacks a quick "mute" button. And there is no Steam+Button combo shortcut either.

A (somewhat) near-UI surface mute button is needed. Valve won't likely have a solution soon. The mute button in Deck Loader would be the next fewest presses away "..." > Decky > mute toggle.

Although a top-level mute slider/button next to ... say the Decky Loader settings gear ... goes against the basic UI design and plug-in nature of it. However, a mute button is something that appears at the highest level of a UI interface, not buried inside a plugin or deeper UI navigation.

Thoughts or feedback on how to implement a much needed mute button?

**Comment by TrainDoctor** [comment]
While I like the idea, Loader makes only a few tweaks to the UI outside of plugins and these changes are largely just about exposing settings and configuration options to users. This falls under the scope of a plugin. I'll run this by the team but if the team doesn't express an interest I'll be closing this. Thanks for your interest in Decky and hopefully we can continue adding features and improving, even if it's not this one in particular.

**Comment by JohnnyCrazy** [comment]
So the core idea of decky loader is provide plugins with a rich toolkit to enhance the deck. In this case, since it needs to be very top-level, I think it will be hard to find a generalized API we can give out to plugin developers.

I'm kinda tempted to add a quick microphone and speaker mute toggle to the decky plugin overview, triggered via hotkeys while the plugin overview is open. But I will get the other folks opinion first.

**Comment by JohnnyCrazy** [comment]
After discussing this internally, we won't have this feature in the core decky as we see it in the responsibilities of plugins to implement such functionality.
