### ISSUE TITLE
[BUG] Missing QMA order management 

### ISSUE THREAD

**Issue by PunkyBust** [SteamDeckHomebrew/decky-loader#452]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [ ] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

Hello,

Am I crazy, I'm sure there was recently the possibility to organize the order of plugins in the QMA.
I used it recently, it seems to me that it was directly in config // plugins
Test on pre release and stable decky and beta and stable deck client.

Am I talking nonsense?
Thanks to all.
Have a nice Saturday

### Expected Behaviour

In config menu

### SteamOS version

Steam OS  3.4.8

### Selected Update Channel

Prerelease

### Have you modified the read-only filesystem at any point?

No

### Logs

N/A

**Comment by TrainDoctor** [comment]
Go to the settings cog and then to plugins to reorder plugins. Thanks.
