### ISSUE TITLE
[BUG] Some plugins are erroring out with TypeError

### ISSUE THREAD

**Issue by vedhavyas** [SteamDeckHomebrew/decky-loader#453]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

I installed Deckey loader and started installing plugins

Some plugins worked some plugins gave TypeError: mod?.PanelSelection?.includes not a function.

### Expected Behaviour

All plugins should work

### SteamOS version

SteamOs 3.4.8 Preview

### Selected Update Channel

Prerelease

### Have you modified the read-only filesystem at any point?

Nope

### Logs

May 13 23:56:32 hustler systemd[1]: Started SteamDeck Plugin Loader.
May 13 23:56:33 hustler PluginLoader[1293]: [selector_events][DEBUG]: Using selector: EpollSelector
May 13 23:56:33 hustler PluginLoader[1293]: [loader][INFO]: plugin_path: /home/deck/homebrew/plugins
May 13 23:56:33 hustler PluginLoader[1293]: [updater][DEBUG]: current branch: 1
May 13 23:56:33 hustler PluginLoader[1293]: [main][DEBUG]: Loading plugins
May 13 23:56:33 hustler PluginLoader[1293]: [loader][INFO]: import plugins from /home/deck/homebrew/plugins
May 13 23:56:33 hustler PluginLoader[1293]: [loader][INFO]: found plugin: SDH-AnimationChanger
May 13 23:56:33 hustler PluginLoader[1293]: [loader][INFO]: Loaded Animation Changer
May 13 23:56:33 hustler PluginLoader[1301]: [selector_events][DEBUG]: Using selector: EpollSelector
May 13 23:56:33 hustler PluginLoader[1293]: [injector][DEBUG]: Steam isn't available yet. Wait for a moment...
May 13 23:56:43 hustler PluginLoader[1293]: [main][DEBUG]: Couldn't find GamepadUI tab, waiting...
May 13 23:56:48 hustler PluginLoader[1293]: [main][INFO]: Loading Decky frontend!
May 13 23:56:48 hustler PluginLoader[1293]: [main][DEBUG]: Page event: None
May 13 23:56:53 hustler PluginLoader[1293]: [main][DEBUG]: Page event: Page.windowOpen
May 13 23:57:02 hustler PluginLoader[1293]: [updater][DEBUG]: checking for updates
May 13 23:57:02 hustler PluginLoader[1293]: [updater][DEBUG]: current branch: 1
May 13 23:57:03 hustler PluginLoader[1293]: [updater][DEBUG]: release type: pre-release
May 13 23:57:03 hustler PluginLoader[1293]: [updater][DEBUG]: determining release type to find, branch is 1
May 13 23:57:03 hustler PluginLoader[1293]: [updater][DEBUG]: release type: pre-release
May 13 23:57:03 hustler PluginLoader[1293]: [updater][INFO]: Updated remote version information
May 13 23:57:06 hustler PluginLoader[1293]: [updater][DEBUG]: checking for updates
May 13 23:57:06 hustler PluginLoader[1293]: [updater][DEBUG]: current branch: 1
May 13 23:57:08 hustler PluginLoader[1293]: [updater][DEBUG]: release type: pre-release
May 13 23:57:08 hustler PluginLoader[1293]: [updater][DEBUG]: determining release type to find, branch is 1
May 13 23:57:08 hustler PluginLoader[1293]: [updater][DEBUG]: release type: pre-release
May 13 23:57:08 hustler PluginLoader[1293]: [updater][INFO]: Updated remote version information
May 13 23:57:28 hustler PluginLoader[1293]: [browser][INFO]: Installing Animation Changer from URL (Version: 1.3.0)
May 13 23:57:28 hustler PluginLoader[1293]: [browser][DEBUG]: Fetching https://cdn.tzatzikiweeb.moe/file/steam-deck-homebrew/versions/f118f485dbd9a12878b054b2d39ae7a66bfa3b1388b88222f46f6fcaf584a952.zip
May 13 23:57:28 hustler PluginLoader[1293]: [browser][DEBUG]: Got 200. Reading...
May 13 23:57:28 hustler PluginLoader[1293]: [browser][DEBUG]: Read 57588 bytes
May 13 23:57:28 hustler PluginLoader[1293]: [browser][DEBUG]: Uninstalling existing plugin...
May 13 23:57:28 hustler PluginLoader[1293]: [base_events][ERROR]: Unclosed client session
May 13 23:57:28 hustler PluginLoader[1293]: client_session: <aiohttp.client.ClientSession object at 0x7f5a3629b880>
May 13 23:57:28 hustler PluginLoader[1293]: [browser][INFO]: uninstalling Animation Changer
May 13 23:57:28 hustler PluginLoader[1293]: [browser][INFO]:  at dir /home/deck/homebrew/plugins/SDH-AnimationChanger
May 13 23:57:28 hustler PluginLoader[1293]: [browser][DEBUG]: calling frontend unload for Animation Changer
May 13 23:57:28 hustler PluginLoader[1293]: [browser][DEBUG]: result of unload from UI: {'id': 1, 'result': {'result': {'type': 'undefined'}}}
May 13 23:57:28 hustler PluginLoader[1293]: [browser][DEBUG]: Plugin Animation Changer was found
May 13 23:57:28 hustler PluginLoader[1293]: [browser][DEBUG]: Plugin Animation Changer was stopped
May 13 23:57:28 hustler PluginLoader[1293]: [browser][DEBUG]: Plugin Animation Changer was removed from the dictionary
May 13 23:57:28 hustler PluginLoader[1293]: [browser][DEBUG]: Plugin Animation Changer was removed from the pluginOrder setting
May 13 23:57:28 hustler PluginLoader[1293]: [browser][DEBUG]: removing files Animation Changer
May 13 23:57:28 hustler PluginLoader[1293]: [browser][DEBUG]: Unzipping...
May 13 23:57:28 hustler PluginLoader[1293]: [browser][DEBUG]: No Remote Binaries to Download
May 13 23:57:28 hustler PluginLoader[1293]: [browser][INFO]: Installed Animation Changer (Version: 1.3.0)
May 13 23:57:29 hustler PluginLoader[1293]: [browser][DEBUG]: Plugin Animation Changer was added to the pluginOrder setting
May 13 23:57:29 hustler PluginLoader[1293]: ======== Running on http://127.0.0.1:1337 ========
May 13 23:57:29 hustler PluginLoader[1293]: (Press CTRL+C to quit)
May 13 23:57:29 hustler PluginLoader[1293]: [loader][INFO]: Loaded Animation Changer
May 13 23:57:29 hustler PluginLoader[2591]: [selector_events][DEBUG]: Using selector: EpollSelector
May 13 23:58:56 hustler PluginLoader[1293]: [browser][INFO]: Installing Bluetooth from URL (Version: 2.0.2)
May 13 23:58:56 hustler PluginLoader[1293]: [browser][DEBUG]: Fetching https://cdn.tzatzikiweeb.moe/file/steam-deck-homebrew/versions/24f890938d1dacd82e7192f3dd18c7ffa201adc31029300cec31d379d09dc17d.zip
May 13 23:58:57 hustler PluginLoader[1293]: [browser][DEBUG]: Got 200. Reading...
May 13 23:58:57 hustler PluginLoader[1293]: [browser][DEBUG]: Read 18178 bytes
May 13 23:58:57 hustler PluginLoader[1293]: [browser][DEBUG]: Unzipping...
May 13 23:58:57 hustler PluginLoader[1293]: [browser][DEBUG]: No Remote Binaries to Download
May 13 23:58:57 hustler PluginLoader[1293]: [browser][INFO]: Installed Bluetooth (Version: 2.0.2)
May 13 23:58:58 hustler PluginLoader[1293]: [browser][DEBUG]: Plugin Bluetooth was added to the pluginOrder setting
May 13 23:58:58 hustler PluginLoader[1293]: [loader][INFO]: Loaded Bluetooth
May 13 23:58:58 hustler PluginLoader[2731]: [selector_events][DEBUG]: Using selector: EpollSelector

**Comment by PartyWumpus** [comment]
Known issue on beta steamos, will hopefully be resolved soon. If you want decky now, you can just downgrade to stable steamos.
