### ISSUE TITLE
[Request] “Update All” button for plugins

### ISSUE THREAD

**Issue by a5ehren** [SteamDeckHomebrew/decky-loader#461]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

A single button to check for and update all plugins would be great.

A pop up that concatenates all the change logs when it is done would also be great.

**Comment by DisasterIncarnate** [comment]
an obvious and appreciated addition if implimented.

**Comment by saworden** [comment]
Would we want "check for updates" and "update all" to be two separate actions/buttons?

**Comment by a5ehren** [comment]
Decky already checks for updates when you load the plugin page. I think a button that waits for that check to finish and runs all the installs is all that is needed.

**Comment by vlaght** [comment]
My brothers in Christ, I would pray for you in case this feature would be released

**Comment by TrainDoctor** [comment]
> My brothers in Christ, I would pray for you in case this feature would be released

Hey, just keep in mind we're an entirely volunteer project. Also, we're deep in the weeds of a plugin developer focused update to resolve long-standing issues. Specifically, with plugins breaking every update and we're aiming to prevent this.
