### ISSUE TITLE
[BUG] Weblate had alert and can't translate now

### ISSUE THREAD

**Issue by david082321** [SteamDeckHomebrew/decky-loader#464]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

See: https://weblate.werwolv.net/projects/decky/decky/#alerts

### Expected Behaviour

Can be translate.

### SteamOS version

N/A

### Selected Update Channel

Stable

### Have you modified the read-only filesystem at any point?

N/A

### Logs

See: https://weblate.werwolv.net/projects/decky/decky/#alerts
`error: could not apply aceeaee... Translated using Weblate (Italian)
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply aceeaee... Translated using Weblate (Italian)
Auto-merging backend/locales/it-IT.json
CONFLICT (content): Merge conflict in backend/locales/it-IT.json
 (1)`

**Comment by RodoMa92** [comment]
Fixed as of 578b8b3, closing it now :)
