### ISSUE TITLE
[BUG] Decky frontend defaults to displaying 'prerelease' as update channel regardless of actual value

### ISSUE THREAD

**Issue by PartyWumpus** [SteamDeckHomebrew/decky-loader#472]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

Going into the settings menu with a stable version of decky, it sometimes (exact cause currently unclear) displays the selected branch as 'prerelease' even though the user is on stable decky. It still clearly is looking for stable versions of decky, and the backend (as you can see in the logs if you look at line 11208) succesfully determines the version to be stable so this is a frontend issue.

https://github.com/SteamDeckHomebrew/decky-loader/assets/48649272/203d4448-d3cb-4692-a5e6-efa6676fb3c7

I am using a manually installed version of decky here, but I have seen reports of this issue on normal decky, and the changes in the version i'm using would not affect this menu at all.

### Expected Behaviour

The version shown by the UI should match the version in the backend.

### SteamOS version

EndevourOS

### Selected Update Channel

Stable

### Logs

[deckylogs.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/11623835/deckylogs.txt)

**Comment by PartyWumpus** [comment]
Found the cause. https://github.com/SteamDeckHomebrew/decky-loader/blob/main/frontend/src/components/settings/pages/general/BranchSelect.tsx this file doesn't ever ask the backend for the current version, and it defaults to the prerelease. Also the current branch doesn't appear to be included anywhere in DeckyState, only the current version.

**Comment by AAGaming00** [comment]
Fixed by #480
