### ISSUE TITLE
[Request] Option to Disable updates pop-up forever!

### ISSUE THREAD

**Issue by CarlBraun** [SteamDeckHomebrew/decky-loader#473]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

I have so much plugins and so frequently it shows me "updates available" pop-up while gaming, or waking up deck with sound. Its so annoying. Please add a switch in settings for any notifications(plugin updates, decky updates)

**Comment by al12gamer** [comment]
Agreed, this would rock

**Comment by RodoMa92** [comment]
It's in prerelease and will come out shortly as a release, if you want to use it right now, switch to prerelease as a channel. Closing.
