### ISSUE TITLE
[Request] <title>missing deck settings plugin

### ISSUE THREAD

**Issue by clapsterxi** [SteamDeckHomebrew/decky-loader#474]
### Please confirm

- [X] I have searched existing issues
- [ ] This issue is not a duplicate of an existing one
- [ ] This is not a request for a plugin

### Feature Request Description

missing deck settings plugin

**Comment by TrainDoctor** [comment]
What?

**Comment by clapsterxi** [comment]
after installing decky loading. There is a plugin I searched for that is called "deck settings". It no longer shows up in the decky loader store. Is there any other way of getting that plugin

**Comment by TrainDoctor** [comment]
> after installing decky loading. There is a plugin I searched for that is called "deck settings". It no longer shows up in the decky loader store. Is there any other way of getting that plugin

That plugin is currently hidden until it can be updated. Please seek out the author of the plugin. We do not control how plugins get updated.
