### ISSUE TITLE
[BUG] Booting kubuntu on desktop is hanging with the message failed to to load SteamDeck Plugin Loader

### ISSUE THREAD

**Issue by kepiz** [SteamDeckHomebrew/decky-loader#483]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [ ] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

I'm on a desktop
Trying to boot and can't get into desktop
hanging with the message failed to to load SteamDeck Plugin Loader.
Tried looking for the systemctl Steam service but I'm finding nothing 

### Expected Behaviour

Booting into kubuntu desktop

### SteamOS version

Kubuntu latest

### Selected Update Channel

Stable

### Logs

Failed to load SteamDeck Plugin Loader

**Comment by TrainDoctor** [comment]
We currently do not provide support for distros outside of SteamOS.
