### ISSUE TITLE
[BUG] Weblate URL has typo error

### ISSUE THREAD

**Issue by OctopusET** [SteamDeckHomebrew/decky-loader#484]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

When you click Translation file URL on the translation page, the url is https://github.com/SteanDeckHomebrew/decky-loader/blob/main/locales/XXXX. "`SteanDeckHomebrew`" should be changed to "`SteamDeckHomebrew`"

Example link : https://weblate.werwolv.net/translate/decky/decky/en/?checksum=03f9f959aa9d4dc8
You can find Translation file URL on the right side of webpage

### Expected Behaviour

URL should contain "`SteamDeckHomebrew`" not the "`SteamDeckHomebrew`"

### SteamOS version

Weblate

### Selected Update Channel

Stable

### Logs

.

**Comment by OctopusET** [comment]
https://github.com/SteamDeckHomebrew/decky-loader/blob/main/backend/locales/en-US.json
Plus, URL does not include "`backend`"

**Comment by RodoMa92** [comment]
Thanks for the report, it's fixed now.

Closing.
