### ISSUE TITLE
[BUG] Side menus won't open after latest Steam update

### ISSUE THREAD

**Issue by ShadowFlare** [SteamDeckHomebrew/decky-loader#490]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [ ] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

Updated Steam (new version that has the overhauled interface in desktop mode) and the left and right side menus in game mode won't open as long as Decky Loader is installed. Uninstalled and they worked again, reinstalled Decky Loader and they were broken again (won't appear at all).

### Expected Behaviour

Already explained above

### SteamOS version

Not sure, but it's up-to-date on stable branch (already have device shut down and put away and didn't want to go get it)

### Selected Update Channel

Stable

### Logs

Don't have one, currently uninstalled until it's fixed. Should be easily reproduceable though.

**Comment by TrainDoctor** [comment]
Without logs and SteamOS version we can do nothing with this report.

**Comment by ShadowFlare** [comment]
Well, I'm sure it will get worked on even if I hadn't sent this report, but was just wanting to give a heads up about it. Don't really feel like getting my device and going through 3 or more reboots to get the info you want at this time and then restoring it back to a working state.
