### ISSUE TITLE
potentional decky issue with beta steam os

### ISSUE THREAD

**Issue by papandbuddygirl** [SteamDeckHomebrew/decky-loader#491]
when pressing steam button or the 3 dots button its invisible in offline mode  in beta
[deckylogs.txt](https://github.com/SteamDeckHomebrew/decky-plugin-database/files/11828245/deckylogs.txt)

**Comment by RossComputerGuy** [comment]
I'm having the same problem on stable, if I'm offline or online I can't see the Decky menu button in quick access menu. But Decky is still running.

**Comment by papandbuddygirl** [comment]
I'm glad I'm not the only one who has this issue I know swapping builds fixed it for me but must seem to be a decky bug glad its reported though

**Comment by papandbuddygirl** [comment]
Well I noticed the decky button sometimes goes missing to this in specific the whole UI was missing it was strange

**Comment by pwnedbygary** [comment]
I can't see the menu either. I've installed, Uninstalled, Uninstaller, reinstalled the damn plugin probably a dozen times to get it to show, and it never does. Steam deck oled running beta branch, stable or even preview, nothing. Worked flawlessly on my lcd model which is strange to me.

**Comment by TrainDoctor** [comment]
> I can't see the menu either. I've installed, Uninstalled, and reinstalled the damn plugin probably a dozen times to get it to show, and it never does.
> 
> This is a Steam Deck oled running beta branch, stable or even preview, nothing. Worked flawlessly on my lcd model which is strange to me.

Can you please gather and submit logs to this thread? Your experience is practically useless to use unless we can see what's going on.

**Comment by FineWolf** [comment]
## Providing Logs

In order to aid in analyzing your issue, you need to provide us with the logs files for the Plugin Loader and any associated plugins that you may have an issue with.

You can extract the logs from your Steam Deck by running the following commands in desktop mode (or via an SSH connection):

```bash
journalctl -b all -u plugin_loader.service > ~/homebrew/logs/plugin_loader.log
tar -czf ~/Desktop/DeckyLogs.tgz -C ~/homebrew/logs .
```

Please attach the resulting `DeckyLogs.tgz` file from your desktop onto this ticket.

**Comment by pwnedbygary** [comment]
Sure, I will attach the logs whenever I get home; thanks for the command.

**Comment by pwnedbygary** [comment]
attached the log file as requested: 
[DeckyLogs.TGZ](https://github.com/SteamDeckHomebrew/decky-loader/files/14114887/DeckyLogs.TGZ)

**Comment by pwnedbygary** [comment]
Any ideas on this guys? Would really like to figure out why decky wont install or work properly anymore.

**Comment by TrainDoctor** [comment]
> Any ideas on this guys? Would really like to figure out why decky wont install or work properly anymore.

What version of steamos are you on? What client version vs the actual OS etc. just give me all the info you can. The logs indicate that it can't inject into the UI as it expects to be able to.

**Comment by FineWolf** [comment]
@pwnedbygary 

Looking at the error message, it is possible that you have a process on your Steam Deck that is listening to port `:8080`.

The Plugin Loader injects itself via Steam's CEF debugging port on that particular port. It seems however that it cannot as it is being used by something else.

Can you run the following command and share the output?

```
lsof -i :8080 -sTCP:LISTEN +c 0
```

**Comment by pwnedbygary** [comment]
Looks like Syncthing lmao

`(1)(deck@steamdeck ~)$ lsof -i :8080 -sTCP:LISTEN +c 0
COMMAND    PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
syncthing 1129 deck   24u  IPv4  25771      0t0  TCP localhost:http-alt (LISTEN)
`

**Comment by pwnedbygary** [comment]
Turns out the UI was listening on that port. Changed to another and Decky works again! Thanks for the tip
