### ISSUE TITLE
[BUG] Decky Loader refusing to Install

### ISSUE THREAD

**Issue by Svetlanist1917** [SteamDeckHomebrew/decky-loader#492]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

A few days ago I noticed my Decky Loader menu was missing from game mode, so I went ahead and attempted to update, but each time I try It doesn't work

When I try to use the Decky Loader install script today, I put in my sudo password and then got this output

```
jq: error (at <stdin>:1): Cannot index string with string "prerelease"




chmod: cannot access '/home/deck/homebrew/services/PluginLoader': No such file or directory
Failed to connect to bus: No medium found
Failed to connect to bus: No medium found
Removed "/etc/systemd/system/multi-user.target.wants/plugin_loader.service".
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   421  100   421    0     0    470      0 --:--:-- --:--:-- --:--:--   470
Created symlink /etc/systemd/system/multi-user.target.wants/plugin_loader.service → /etc/systemd/system/plugin_loader.service.
chown: cannot access '/home/deck/homebrew/services/*': No such file or directory
```

Whenever this is all done, I get a popup saying "Install finished, installer can now be closed" however when i go back to game mode, the plugin menu does not appear. 

Yes I have tried to use EmuDeck's installation. Yes I turned on CEF remote debugging. Yes I tried Pre-Release as well, and all failed to properly function.

### Expected Behaviour

It should properly function and let me download plugins, however this doesn't work. My only conclusion would be that this Homebrew does not work on 3.4.8.

### SteamOS version

SteamOS 3.4.8 Stable

### Selected Update Channel

Stable

### Logs

[deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/11835869/deckylog.txt)

**Comment by E1fs** [comment]
Try this : [Oflline Installer](https://sora-1252821661.cos.ap-beijing-1.myqcloud.com/outline/steamdeck/decky-loader/DeckyLoader.zip)
1. Unzip.
2. chmod +x install_release_offline.sh
3. ./install_release_offline.sh
4. The installed version is v2.10.4-pre7

**Comment by PartyWumpus** [comment]
This problem appears to be fixed. Also, I would not recommend using random zip installers shared online like the one above.

**Comment by nevusss** [comment]
I am having the exact same problem without the failed to connect to bus

**Comment by TrainDoctor** [comment]
> I am having the exact same problem without the failed to connect to bus

Please make a new issue and include logs then.

**Comment by MezMez** [comment]
This issue seems to have resurfaced. Thought it may have been a plugin issue, but after deleting the contents of the plugin folder, and finally looking at the error message, that this is more applicable. 

Happened while I was trying to install an update for emudecky, but I am assuming that it was just what caused Decky to see that issue to begin with.

Hope it gets fixed soon. I know SteamOS has been getting a lot of updates lately even on Stable. My version currently is: 3.8.14

**Comment by netzkopf** [comment]
i  can confirm that the problem resurfaced. I get the exact same message as OP.
