### ISSUE TITLE
[BUG] Quick access menu interface moves up(appearing space on the bottom and hidden top bar)

### ISSUE THREAD

**Issue by CarlBraun** [SteamDeckHomebrew/decky-loader#498]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

Steps to reproduce:
1. Booting up the Deck
2. Launching any app
3. Get into Quick access menu

### Expected Behaviour

1. On the top bar It should show a Wi-Fi icon, Battery level, Clocks & profile picture. but its not. (probably because of "show keyboard icon" in "Quick access menu")
2. On the bottom it shouldn't show transparent space with "A Select" button

### SteamOS version

SteamOS 3.4.8

### Selected Update Channel

Stable

### Logs

[deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/11895229/deckylog.txt)

Screenshot of the problem [Steam Screenshot](https://github.com/SteamDeckHomebrew/decky-loader/assets/104396403/c16be665-e4c9-4ac1-b9e1-6ff74bf16778)

**Comment by TheUntappableKeg** [comment]
I have also experienced this bug except reversed. Example would be I can only see half of the steam haptics toggle option. It moves the Quick access menu down.

**Comment by AAGaming00** [comment]
Should be fixed in latest prerelease
