### ISSUE TITLE
[BUG] Plugin order is not consistent after updating plugins

### ISSUE THREAD

**Issue by PartyWumpus** [SteamDeckHomebrew/decky-loader#513]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [ ] I have attached logs to this bug report (failure to include logs will mean your issue will not be responded too).

### Bug Report Description

After a plugin is updated, the plugin order is succesfully restored to the order it should be, but then after the steam client is restarted or if decky is restarted, the updated plugins move to the bottom. If the order is manually changed before the client restarts, it'll work fine.

The frontend has the correct order, but the backend does not. When a plugin is updated the loader.json's pluginOrder list first loses that plugin from the list and then it appears again at the bottom. This is likely fixable either by putting the same code that fixes the order in the frontend into the backend as well, or just saving the order from the frontend whenever a plugin is updated or possibly removing the code that's incorrectly saving to the loader.json file on a plugin update.

### Expected Behaviour

The order should be consistent. 

### SteamOS version

SteamOS 3.5 Main

### Selected Update Channel

Stable

### Have you modified the read-only filesystem at any point?

Yes, not relevant

### Logs

not relevant

**Comment by btabaska** [comment]
#522 Pull Request to add backend settings sync to plugin order like notification settings uses.

**Comment by nabel0** [comment]
I can confirm this...Same here
