### ISSUE TITLE
[Request] Gentoo/OpenRC Compatibility

### ISSUE THREAD

**Issue by ThisNekoGuy** [SteamDeckHomebrew/decky-loader#534]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

The install script assumes every Linux system it's run on is using Systemd, which is not the case on Gentoo; can the script please be adapted to detect this and, if necessary, use the appropriate service format and init commands?
Decky Loader can be useful on desktop too, and I just moved to Gentoo recently :p

(It also assumes everyone uses `sudo` even though `doas` is an alternative [that I use] >_>)

**Comment by TrainDoctor** [comment]
> ### Please confirm
> 
>     * [x]  I have searched existing issues
> 
>     * [x]  This issue is not a duplicate of an existing one
> 
>     * [x]  This is not a request for a plugin
> 
> 
> ### Feature Request Description
> 
> The install script assumes every Linux system it's run on is using Systemd, which is not the case on Gentoo; can the script please be adapted to detect this and, if necessary, use the appropriate service format and init commands? Decky Loader can be useful on desktop too, and I just moved to Gentoo recently :p
> 
> (It also assumes everyone uses `sudo` even though `doas` is an alternative [that I use] >_>)
> ### Further Description
> 
> _No response_

Feel free to implement these on your own time. The largest percentage of the most used distributions use systemd like it or not. Also this tool is and has always been targeted at the steam deck and speaking for myself at least, I have no interest in making 100% compatibility with every possible little different configuration.

**Comment by Witherking25** [comment]
It's a simple task, the systemd service used here is very simplistic, so you can implement and pr if you like

**Comment by Witherking25** [comment]
the current systemd service is this:
```
[Unit]
Description=SteamDeck Plugin Loader
After=network-online.target
Wants=network-online.target
[Service]
Type=simple
User=root
Restart=always
ExecStart=/home/deck/homebrew/services/PluginLoader
WorkingDirectory=/home/deck/homebrew/services
KillSignal=SIGKILL
Environment=UNPRIVILEGED_PATH=/home/deck/homebrew
Environment=PRIVILEGED_PATH=/home/deck/homebrew
Environment=LOG_LEVEL=INFO
[Install]
WantedBy=multi-user.target
```
you can try this one for openrc, untested as I don't have a machine that runs it
```
#!/sbin/openrc-run

name=$RC_SVCNAME
description="SteamDeck Plugin Loader"
supervisor="supervise-daemon"
command=""
command_args="/home/deck/homebrew/services/PluginLoader"
supervise_daemon_args=" -d /home/deck/homebrew/services -e LOG_LEVEL=\"INFO\""
command_user="root"

depend() {
	after network-online 
	use network-online 
}
```
