### ISSUE TITLE
[Request] Plugin.uninstall callback function

### ISSUE THREAD

**Issue by wheaney** [SteamDeckHomebrew/decky-loader#536]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [x] This is not a request for a plugin

### Feature Request Description

During uninstall, [decky-loader calls stop()](https://github.com/SteamDeckHomebrew/decky-loader/blob/main/backend/browser.py#L121) which triggers `_unload()`, but from my conversations in Discord, I can't rely on `_unload()` to be 1:1 with uninstall (i.e. it may be triggered at other times in the plugin lifecycle).

My plugin installs a systemd service when it's loaded, but since there's no reliable way to tap into decky's uninstall mechanism, a user uninstalling my plugin may be surprised to find that it's still operating behind the scenes.

This request is to add an `uninstall` function to the Plugin interface that is called after `stop()` and before deletion of the plugin directory.

**Comment by wheaney** [comment]
@PartyWumpus This is showing up as assigned to me in the SDH Tracker. I've implemented and test this myself, so at this point I'm just waiting for reviews/testing. Should it be assigned to someone else (or unassigned)?

**Comment by TrainDoctor** [comment]
@wheaney we simply use assignment as a marker of who requested and or is working on a feature request etc.
