### ISSUE TITLE
[Request] Allow plugins as Python modules

### ISSUE THREAD

**Issue by Jan200101** [SteamDeckHomebrew/decky-loader#537]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

Decky Plugins should also be usable as a python module

### Further Description

Right now plugins are mainly loaded via a main.py
A module would allow proper encapsulation of the code as well as allow specifying relevant information in multiple ways that are query able through official means (the pkg_resources library).

Modules would also allow the creation of wheels, which can be used to bundle dependencies of various kind.

**Comment by Witherking25** [comment]
What would also be useful is to tell decky to just start and stop a binary, as I mainly just have a native backend and use websockets to communicate. This would completely eliminate the need for a python file in general if you don't want one

**Comment by Witherking25** [comment]
But yes op makes a good point and is a better plan than the current py_modules thing

**Comment by Witherking25** [comment]
It seems for module backends, all that really needs changing is this line here
https://github.com/SteamDeckHomebrew/decky-loader/blob/main/backend/loader.py#L159
To fall back to `main` instead of `main.py` if `main.py` doesn't exist

**Comment by Witherking25** [comment]
Well, depending on how importlib handles things it may need to be the __init__.py

**Comment by Jan200101** [comment]
Importlib handles it like the core import
So when importing a module e.g. main/ you need main/__init__.py (edit sniped, damn)

The module name could be made configurable but one step at a time

**Comment by Witherking25** [comment]
Yeah, that line seems to be the only change really needed

**Comment by Witherking25** [comment]
Feel free to pr if you like

**Comment by Jan200101** [comment]
Enough feedback on the Discord has convinced me that this isn't worthwhile.
