### ISSUE TITLE
[BUG] Decky disappeared from the three dot menu on new update of steamOS

### ISSUE THREAD

**Issue by HankeMat** [SteamDeckHomebrew/decky-loader#538]
### Please confirm

- [ ] I have searched existing issues
- [ ] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [ ] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

The Menu of this application that should be visible when you press the tree dots button on your steam deck is gone. Somehow it disappeared and the last thing I did that coudl cause this is the new SteamOS release, because I dont really know how this app works but every steamOS update wipes everything except yur home foder it might be the issue somehow, so I tried to install Decky Loader once again and nothing changed at all.

### Expected Behaviour

It should be showing a decky logo when you press the three dots button on youre steam deck and give its menu.

### SteamOS version

SteamOS 3.4.10

### Selected Update Channel

Stable

### Have you modified the read-only filesystem at any point?

No

### Logs

I dont have access to the log. Firstly I dont know where to find, but all the files are gone somehow

**Comment by TrainDoctor** [comment]
Please gather logs. The template you filled out had instructions on how to do so.

**Comment by HankeMat** [comment]
[deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/12587220/deckylog.txt)
Is that it? Sorry, Iam kinda new to GitHub and all

**Comment by HankeMat** [comment]
> > [deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/12587220/deckylog.txt)
> > Is that it? Sorry, Iam kinda new to GitHub and all
> 
> It seems like decky is failing to load due to an issue with the executable. Try running the decky installer again.

I tried that. And nothing happened

**Comment by PartyWumpus** [comment]
yeah it looks like the executable was missing, but the more recent log shows it there. Could you try restarting your deck?

**Comment by HankeMat** [comment]
> yeah it looks like the executable was missing, but the more recent log shows it there. Could you try restarting your deck?

Sorry for time delay, but I did restarted it more than once and nothing fixed it. Today I went on Steam Deck and Decky was back somehow.
