### ISSUE TITLE
[BUG] pre-release 2.10.6-pre1 causing lots of plugins to break

### ISSUE THREAD

**Issue by Localhorst86** [SteamDeckHomebrew/decky-loader#551]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

After updating to 2.10.6-pre1 earlier today, a lot of my installed plugins stopped working or started to behaving weirdly.

Here's a specific list of plugins that I am using and their issues introduced with the pre-release.

AutoFlatpacks:
- Buttons to check for updates and installing updates are grayed out and inaccessible
- Plugin displays a notification "Failed to load setting, skipping check for sanity" in random intervals

TabMaster:
- plugin will not list any tabs, neither hidden tabs, nor available ones

Animation Changer:
- will either not show any downloaded animations in it's dropdown menus at all, or
- will take a considerable time (10-30 seconds) to populate the dropdown menus with the animations (only 6 animations are installed)

Uninstalling decky-loader pre-release and reinstalling it did not fix the issues.
Reverting to 2.10.5 stable solves the above mentioned issues.

### Expected Behaviour

AutoFlatpacks:
- Buttons to check for updates and installing updates should be available
- Plugin should not throw error notifications "Failed to load setting, skipping check for sanity" in random intervals

TabMaster:
- plugin should show a list of available tabs, and a list of hidden ones

Animation Changer:
- should not fail or take a considerable amount of time show the installed animations (given a sane number of installed animations)

### SteamOS version

SteamOS 3.4.11 stable

### Selected Update Channel

Prerelease

### Logs

[deckylogs.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/13179244/deckylogs.txt)

**Comment by TrainDoctor** [comment]
Thank you for your detailed response. I am assigning the devs who worked on this to take a look asap.

**Comment by TrainDoctor** [comment]
@Localhorst86 can you also provide a list of plugins that are working without or only with minor issues? If none exist please let us know and provide a full list of plugins.

**Comment by Localhorst86** [comment]
@TrainDoctor 

Appart from the above mentioned plugins with their issues, this is a list of other plugins I have installed and wether or not they work correctly:

Shotty 0.0.1-1:
- seems to work without issues

Storage Cleaner 1.3.0
- seems to work fine, allthough it takes about a minute after booting the steam deck to actually list shader caches and compatdata

CSS Loader 2.0.1
- custom themes work as soon as the device boots, the CSS Loader shows "CSS Loader failed to initilaize, try reloading, and if that doesn't work, try restarting your deck." in the quicktab menua for about a minute after booting the deck. After that, the menu seems to work fine as well.

ProtonDB Badges 1.0.11
- seems to work fine

SteamgridDB 1.3.1
- seems to work fine

**Comment by Localhorst86** [comment]
Possibly related to the delays I mentioned for Storage Cleaner and CSS Loader, checking for Decky updates seems to hang during the first few minutes after booting the deck, as does trying to uninstall a plugin.

**Comment by TrainDoctor** [comment]
Resolved by latest pre-release, please confirm.

**Comment by marios8543** [comment]
Confirmed by OP on discord
