### ISSUE TITLE
[Request] Backup

### ISSUE THREAD

**Issue by Krutonium** [SteamDeckHomebrew/decky-loader#552]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

I would love it if Decky had the ability to back up all plugins and plugin data; so that you can quickly restore if you need to restore your deck for whatever reason.

### Further Description

Basically, I ran into an issue the other day that required me to factory reset my deck, and I wish I had a backup of all my plugins and settings. Having it zip them up and put them somewhere would be fantastic.

**Comment by PartyWumpus** [comment]
You can just zip up the ~/homebrew folder in desktop mode and you'll get everything. Considering how easy compressing a folder is in desktop mode, I think it's probably not worth implementing this.

**Comment by sanyer** [comment]
Yes, documenting this would be awesome.
