### ISSUE TITLE
[BUG] <title>plugin dont work in steamos 3.5.5

### ISSUE THREAD

**Issue by demontaxo** [SteamDeckHomebrew/decky-loader#563]
### Please confirm

- [X] I have searched existing issues
- [ ] This issue is not a duplicate of an existing one
- [ ] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [ ] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

vibrant deck dont change color
fantastic show -1337 rps

### Expected Behaviour

mmm

### SteamOS version

3.5.5

### Selected Update Channel

Stable

### Logs

file:///home/deck/deckylog.txt
[deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/13429245/deckylog.txt)

**Comment by RodoMa92** [comment]
This is the bug tracker for Decky Loader, not for the plugins. You can get support on our Discord server, in the dedicated sections for them. You can find a link to the discord server in the readme of this repo.

Closing this.
