### ISSUE TITLE
[BUG] Decky`s Icon doest show up.

### ISSUE THREAD

**Issue by HeavensFeelBad** [SteamDeckHomebrew/decky-loader#565]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

After System Update Decky`s icon doesnt show up. Tried Reinstallation and Complete wipe. Doesnt helps. Any Ideas?

### Expected Behaviour

to Show up

### SteamOS version

SteamOS 3.5.5

### Selected Update Channel

Stable

### Have you modified the read-only filesystem at any point?

No

### Logs

dfsd

**Comment by MrHappy** [comment]
Same on 3.5.7

**Comment by xfechx** [comment]
It is not working at the moment. I have tried everything without success..

**Comment by TrainDoctor** [comment]
> It is not working at the moment. I have tried everything without success..

Again, without logs I cannot help you @xfechx.

**Comment by EMERALD0874** [comment]
@xfechx - Please reboot your deck (if possible) when attempting to recreate the issue, then run `cd ~ && journalctl -b0  -u plugin_loader.service > deckylog.txt`. This will save the log file to `~` aka `/home/deck`. Please upload the file here.

**Comment by xfechx** [comment]
Here are the results from the log:

Dec 10 16:43:20 steamdeckoled systemd[1]: Started SteamDeck Plugin Loader.
Dec 10 16:43:20 steamdeckoled PluginLoader[962]: [loader][INFO]:
plugin_path: /home/deck/homebrew/plugins
Dec 10 16:43:20 steamdeckoled PluginLoader[962]: [loader][INFO]: import
plugins from /home/deck/homebrew/plugins
Dec 10 16:43:20 steamdeckoled PluginLoader[962]: [loader][INFO]: found
plugin: moondeck
Dec 10 16:43:20 steamdeckoled PluginLoader[962]: [loader][INFO]: Loaded
MoonDeck
Dec 10 16:43:20 steamdeckoled PluginLoader[962]: [loader][INFO]: found
plugin: decky-storage-cleaner
Dec 10 16:43:20 steamdeckoled PluginLoader[962]: [loader][INFO]: Loaded
Storage Cleaner
Dec 10 16:43:20 steamdeckoled PluginLoader[962]: [loader][INFO]: found
plugin: SDH-QuickLaunch
Dec 10 16:43:20 steamdeckoled PluginLoader[962]: [loader][INFO]: Loaded
Quick Launch
Dec 10 16:43:20 steamdeckoled PluginLoader[962]: [loader][INFO]: found
plugin: SDH-AudioLoader
Dec 10 16:43:20 steamdeckoled PluginLoader[962]: [loader][INFO]: Loaded
Audio Loader
Dec 10 16:43:20 steamdeckoled PluginLoader[962]: [loader][INFO]: found
plugin: decky-steamgriddb
Dec 10 16:43:20 steamdeckoled PluginLoader[962]: [loader][INFO]: Loaded
SteamGridDB
Dec 10 16:43:20 steamdeckoled PluginLoader[962]: [loader][INFO]: found
plugin: decky-recorder
Dec 10 16:43:21 steamdeckoled PluginLoader[962]: [loader][INFO]: Loaded
Decky Recorder
Dec 10 16:43:21 steamdeckoled PluginLoader[962]: [loader][INFO]: found
plugin: SDH-CssLoader
Dec 10 16:43:21 steamdeckoled PluginLoader[962]: [loader][INFO]: Loaded CSS
Loader
Dec 10 16:43:21 steamdeckoled PluginLoader[962]: [loader][INFO]: found
plugin: decky-autoflatpaks
Dec 10 16:43:21 steamdeckoled PluginLoader[962]: [loader][INFO]: Loaded
AutoFlatpaks
Dec 10 16:43:21 steamdeckoled PluginLoader[962]: [loader][INFO]: found
plugin: protondb-decky
Dec 10 16:43:21 steamdeckoled PluginLoader[962]: [loader][INFO]: Plugin
ProtonDB Badges is passive
Dec 10 16:43:21 steamdeckoled PluginLoader[962]: [loader][INFO]: Loaded
ProtonDB Badges
Dec 10 16:43:21 steamdeckoled PluginLoader[962]: [loader][INFO]: found
plugin: TabMaster
Dec 10 16:43:21 steamdeckoled PluginLoader[962]: [loader][INFO]: Loaded
TabMaster
Dec 10 16:43:21 steamdeckoled PluginLoader[962]: [loader][INFO]: found
plugin: vibrantDeck
Dec 10 16:43:21 steamdeckoled PluginLoader[962]: [loader][INFO]: Loaded
vibrantDeck
Dec 10 16:43:21 steamdeckoled PluginLoader[962]: [loader][INFO]: found
plugin: bash-shortcuts
Dec 10 16:43:21 steamdeckoled PluginLoader[962]: [loader][INFO]: Loaded
Bash Shortcuts
Dec 10 16:43:21 steamdeckoled PluginLoader[962]: [loader][INFO]: found
plugin: Steamback
Dec 10 16:43:21 steamdeckoled PluginLoader[962]: [loader][INFO]: Loaded
Steamback
Dec 10 16:43:21 steamdeckoled PluginLoader[962]: [loader][INFO]: found
plugin: PowerTools
Dec 10 16:43:21 steamdeckoled PluginLoader[962]: [loader][INFO]: Loaded
PowerTools
Dec 10 16:43:21 steamdeckoled PluginLoader[962]: [loader][INFO]: found
plugin: OpenGOAL
Dec 10 16:43:21 steamdeckoled PluginLoader[962]: [loader][INFO]: Loaded
OpenGOAL
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]:
Initializing Audio Loader...
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Finding sound packs...
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack Vampire Killer
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack Vampire Killer added
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack SMT3 Menu SFX
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack SMT3 Menu SFX added
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack GameCube Menu Music
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack GameCube Menu Music added
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack Cuphead Sound Effects
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack Cuphead Sound Effects added
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack PlayStation 5 Home Menu
Dec 10 16:43:21 steamdeckoled PluginLoader[1205]: chown: changing ownership
of '/home/deck/homebrew/logs/SDH-QuickLaunch/2023-12-10 16.43.21.log':
Operation not permitted
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack PlayStation 5 Home Menu added
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack PlayStation 4 Home Menu
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack PlayStation 4 Home Menu added
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack NieR Perfect YoRHa OS Sound FX
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack NieR Perfect YoRHa OS Sound FX added
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack Persona 5
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack Persona 5 added
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack PS4
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack PS4 added
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack Dreamcast UI SFX
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack Dreamcast UI SFX added
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack HL2SteamDeckUISounds
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack HL2SteamDeckUISounds added
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack Hip Shop
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack Hip Shop added
Dec 10 16:43:21 steamdeckoled PluginLoader[1211]: chown: changing ownership
of '/home/deck/homebrew/logs/SDH-QuickLaunch/2023-12-10 16.43.21.log':
Operation not permitted
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack Big Picture Mode
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack Big Picture Mode added
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack Undertale Sound Effects
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack Undertale Sound Effects added
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack Switch
Dec 10 16:43:21 steamdeckoled PluginLoader[1212]: chown: changing ownership
of '/home/deck/homebrew/logs/SDH-QuickLaunch/2023-12-10 16.43.21.log':
Operation not permitted
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack Switch added
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack PSO Menu Sounds
Dec 10 16:43:21 steamdeckoled PluginLoader[1208]: chown: changing ownership
of '/home/deck/homebrew/logs/SDH-QuickLaunch/2023-12-10 16.43.21.log':
Operation not permitted
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack PSO Menu Sounds added
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack Wii Menu Sounds
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack Wii Menu Sounds added
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack Second Life
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack Second Life added
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack 3DS Internet Settings
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack 3DS Internet Settings added
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack Nintendo GameCube Menu SFX
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack Nintendo GameCube Menu SFX added
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack Persona 4
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack Persona 4 added
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack PS2 System Sounds
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack PS2 System Sounds added
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack PSVita
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack PSVita added
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Analyzing sound pack It's Raining Somewhere Else
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Sound pack It's Raining Somewhere Else added
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Fetching config file at /home/deck/homebrew/sounds/config.json
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Found config file
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader - Config existing is True
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: Audio
Loader initialized.
Dec 10 16:43:21 steamdeckoled PluginLoader[1112]: [main][INFO]: [<_.Pack
object at 0x7fc883ca3fd0>, <_.Pack object at 0x7fc883ca3f70>, <_.Pack
object at 0x7fc883ca3e20>, <_.Pack object at 0x7fc883ca3e50>, <_.Pack
object at 0x7fc883ca3dc0>, <_.Pack object at 0x7fc883ca3df0>, <_.Pack
object at 0x7fc883ca3ee0>, <_.Pack object at 0x7fc883ca3eb0>, <_.Pack
object at 0x7fc883ca3d90>, <_.Pack object at 0x7fc883ca3d60>, <_.Pack
object at 0x7fc883ca3d30>, <_.Pack object at 0x7fc883ca3d00>, <_.Pack
object at 0x7fc883ca3cd0>, <_.Pack object at 0x7fc883ca3ca0>, <_.Pack
object at 0x7fc883ca3c70>, <_.Pack object at 0x7fc883ca3c40>, <_.Pack
object at 0x7fc883ca3c10>, <_.Pack object at 0x7fc883ca3be0>, <_.Pack
object at 0x7fc883ca3bb0>, <_.Pack object at 0x7fc883ca3af0>, <_.Pack
object at 0x7fc883ca3fa0>, <_.Pack object at 0x7fc883ca3970>, <_.Pack
object at 0x7fc883ca3940>, <_.Pack object at 0x7fc883ca3910>]
Dec 10 16:43:21 steamdeckoled PluginLoader[1223]: Logging to:
"/tmp/powertools.log"
Dec 10 16:43:21 steamdeckoled PluginLoader[1223]: Starting back-end
(powertools v1.4.0)
Dec 10 16:43:21 steamdeckoled PluginLoader[1223]: Current dir
`/home/deck/homebrew/services`
Dec 10 16:43:26 steamdeckoled PluginLoader[962]: [base_events][ERROR]: Task
exception was never retrieved
Dec 10 16:43:26 steamdeckoled PluginLoader[962]: future: <Task finished
name='Task-6' coro=<PluginManager.loader_reinjector() done, defined at
main.py:110> exception=Exception('/json did not return 200. Not
Authorized\n')>
Dec 10 16:43:26 steamdeckoled PluginLoader[962]: Traceback (most recent
call last):
Dec 10 16:43:26 steamdeckoled PluginLoader[962]:   File "main.py", line
117, in loader_reinjector
Dec 10 16:43:26 steamdeckoled PluginLoader[962]:   File "injector.py", line
405, in get_gamepadui_tab
Dec 10 16:43:26 steamdeckoled PluginLoader[962]:   File "injector.py", line
380, in get_tabs
Dec 10 16:43:26 steamdeckoled PluginLoader[962]: Exception: /json did not
return 200. Not Authorized
Dec 10 16:43:30 steamdeckoled PluginLoader[962]: [loader][INFO]: Hot reload
enabled

**Comment by AAGaming00** [comment]
Seems like there's something else running on port 8080

**Comment by xfechx** [comment]
I realised I had Syncthing service running on 8080. Now I have changed
Syncthing port to run on 8384 and decky is working fine.

Thanks for your help
