### ISSUE TITLE
[BUG] No icon showing up

### ISSUE THREAD

**Issue by Mouchoir** [SteamDeckHomebrew/decky-loader#568]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

Hello,

I tried to install decky but after a successful installation, I do not have the plug icon in the ... menu 
I have tried to install the pre release version as suggested but it doesnt change anything. I have restarted my device.

I do not use Syncthing

I know that Decky is installed because when I run it from my desktop again, a new uninstall option has appeared
Could anyone help me with this issue ?
Thanks

### Expected Behaviour

"plug icon" should appear when i press the ... button in game mode

### SteamOS version

SteamOS 3.5.7

### Selected Update Channel

Stable

### Logs

[deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/13655088/deckylog.txt)
[deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/13655132/deckylog.txt)

**Comment by plrusek** [comment]
happened to me too just now but on the beta update channel for steamos, you said you are on stable though. i reverted back to stable and it started working again.

**Comment by BlueDawnxx** [comment]
having the same problem just now. im on beta. Trying to revert. Reporting back then

**Comment by BlueDawnxx** [comment]
after installing the stable version it instantly appeared

**Comment by TrainDoctor** [comment]
For everyone posting here, please switch to desktop mode and run the installer for preview decky, then reboot to game mode and run this: ``cd ~ && journalctl -b0  -u plugin_loader.service > deckylog.txt`` afterwards in desktop mode/or via ssh so we can get more detailed logs as the preview install of decky provides more detailed logging. Thanks in advance.

**Comment by Intoxicus** [comment]
Dec 12 19:52:34 steamdeck systemd[1]: Started SteamDeck Plugin Loader.
Dec 12 19:52:34 steamdeck PluginLoader[979]: [selector_events][DEBUG]: Using selector: EpollSelector
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: plugin_path: /home/deck/homebrew/plugins
Dec 12 19:52:34 steamdeck PluginLoader[979]: [updater][DEBUG]: current branch: 1
Dec 12 19:52:34 steamdeck PluginLoader[979]: [main][DEBUG]: Loading plugins
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: import plugins from /home/deck/homebrew/plugins
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: found plugin: decky-terminal
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: Loaded Decky Terminal
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: found plugin: VolumeMixer-decky
Dec 12 19:52:34 steamdeck PluginLoader[1016]: [selector_events][DEBUG]: Using selector: EpollSelector
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: Loaded Volume Mixer
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: found plugin: Bluetooth
Dec 12 19:52:34 steamdeck PluginLoader[1017]: [selector_events][DEBUG]: Using selector: EpollSelector
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: Loaded Bluetooth
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: found plugin: decky-storage-cleaner
Dec 12 19:52:34 steamdeck PluginLoader[1018]: [selector_events][DEBUG]: Using selector: EpollSelector
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: Loaded Storage Cleaner
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: found plugin: decky-recorder
Dec 12 19:52:34 steamdeck PluginLoader[1019]: [selector_events][DEBUG]: Using selector: EpollSelector
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: Loaded Decky Recorder
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: found plugin: DeckyFileServer
Dec 12 19:52:34 steamdeck PluginLoader[1021]: [selector_events][DEBUG]: Using selector: EpollSelector
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: Loaded DeckyFileServer
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: found plugin: decky-syncthing
Dec 12 19:52:34 steamdeck PluginLoader[1023]: [selector_events][DEBUG]: Using selector: EpollSelector
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: Loaded Syncthing
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: found plugin: DeckMTP
Dec 12 19:52:34 steamdeck PluginLoader[1025]: [selector_events][DEBUG]: Using selector: EpollSelector
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: Loaded DeckMTP
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: found plugin: protondb-decky
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: Plugin ProtonDB Badges is passive
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: Loaded ProtonDB Badges
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: found plugin: TunnelDeck
Dec 12 19:52:34 steamdeck PluginLoader[1029]: [selector_events][DEBUG]: Using selector: EpollSelector
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: Loaded TunnelDeck
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: found plugin: ControllerTools
Dec 12 19:52:34 steamdeck PluginLoader[1033]: [selector_events][DEBUG]: Using selector: EpollSelector
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: Loaded Controller Tools
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: found plugin: TabMaster
Dec 12 19:52:34 steamdeck PluginLoader[1038]: [selector_events][DEBUG]: Using selector: EpollSelector
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: Loaded TabMaster
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: found plugin: MusicControl
Dec 12 19:52:34 steamdeck PluginLoader[1043]: [selector_events][DEBUG]: Using selector: EpollSelector
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: Loaded MusicControl
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: found plugin: volume-boost
Dec 12 19:52:34 steamdeck PluginLoader[1047]: [selector_events][DEBUG]: Using selector: EpollSelector
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: Loaded Volume Boost
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: found plugin: PowerTools
Dec 12 19:52:34 steamdeck PluginLoader[1052]: [selector_events][DEBUG]: Using selector: EpollSelector
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: Loaded PowerTools
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: found plugin: MangoPeel
Dec 12 19:52:34 steamdeck PluginLoader[1060]: [selector_events][DEBUG]: Using selector: EpollSelector
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: Loaded MangoPeel
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: found plugin: SDH-PlayTime
Dec 12 19:52:34 steamdeck PluginLoader[1066]: [selector_events][DEBUG]: Using selector: EpollSelector
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: Loaded PlayTime
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: found plugin: steam-deck-battery-tracker
Dec 12 19:52:34 steamdeck PluginLoader[1077]: [selector_events][DEBUG]: Using selector: EpollSelector
Dec 12 19:52:34 steamdeck PluginLoader[979]: [loader][INFO]: Loaded Battery Tracker
Dec 12 19:52:34 steamdeck PluginLoader[1081]: [selector_events][DEBUG]: Using selector: EpollSelector
Dec 12 19:52:34 steamdeck PluginLoader[979]: [injector][DEBUG]: Steam isn't available yet. Wait for a moment...
Dec 12 19:52:34 steamdeck PluginLoader[1047]: [MusicControl] UID: 1000
Dec 12 19:52:34 steamdeck PluginLoader[1131]: 02:52:34 [INFO] Using settings file: /home/deck/homebrew/settings/controller-tools.json
Dec 12 19:52:34 steamdeck PluginLoader[1131]: 02:52:34 [INFO] Logging level: Info
Dec 12 19:52:34 steamdeck PluginLoader[1131]: 02:52:34 [INFO] Listening on 127.0.0.1:33220
Dec 12 19:52:34 steamdeck PluginLoader[1133]: Logging to: "/tmp/powertools.log"
Dec 12 19:52:34 steamdeck PluginLoader[1133]: Starting back-end (powertools v1.4.0)
Dec 12 19:52:34 steamdeck PluginLoader[1133]: Current dir `/home/deck/homebrew/services`
Dec 12 19:52:44 steamdeck PluginLoader[979]: [loader][INFO]: Hot reload enabled
Dec 12 19:52:49 steamdeck PluginLoader[979]: [main][DEBUG]: Couldn't find GamepadUI tab, waiting...
Dec 12 19:52:54 steamdeck PluginLoader[979]: [main][INFO]: Loading Decky frontend!
Dec 12 19:52:54 steamdeck PluginLoader[979]: [main][DEBUG]: Page event: None
Dec 12 19:53:04 steamdeck PluginLoader[979]: [updater][DEBUG]: checking for updates
Dec 12 19:53:04 steamdeck PluginLoader[979]: [updater][DEBUG]: current branch: 1
Dec 12 19:53:04 steamdeck PluginLoader[979]: [updater][DEBUG]: release type: pre-release
Dec 12 19:53:04 steamdeck PluginLoader[979]: [updater][DEBUG]: determining release type to find, branch is 1
Dec 12 19:53:04 steamdeck PluginLoader[979]: [updater][DEBUG]: release type: pre-release
Dec 12 19:53:04 steamdeck PluginLoader[979]: [updater][INFO]: Updated remote version information
Dec 12 19:54:12 steamdeck PluginLoader[979]: [main][DEBUG]: Page event: Page.windowOpen

**Comment by TrainDoctor** [comment]
Please try out new pre-release of Decky, should be working.

**Comment by 4RH1T3CT0R7** [comment]
The same problem

**Comment by TrainDoctor** [comment]
> The same problem

Please try the latest pre-release. The issue is resolved.

**Comment by 4RH1T3CT0R7** [comment]
> > The same problem
> 
> Please try the latest pre-release. The issue is resolved.

No

**Comment by PartyWumpus** [comment]
"No" is not very helpful. If you've just installed decky and the icon isn't showing up, check the [common issues](https://github.com/SteamDeckHomebrew/decky-loader?tab=readme-ov-file#-common-issues) section and try downloading the prerelease. If it's just broken after an update, download the decky prerelease.

**Comment by GarlicRot** [comment]
Thank you, updating to the pre-release fixed it for me.

**Comment by 4RH1T3CT0R7** [comment]
> "No" is not very helpful. If you've just installed decky and the icon isn't showing up, check the [common issues](https://github.com/SteamDeckHomebrew/decky-loader?tab=readme-ov-file#-common-issues) section and try downloading the prerelease. If it's just broken after an update, download the decky prerelease.

Pre-release version works well, thanks

**Comment by Mouchoir** [comment]
Installing the new pre-release update did solve it !
Well done team

**Comment by gaker19sc** [comment]
I still have this issue

**Comment by NathanielTat** [comment]
Same issue, stable channel on the steam deck stable channel if deckyloader fresh install everything and still not showing in the game mode

**Comment by TrainDoctor** [comment]
This issue is stale and not relevant to the current issues being experienced. Please file a new issue with proper logs, detailed instructions to recreate the issue etc.
