### ISSUE TITLE
Support for BazziteOS (or a potential workaround)

### ISSUE THREAD

**Issue by FireXDragon007** [SteamDeckHomebrew/decky-loader#569]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

On BazziteOS (SteamOS Clone) the Syncthing plugin throws the error: "Failed to fetch "
With no useful information in the process log

Maybe an update or a workaround to get the plugin working

**Comment by TrainDoctor** [comment]
> ### Please confirm
> 
>     * [x]  I have searched existing issues
> 
>     * [x]  This issue is not a duplicate of an existing one
> 
>     * [x]  This is not a request for a plugin
> 
> 
> ### Feature Request Description
> 
> On BazziteOS (SteamOS Clone) the Syncthing plugin throws the error: "Failed to fetch " With no useful information in the process log
> 
> Maybe an update or a workaround to get the plugin working
> ### Further Description
> 
> _No response_

This is a feature request for a plugin, not for decky loader. Please file it there.
