### ISSUE TITLE
Decky Loader Store not loading 

### ISSUE THREAD

**Issue by PoochMasterson** [SteamDeckHomebrew/decky-loader#574]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

When I go to the plugins option on my steam deck and click the store icon on Decky Loader it loads infinitely, I am not on the beta and I have made sure everything is correct, also I have developer mode turned on, please help 

https://github.com/SteamDeckHomebrew/decky-loader/assets/155321220/e54f9082-8537-4947-bc81-535649264bf5

### Expected Behaviour

It should load into the marketplace 

### SteamOS version

Steam OS 3.5.7 Stable 

### Selected Update Channel

Stable

### Logs

I don’t know how to do that

**Comment by AAGaming00** [comment]
Everything is fine on our end, this is likely an issue with your network. Perhaps try a different DNS.

**Comment by PartyWumpus** [comment]
just tested on my device and I'm getting the same issue, with a CORS error in the js console. Probably need to clear cloudflare cache I guess?

**Comment by AAGaming00** [comment]
lol what apparently it's not serving cors headers

**Comment by AAGaming00** [comment]
nevermind it is I was testing wrong

**Comment by Kyguy0** [comment]
I had this problem after updating from a very old decky version and not rebooting. Rebooting fixed it.
