### ISSUE TITLE
[BUG] decky loaded not working anymore 

### ISSUE THREAD

**Issue by L0WR1D3Rz** [SteamDeckHomebrew/decky-loader#583]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [ ] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

Hi. Since he last steam deck update the decky loader stable version doesn't work anymore. Is there a fix/update in the works? 

### Expected Behaviour

Decky should work and appear in the menu 

### SteamOS version

Latest Main Channel version 

### Selected Update Channel

Beta

### Have you modified the read-only filesystem at any point?

No

### Logs

Don't have the log yet

**Comment by AAGaming00** [comment]
Are you using stable or prerelease decky? Your description is inconsistent.

**Comment by L0WR1D3Rz** [comment]
My description clarifies pretty well which decky loader version I'm using

**Comment by PartyWumpus** [comment]
stable decky does not always work on the beta steam client. try switching to prerelease decky.

**Comment by L0WR1D3Rz** [comment]
> stable decky does not always work on the beta steam client. try switching to prerelease decky.

Thanks will try

**Comment by CookiePolicyEnforcer** [comment]
I can confirm that the prerelease version of decky works

**Comment by RowanSkie** [comment]
The current version of SteamOS Beta doesn't work correctly right now with the latest prerelease Decky Loader. I just can't see the option to access it, but the other stuff I installed is still on.

**Comment by IceStar3030** [comment]
I tried on SteamOS 3.5.7 stable and beta, with Decky stable and prerelease. Decky shows up on neither. I was only able to access Decky once when there was an update for it. Apparently the plugins still work though.

**Comment by craigz** [comment]
i'm having the same issue. 

i've got 3 plugins that currently show errors, and when the steam deck boots, or steam restarts, i get 3 notifications, 1 from each. 

yesterday and several days prior, i was able to access decky-loader via the QAM button as usual, and the plugins with errors showed `!` icons.  

today after the latest steamOS preview update (3.5.15/20240212.1), i still see the notifications on boot/steam startup, however there is no decky-loader icon in the QAM. i can see that CSS Loader is up and running. 

i just checked the `plugin_loader.service` status; it is up and running, it's just not displaying it's icon.  

just now upon restarting steam, i got an update notification (Prerelease v2.11.0-pre2).  tapping the notification  opened decky loader and i was able to install the update. 

after restarting steam however, the notifications appear (and are un-clickable, i tried!) and the icon remains missing from the QAM.

**Comment by TrainDoctor** [comment]
> I tried on SteamOS 3.5.7 stable and beta, with Decky stable and prerelease. Decky shows up on neither. I was only able to access Decky once when there was an update for it. Apparently the plugins still work though.

I am currently running SteamOS Stable 3.5.7 with Pre-release Decky. All of my plugins works work atm. Please submit logs using this ``cd ~ && journalctl -b0 -u plugin_loader.service > deckylogs.txt`` and upload the resulting file which can be found at ``/home/deck/``.

**Comment by TrainDoctor** [comment]
> i've got 3 plugins that currently show errors, and when the steam deck boots, or steam restarts, i get 3 notifications, 1 from each.

Please make sure to submit issues on those developers pages.

**Comment by craigz** [comment]
> Please make sure to submit issues on those developers pages.

i plan on doing so. after this current issue is resolved and i can access decky-loader again ;)

**Comment by dev0T** [comment]
Decky loader stopped working on both of our steam decks

**Comment by AlphaCraft9658** [comment]
My plugins fail loading. Reinstalling Decky Loader didn't seem to help.

**Comment by nascentt** [comment]
mine is broken, not really sure if i'm meant to create a new issue or use this despite it potentially being a duplicate?
decky loader was missing from the menu, so i re-ran the installer in desktop mode, and now it shows again, but none of the plugins are doing anything.  I tried using the "reinstall" plugin option for a few of them, no change.
It's like decky loader isn't running despite now being able to see the menu.

**Comment by AndehX** [comment]
What's going on with this?  The Steam family sharing just came out, but it only works on steamos beta.  Need Decky Loader fixed asap really.

**Comment by TrainDoctor** [comment]
> What's going on with this? The Steam family sharing just came out, but it only works on steamos beta. Need Decky Loader fixed asap really.

Please understand that this is a volunteer only project and adjust your expectations accordingly. We will make you aware when we have a fix in the pipeline. Thanks.

**Comment by krompus** [comment]
I'm on SteamOS Stable, and Decky Stable, my plugins seem to still be working correctly but I'm no longer seeing the Decky icon in the right panel, so I can't control anything. I tried downloading Decky stable again and ran the desktop file but nothing happens. Not sure how to proceed.

**Comment by L0WR1D3Rz** [comment]
Just wanted to know whether there is any update on this. I understand it's a passion project, just wonder if the devs are working on getting it to work with the latest beta.

**Comment by PartyWumpus** [comment]
> Just wanted to know whether there is any update on this. I understand it's a passion project, just wonder if the devs are working on getting it to work with the latest beta.

Nobody is currently working on a fix. For now I'd just turn decky off, do the stuff you want in the beta, and then return to a normal client branch and turn decky back on.

**Comment by L0WR1D3Rz** [comment]
Thank you for the quick response, appreciate it. Unfortunately I need the family feature which is only available in the beta so for now I'll remove decky and hope for an updated version in the near future!

**Comment by AlphaCraft9658** [comment]
> > Just wanted to know whether there is any update on this. I understand it's a passion project, just wonder if the devs are working on getting it to work with the latest beta.
> 
> Nobody is currently working on a fix. For now I'd just turn decky off, do the stuff you want in the beta, and then return to a normal client branch and turn decky back on.

I am currently on the stable branch of both steam and decky, but the plugins fail to load, with notifications appearing telling me they did. Even accessing the decky settings is not possible, as it's not shown. I don't know why this is happening. Other people are running it fine. I already reinstalled decky, but haven't wiped it, as I want to keep my plugins and configs. Do you have an idea of what could be going on and what I could try to fix it? If not, that's fine. I really appreciate the time and effort you put into this project.

**Comment by PartyWumpus** [comment]
> I am currently on the stable branch of both steam and decky, but the plugins fail to load, with notifications appearing telling me they did. Even accessing the decky settings is not possible, as it's not shown. I don't know why this is happening. Other people are running it fine. I already reinstalled decky, but haven't wiped it, as I want to keep my plugins and configs. Do you have an idea of what could be going on and what I could try to fix it? If not, that's fine. I really appreciate the time and effort you put into this project!

On stable steam!? What do you mean by the settings not being shown, is it that they don't load or that decky isn't there?

**Comment by AlphaCraft9658** [comment]
> > I am currently on the stable branch of both steam and decky, but the plugins fail to load, with notifications appearing telling me they did. Even accessing the decky settings is not possible, as it's not shown. I don't know why this is happening. Other people are running it fine. I already reinstalled decky, but haven't wiped it, as I want to keep my plugins and configs. Do you have an idea of what could be going on and what I could try to fix it? If not, that's fine. I really appreciate the time and effort you put into this project!
> 
> On stable steam!? What do you mean by the settings not being shown, is it that they don't load or that decky isn't there? Edit: also, logs might be useful: Please submit logs using this cd ~ && journalctl -b0 -u plugin_loader.service > deckylogs.txt and upload the resulting file which can be found at /home/deck/

I am sorry. It was actually different from what I could remember. In fact, the decky menu is accessible, but a majority of plugins didn't load successfully. Now I updated the plugins and a majority of them loads. Only DeckFAQs or what it was called doesn't load. Here is the [log](https://github.com/SteamDeckHomebrew/decky-loader/files/14937558/deckylogs.txt), so that we could maybe find the cause of the problem with that last plugin. My mistake.

**Comment by PartyWumpus** [comment]
> I am sorry. It was actually different from what I could remember. In fact, the decky menu is accessible, but a majority of plugins didn't load successfully.

Nah I imagine the decky backend crashed from one of the broken plugins which makes the settings menu break, and that's what you remembered. deckfaqs issue is known and [the fix is going onto the testing store soon](https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/594)
good to have your issue fixed either way :)

**Comment by vladventura** [comment]
My issue was that I had a service running already on port 8080 (syncthing), and decky was unable to hit the /json endpoint. If you want me to upload the logfile let me know, I'm just not at home currently. I changed the syncthing ports, uninstalled and reinstalled decky and voilà, the icon showed up on game mode qam.

On desktop mode, open a browser and go to localhost:8080. You should see a page with the title cef remote debugging, if not, then there's a service running on that port already.

I think decky should check that 8080 is not taken already. When I get back home I'll try and take a look how much it would take. Hope this helps some else!

**Comment by TrainDoctor** [comment]
Stale issue.

**Comment by L0WR1D3Rz** [comment]
What does stale issue mean?
Angelo Karaiannis
Mob: +41 79 278 00 25
email: ***@***.***
