### ISSUE TITLE
[BUG]  Decky Loader can not  (re)install or uninstall

### ISSUE THREAD

**Issue by Roromari** [SteamDeckHomebrew/decky-loader#593]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Decky icon disappeared sometime ago, so i tried to do an reinstall but failed.Both stable and prerelease showed the same error.
 

        Using the fallback 'C' locale.
[sudo] password for deck: [sudo] password for deck:
        Using the fallback 'C' locale.

        Using the fallback 'C' locale.

        Using the fallback 'C' locale.

chmod: cannot access '/home/deck/homebrew/services/PluginLoader': No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   422  100   422    0     0     66      0  0:00:06  0:00:06 --:--:--   112
Created symlink /etc/systemd/system/multi-user.target.wants/plugin_loader.service → /etc/systemd/system/plugin_loader.service.
chown: cannot access '/home/deck/homebrew/services/*': No such file or directory

### Tried uninstall also failed

(deck@steamdeck ~)$ curl -L https://github.com/SteamDeckHomebrew/decky-installer/releases/latest/download/uninstall.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   778  100   778    0     0    362      0  0:00:02  0:00:02 --:--:--     0
[sudo] password for deck:
Uninstalling Steam Deck Plugin Loader...
Removed "/etc/systemd/system/multi-user.target.wants/plugin_loader.service".
rm: cannot remove '/home/deck/homebrew/services/PluginLoader': No such file or directory
(1)(deck@steamdeck ~)$

### Expected Behaviour

working？

### SteamOS version

3.5.17

### Selected Update Channel

Prerelease

### Have you modified the read-only filesystem at any point?

can't remember

### Backend Logs

[deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/14490724/deckylog.txt)

### Frontend Logs

[cef_log.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/14490779/cef_log.txt)

**Comment by cjameslynn** [comment]
same issue

**Comment by zhouLife** [comment]
same issue

**Comment by shurikis** [comment]
same issue
