### ISSUE TITLE
[Request] Will Decky Loader work on SteamOS, Ubuntu, and/or Linux Mint.

### ISSUE THREAD

**Issue by SamBox436** [SteamDeckHomebrew/decky-loader#594]
### Please confirm

- [ ] I have searched existing issues
- [ ] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

I was going to use Decky Loader on Windows, but that is incompatible. So I wonder, what about SteamOS, and Linux? Anything new?

### Further Description

Support for Ubuntu, Desktop SteamOS, and Linux Mint

**Comment by TrainDoctor** [comment]
Decky already works on most modern Linux distros but is not tested against them. Only against SteamOS that ships on the Steam Deck. Thanks.
