### ISSUE TITLE
[Request] plugin install progress

### ISSUE THREAD

**Issue by joaociocca** [SteamDeckHomebrew/decky-loader#595]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

I'm a new Decky Loader user, but already long time Steam and Linux user. It would be nice to get any kind of progress bar/indicator on the plugin install screen, as it is now I have no idea if it's working, if it's stuck with some problem, etc... I mean, I've been watching the "Install Bluetooth" with the button saying "Installing" for some 20 minutes by now.

**Comment by cjameslynn** [comment]
same

**Comment by DemonicQuasar** [comment]
Hi, I'd like to contribute to this, I've never contributed to a project on github so I'm not sure if I should as for permission or what. Should I?

**Comment by joaociocca** [comment]
> Hi, I'd like to contribute to this, I've never contributed to a project on github so I'm not sure if I should as for permission or what. Should I?

You should read the wiki https://wiki.deckbrew.xyz/en/loader-dev/development

**Comment by joaociocca** [comment]
oh look, it took 10 minutes for Bluetooth plugin to update...

```
Apr 22 00:07:40 steamdeck PluginLoader[1125]: [browser][INFO]: Installing Bluetooth from URL (Version: 2.2.0)
Apr 22 00:11:59 steamdeck PluginLoader[1125]: [browser][INFO]: Incrementing installs for Bluetooth from URL https://plugins.deckbrew.xyz/plugins (version 2.2.0)
Apr 22 00:16:19 steamdeck PluginLoader[1125]: [browser][INFO]: uninstalling Bluetooth
Apr 22 00:16:19 steamdeck PluginLoader[1125]: [browser][INFO]:  at dir /home/deck/homebrew/plugins/Bluetooth
Apr 22 00:16:19 steamdeck PluginLoader[1125]: [browser][INFO]: Installed Bluetooth (Version: 2.2.0)
```

Got that from `journalctl`, but on the user frontend on the Deck, the only thing was the "updating" popup, with the grayed out button. I was almost restarting the Deck :rofl:

**Comment by TrainDoctor** [comment]
This was completed not to long ago!

**Comment by joaociocca** [comment]
oh yeah, I actually noticed it yesterday and forgot to come here congratulate on the implementation! it's really awesome now <3
