### ISSUE TITLE
[ISSUE] Can't uninstall failing plugin, gaming mode broken

### ISSUE THREAD

**Issue by aanze** [SteamDeckHomebrew/decky-loader#596]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

Gaming mode on my Nobara distro stopped being able to run after updating a plugin.
Since I can't get back to gaming mode, I can't uninstall the plugin either.
Is there a folder where I can manually remove the faulty plugin ?

### Expected Behaviour

There should be a way to manually delete a plugin without using decky loader interface in case it can't be accessed.

### SteamOS version

Nobara v39

### Selected Update Channel

Stable

### Backend Logs

None

### Frontend Logs

None

**Comment by PartyWumpus** [comment]
All decky data is installed in `~/homebrew`, plugins are in `~/homebrew/plugins` you can just delete it there.
