### ISSUE TITLE
[BUG] Decky is broken on latest beta client.

### ISSUE THREAD

**Issue by PartyWumpus** [SteamDeckHomebrew/decky-loader#597]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [ ] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

Opening the decky tab shows a screen wide error. "TypeError: Cannot read properties of undefined (reading 'Title')". The line with the error is `return (window.SP_REACT.createElement(Focusable, { style: titleStyles, className: staticClasses.Title },`. Something is up with the staticClasses, they appear to not be defined. I don't have time to look further into it right now.

Also the toaster might be broken again. Not 100% sure.

### SteamOS version

Client version 1709920887 (mar 7)

### Selected Update Channel

Prerelease

### Backend Logs

not relevant

### Frontend Logs

not relevant

**Comment by sickhate** [comment]
Even on stable steam ok is broken

**Comment by Zodiaksl** [comment]
Can confirm.

Also on latest BETA. Tried going back to Stable, pre-release, uninstalling, reinsitalling, etc.

**Comment by Lordmau5** [comment]
Adding onto this, one of the plug-ins I have installed (I assume a theme) is preventing me from opening a view of a game

```Error Reference: Shared SteamUI_8751946_f71b1e5c8d53b3f1

Cannot read properties of undefined (reading 'InnerContainer')```

**Comment by PartyWumpus** [comment]
The problem has been found, valve has renamed most of the CSS classes in the entire UI. Shouldn't be too hard to work around.

**Comment by spamsgood** [comment]
It's also broken preview. It's so broken for me I can't even launch games because when i select any game this is what I get. ![image](https://github.com/SteamDeckHomebrew/decky-loader/assets/28077404/a0b61b66-05a6-4445-b40c-b2d94675ae0c)

**Comment by ShadowMonster99** [comment]
upvote this forum post:
https://steamcommunity.com/groups/SteamClientBeta/discussions/3/4298194722189670859/

Steam is making changes that will affect mods like this.

**Comment by AndehX** [comment]
any idea how long this will take to fix?

**Comment by zcoop98** [comment]
> upvote this forum post:
> 
> https://steamcommunity.com/groups/SteamClientBeta/discussions/3/4298194722189670859/
> 
> 
> 
> Steam is making changes that will affect mods like this. 


Staff [replied to that thread](https://steamcommunity.com/groups/SteamClientBeta/discussions/3/4298194722189670859/#c4298194722190450222):

> **toms**   _13 hours ago_  
> I want to clarify an aspect of what has changed: classes are not being randomized every update. These classes have all changed in the most recent beta update, because of the changes to classname generation, but there are not currently any plans to change them all again in future updates. Of course, there is no guarantee that any given class will remain the same between updates, but this has always been the case.

**Comment by sickhate** [comment]
I cant wait for this to be fixed. These plugins are awesome

**Comment by PartyWumpus** [comment]
For now I'd just switch to the stable client.

**Comment by PartyWumpus** [comment]
Commit https://github.com/SteamDeckHomebrew/decky-loader/commit/4a7e9a5f3dc8fa1ab4789ac8396b030d72e1facc should fix this. Try updating to the newest prerelease.

**Comment by Zodiaksl** [comment]
> Commit [4a7e9a5](https://github.com/SteamDeckHomebrew/decky-loader/commit/4a7e9a5f3dc8fa1ab4789ac8396b030d72e1facc) should fix this. Try updating to the newest prerelease.

How does one download this in Desktop mode?

**Comment by PartyWumpus** [comment]
> How does one download this in Desktop mode?

Rerun the installer script and select "update to the latest prerelease", can be downloaded from the big download button on [this repo's readme page](https://github.com/SteamDeckHomebrew/decky-loader)

**Comment by Zodiaksl** [comment]
Updated to v2.12.0-pre1

Decky is now accessible from Game mode. However, I get errors for every single plugin trying to load.

**Comment by d3m3vilurr** [comment]
> Still on latest SteamOS Beta Channel, Updated to v2.12.0-pre1
> 
> Decky is now accessible from Game mode. However, I get errors for every single plugin trying to load.

plugins also have to update DFL to 3.25

**Comment by sickhate** [comment]
Yeah still some broken here on beta as well

**Comment by HugLifeTiZ** [comment]
Still *some* broken here? More like *most,* for me. ControllerTools, Shotty, ProtonDB Badges, SteamGridDB, and more very useful plugins are now broken, and their maintainers have to be the ones to perform updates in order to not be broken? Can Decky do anything to future-proof against this sort of thing?

**Comment by TrainDoctor** [comment]
> Still _some_ broken here? More like _most,_ for me. ControllerTools, Shotty, ProtonDB Badges, SteamGridDB, and more very useful plugins are now broken, and their maintainers have to be the ones to perform updates in order to not be broken? Can Decky do anything to future-proof against this sort of thing?

We already have in terms of frontends, it's called global DFL. Plugin authors can reference the current plugin template.
