### ISSUE TITLE
[BUG] Decky causes Freeze on StartUp Animation

### ISSUE THREAD

**Issue by MJG9770** [SteamDeckHomebrew/decky-loader#598]
### Please confirm

- [x] I have searched existing issues
- [x] This issue is not a duplicate of an existing one
- [x] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [x] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

Steps to reproduce the issue:
1. Power On Steam Deck without Decky installed: all good
2. Go in Game Menu via "Steam" button to Power "On/Off"
3. Choose "Switch to Desktop"
4. Download from decky.xyz with Firefox or Chrome (both tested) the installation file
5. Draw the installation file to desktop
6. install it, agreeing to set admin password to "Decky!"
7. Go back to Game Mode
8. Restart the Deck via "Steam" button "On/Off", choose "Restart"
9. Now the Start Up animation freezes in the last third
10. Click any button or wait for 1-2 minutes until automatically is back in Game Menu
11. Click "Steam" button, go to "On/Off", choose "Switch to Desktop"
12. Click the same installation file, choose "deinstall decky"
13. Go back to "Game Mode"
14. Click "Steam" button, restart the deck
15. Start Up animation runs as expected without freezing

Pls see my self captured video, since it is 56 Megabyte I uploaded it to my googledrive for you:
https://drive.google.com/file/d/17yxg5O80hveoFJhN6pcRjwGmTCzWHK_S/view?usp=sharing

Let me know if you need it somehow different to look at it.

It doesn't matter which startup animation you choose or whether you have installed any plugin via decky. It is the DeckyLoader itself.

### Expected Behaviour

No freeze during start up animation.

I tested this procedure three times and even restored my Steam Deck to factory settings. It is happening again and again.
With Decky deinstalled all works fine.

### SteamOS version

SteamOS 3.5.7 Stable

### Selected Update Channel

Stable

### Have you modified the read-only filesystem at any point?

No.

### Backend Logs

[deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/14570091/deckylog.txt)

### Frontend Logs

[cef_log.previous.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/14570090/cef_log.previous.txt)

**Comment by EASK8ER52** [comment]
Having the same exact issue. Just tried a full uninstall deleting all configs and without decky it boots into gaming mode quickly like it should. Once I redownload decky I got the same issue, 2 minute freeze starting gaming mode or even just restarting steam from within gaming mode.

Really annoying cause I decky and it's plugins are just so useful. I'm on the OLED if that matters, haven't messed with anything. Stable normal steam OS.

**Comment by MJG9770** [comment]
I hope the devs read this and fix the issue - any update?

**Comment by AAGaming00** [comment]
can't reproduce

**Comment by MJG9770** [comment]
then pls see the logs what it can be, more than happy to follow any instructions what could fix it. My Deck was new and did not do anything else to it.

**Comment by EASK8ER52** [comment]
If y'all want I can send a video of it happening when I get home. Also I can send a list if the plugins I'm using

**Comment by ThisNekoGuy** [comment]
I've also been having this issue but, for me, it started as soon as I rebooted after [disabling HTTP2](https://wiki.archlinux.org/title/Steam#Disable_HTTP2_for_faster_downloads) to because I was getting less than 1MB/s downloads.
I get startup hangs ever since but I'm not sure if it was just a coincidence since it happens even if my wifi is off.

**Comment by AAGaming00** [comment]
it's likely related to you disabling http2. try re-enabling it.

**Comment by ThisNekoGuy** [comment]
I was about to do that just now, but I remembered that Decky Loader broke (doesn't load) when I updated the Steam client to the (Family Sharing) beta yesterday. :/

**Comment by AAGaming00** [comment]
it should work on prerelease

**Comment by ThisNekoGuy** [comment]
Updating to the prerelease made Decky work again but changing the HTTP setting didn't make any difference for improving the startup time.
Tested with a reboot afterward.

**Comment by TrainDoctor** [comment]
Stale issue.

**Comment by VRArt1** [comment]
Experiencing this issue.

**Comment by TrainDoctor** [comment]
If you are experiencing an issue long after the original was resolved, please file a new issue with logs.
