### ISSUE TITLE
[BUG] Decky Loader causes Baldur's Gate 3 to crash shortly after launch

### ISSUE THREAD

**Issue by CobaltChris** [SteamDeckHomebrew/decky-loader#599]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

These are the steps to reproduce for MY setup, but I've heard others claim this is relevant to the Steam Version as well
One addition to this report. After updating Decky to latest stable and SteamOS to 3.5.17, the issue persists.

1. Install Bauldur's Gate 3 on Heroic Games Launcher (from GOG) with default settings
2. Launch through either Desktop or Gaming Mode (with `--skip-launcher -dx11` arguments)
3. If the bug occurs, the game will launch with no audio and then crash upon or shortly after reaching the loading screen (tapping the screen expedites the process)
4. Uninstall Decky Loader
5. Reboot
6. Launch BG3 again
7. Game no longer crashes

Current installed Plugins:
AutoFlatpaks - 1.6.6
Pause Games - 0.4.2-1
Discord Status - 1.1.0-1
ProtonDB Badges - 1.0.12-1
Controller Tools - 1.1.2-1
MusicControl - 1.1.4-1
Shotty - 0.0.1-1
Storage Cleaner - 1.3.1
System Toolbox - 1.0.2-1
Quick Launch - 1.2.0
Emuachievements - 2.0.2-1
Bluetooth - 2.0.2-1
PowerTools - 1.4.0-1
AutoSuspend - 2.1.0
AudioLoader - 1.5.1-1
TabMaster - 2.4.1
Decky Cloud Save - 1.3.5
SteamGridDB - 1.3.3-1
DeckyRecorder - 0.3.6
HLTB For Deck - 1.4.1-1
CSS Loader - 2.0.6
[cef_log.previous.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/14582089/cef_log.previous.txt)

### Expected Behaviour

Launch without crashing

### SteamOS version

3.4.8

### Selected Update Channel

Stable

### Backend Logs
[deckylog1.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/14582183/deckylog1.txt)

### Frontend Logs
[cef_log.previous.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/14582141/cef_log.previous.txt)

**Comment by CobaltChris** [comment]
[cef_log.previous.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/14582355/cef_log.previous.txt)
[deckylog1.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/14582357/deckylog1.txt)


I added these logs as the ones in the original post seem to 404 out. I tried re-uploading them, but the entry box kept fighting me.

**Comment by JohnnyCrazy** [comment]
Hi,

Did you try launching it with having decky installed, but without any plugins installed?

**Comment by CobaltChris** [comment]
Can confirm a fresh instance does not cause issues so far.

I am now attempting to determine which plugin/setting/combination causes this issue.

**Comment by CobaltChris** [comment]
It appears that PowerTools was the source of the problem. I will now be closing the issue.
