### ISSUE TITLE
[Request] Make Decky-Loader compatible with Windows with Millennium Project

### ISSUE THREAD

**Issue by shawny43** [SteamDeckHomebrew/decky-loader#602]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

https://millennium.web.app/

Millennium made some proofs that Steam mods can work on the client inside Windows wich is a good opportunity if Decky gang could work together with Millennium and make Big Pictures plugins and themes mods work in that way. Soo why not work both together and make Steam moddable everywhere?

Millennium is an project that allow themes and plugins in similar way from Decky loader but specific to the desktop version. This allow themes and plugins trough their own embeded integrations withtout broke anything that could be a nice way for Decky to start if they want to make an desktop version of it. 

This can solve some missing compatibility has well and mostly from this particular case when we needs to theme both BP and Desktop together and get plugins work in both modes. Soo let's me what's you think. I know SFP is dying over there but Millennium seem have good promises over there. 

### Further Description

Millennium bring their own executable installer with one click. It's install all necessary that include DirectX9 and such redistribuables withtout issues. If Decky needs to create an executable compatible, millennium gang could help. For any plugins and themes managements this could be handy if both work together.

**Comment by AAGaming00** [comment]
we already somewhat support windows, and we will not be using millennium's method as our current method works on windows.

**Comment by shawny43** [comment]
But it's show has desktop files when i click download. It's not make sense of what's you said. What does you mean?

**Comment by TrainDoctor** [comment]
> But it's show has desktop files when i click download. It's not make sense of what's you said. What does you mean?

We do not provide an installer for windows. Just the executable.

**Comment by shawny43** [comment]
Can we do something with Desktop file, such an Bash execution?

**Comment by PartyWumpus** [comment]
You don't use the desktop file. You just download the windows binary, available in GitHub actions and run it. We currently don't have any plans to properly support windows or desktop mode, but it's been perfectly possible for a long time.
