### ISSUE TITLE
[Will support for desktop linux (specifically manjaro) be implemented?] <title>

### ISSUE THREAD

**Issue by MakaiHanta** [SteamDeckHomebrew/decky-loader#603]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

My goal was to turn my PC into something like a console: to be able to play games on it as comfortably while sitting on the couch in front of the TV, but also conveniently switch to the monitor. Only linux with KDE Plasma fulfills my requirements. Unfortunately, my setup is sorely lacking custom plugins.

I tried to run the install script, but unfortunately it just terminates without any result. I would really like to see a desktop linux version of the decky loader

**Comment by TrainDoctor** [comment]
We provide general support but not for specific distros. This seems like a Manjaro problem.

**Comment by PartyWumpus** [comment]
The install script assumes you have konsole installed, try using the CLI installer. If that doesn't work, check the [wiki](https://wiki.deckbrew.xyz/e/en/user-guide/install). If that doesn't work then it's probably a manjaro issue and not something I'd care to debug.

**Comment by MakaiHanta** [comment]
> Сценарий установки предполагает, что у вас установлен konsole, попробуйте использовать установщик CLI. Если это не сработает, проверьте [вики](https://wiki.deckbrew.xyz/e/en/user-guide/install). Если это не сработает, то, вероятно, это проблема manjaro, а не то, что я хотел бы отлаживать.

When starting the installer, the konsole opens and then closes 3 seconds later. Nothing is written in the konsole itself. At the same time, nothing is written in the console itself, there is only a cursor

**Comment by PartyWumpus** [comment]
please run the command at the bottom of [this section of the readme](https://github.com/SteamDeckHomebrew/decky-loader?tab=readme-ov-file#-installation) if the installer isn't working.

**Comment by MakaiHanta** [comment]
> please run the command at the bottom of [this section of the readme](https://github.com/SteamDeckHomebrew/decky-loader?tab=readme-ov-file#-installation) if the installer isn't working.

It worked! It turns out that the "jq" package is required to install the decky loader
