### ISSUE TITLE
[BUG] Something went wrong while dsplaying this content

### ISSUE THREAD

**Issue by hanschke** [SteamDeckHomebrew/decky-loader#605]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

Error Reference: Shared SteamUI_0_52519ecac0fde95d

Cannot read properties undefined (reading "InnerContainer)

### Expected Behaviour

I cannot install or start any games on my steam deck and after uninstall the Decky all work fine.

### SteamOS version

Steam OS latest Stable

### Selected Update Channel

Prerelease

### Have you modified the read-only filesystem at any point?

no

### Backend Logs

Error Reference: Shared SteamUI_0_52519ecac0fde95d

Cannot read properties undefined (reading "InnerContainer)

### Frontend Logs

Error Reference: Shared SteamUI_0_52519ecac0fde95d

Cannot read properties undefined (reading "InnerContainer)

**Comment by TrainDoctor** [comment]
This is not a bug report, you have not attached any of the logs we need.

**Comment by novhack** [comment]
This bug happens on SteamOS Beta channel. When SteamOS Beta is installed it becomes impossible to open any game detail until Decky Loader is uninstalled.
