### ISSUE TITLE
[Request] Add rebooting to the install instructions

### ISSUE THREAD

**Issue by Soundtoxin** [SteamDeckHomebrew/decky-loader#607]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

Following the install instructions, the plug symbol for Decky didn't appear. I went back into desktop mode and ran the installer again in case something was wrong, but it asked if I wanted to update or reinstall this time. I chose update even though I'd just installed it. I went back to game mode a second time. Still not there. I rebooted. Then it showed up. But the instructions don't mention you have to reboot, so I was convinced I'd done something wrong or was missing something. I would highly recommend mentioning that a reboot may be necessary after the Decky install.
Also, I think the website should probably have install instructions and not just the github readme.

### Further Description

This would reduce the friction during initial install for new users.

**Comment by TrainDoctor** [comment]
This is not intended behavior. If you file an issue we can try to fix the underlying issue.

**Comment by Soundtoxin** [comment]
Since it eventually started working, I'm not sure I could recreate the issue for the purpose of gathering logs, but it's good to know this was unintended. I looked over the readme wondering what sort of logs you could mean (and it didn't say, but I did find them mentioned in the new issue / bug report template) and I noticed under common issue that syncthing is mentioned and there's a port collision. That may very well have been my issue, and then if so, perhaps syncthing didn't start automatically on reboot because it only runs once I start desktop mode, and I booted into game mode. So now presumably if decky is working, syncthing is not currently working.
BTW if you know that 8080 is a commonly used port, why would you (as in whoever wrote the readme / runs the show) ask people to change ports of everything else instead of just changing the port for decky? Seems a bit odd to me.
In either case I think I can probably close this particular issue as you've addressed that it wasn't intended/expected and I must've hit some sort of problem. If I manage to run into the problem again and it doesn't turn out to be related to syncthing, then I'll open a fresh issue at that time. Thanks. Closing.
