### ISSUE TITLE
[Request] Notify user if new plugins have been added to the database

### ISSUE THREAD

**Issue by JtdeGraaf** [SteamDeckHomebrew/decky-loader#616]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

Notify the user if new plugins have been added to the plugin database.

This will help users who aren't active in the community with finding new plugins, it also helps the plugin developer gain some publicity.

This feature should be opt-in or opt-out.

I might be able to develop this myself, but I'd first like to know if this is wanted or not.

**Comment by PartyWumpus** [comment]
You can always sort by newest in the store tbf. Some sort of discovery system could be good though for sure.

**Comment by TrainDoctor** [comment]
I doubt this will ever be useful to our project given sorting by new is possible now.
