### ISSUE TITLE
[BUG] Decky stops working when switching to a different Steam account

### ISSUE THREAD

**Issue by adriansticoid** [SteamDeckHomebrew/decky-loader#618]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

I share my Steam Deck with my sister and with the new Families feature, she now logs in her own account on the Deck. I picked it up one time, her account was in so I switched to mine, and now Decky won't show up in QAM. If I reboot manually, only then Decky will show up again while my account is logged in.

### Expected Behaviour

Decky should be able to seamlessly function while switching accounts in gaming mode.

### SteamOS version

3.5.17 Stable, Steam Client beta

### Selected Update Channel

Stable

### Backend Logs

[deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15098582/deckylog.txt)

### Frontend Logs

[cef_log.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15098601/cef_log.txt)
[cef_log.previous.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15098603/cef_log.previous.txt)

**Comment by adriansticoid** [comment]
Switched back to her account, Decky is active again. Switched back to mine, inactive.

**Comment by Mothamoz** [comment]
Exact same issue here, client setup as described in OP as well.

It works for the first time going back to game mode after rerunning the installer from the secondary account, attempts after that it's gone again though.

**Comment by CrazyCoder** [comment]
Same issue. It would be great if Decky could work from all the accounts.

**Comment by rairulyle** [comment]
Bump

**Comment by dANii2k** [comment]
Same probleem Here

**Comment by MonsterSurface** [comment]
Has anyone found a solution yet?

**Comment by TrainDoctor** [comment]
The issue is due to how the UI is treated when switching to another account. We've tried several different solutions but have had no concrete results.

**Comment by MonsterSurface** [comment]
> The issue is due to how the UI is treated when switching to another account. We've tried several different solutions but have had no concrete results.

Ok that’s fine I’ve worked out that if I just restart the system instead it works thanks, anyway.
