### ISSUE TITLE
[Request] Disable / Enable plugin functionality

### ISSUE THREAD

**Issue by dev0T** [SteamDeckHomebrew/decky-loader#623]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

Decky plugins could be disabled / enabled when needed. This would help plugins broken with updates to be disabled temporarily and then re-enabled when they have been updated, for example. See #621. This would reduce the friction of needing to uninstall the plugins and they search for them again after the issues are solved.

It could be an extra button sharing space with the current Reinstall one or an added entry on the menu.

**Comment by AbsurdlySuspicious** [comment]
#350
