### ISSUE TITLE
[Request] Better detect failed page renders and automatically disable UI modifications from plugins causing them

### ISSUE THREAD

**Issue by BryanJacobs** [SteamDeckHomebrew/decky-loader#625]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] This is not a request for a plugin

### Feature Request Description

Decky should be able to detect when a plugin causes a Steam frontend render failure, and help the user to restore decky-loader itself (not the plugin...) to a working state.

### Further Description

See https://github.com/SteamDeckHomebrew/decky-loader/issues/621 , where a large number of plugins were simultaneously broken by a Steam frontend update.

Decky-loader has some code to notice when a plugin errors out, but _doesn't_ appear to notice when the plugin breaks the Steam UI entirely. This can - and did - create a situation where users couldn't uninstall plugins via the GUI, because the decky-loader GUI was inaccessible due to modifications made by the plugins themselves.

I think a situation where all pages are throwing render errors should cause decky-loader to disable plugins until that stops being the case. Call it a "safe mode", if you will. This would ideally also be able to isolate the broken plugin(s) and inform the user.

**Comment by AAGaming00** [comment]
Better error boundaries are planned for the websocket update
