### ISSUE TITLE
[BUG] Decky UI not displaying in latest client beta (May 28)

### ISSUE THREAD

**Issue by AurelioB** [SteamDeckHomebrew/decky-loader#630]
### Please confirm

- [x] I have searched existing issues
- [x] This issue is not a duplicate of an existing one
- [x] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [x] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

After updating to latest client beta Decky UI disappeared from the QA menu.
Plugins are (at least partially) still loaded. For example, my CSS loader theme is still applied, but ProtonDB badges & HLTB stats are not displayed in game view.

I've already tried reinstalling decky prerelease, but the result is the same

- **OS Build:** 20240516.100
- **Steam Version:** 1716970740
- **Steam Client Build Date:** Wed, May 29 1:44 AM UTH -08:00
- **Steam Web Build Date:** Wed, May 29 1:44 AM UTH -08:00
- **Steam API Version:** SteamClient021

### Expected Behaviour

Decky UI should be available in QAM

### SteamOS version

SteamOS 3.6.3

### Selected Update Channel

Prerelease

### Have you modified the read-only filesystem at any point?

No

### Backend Logs

[deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15488115/deckylog.txt)

### Frontend Logs

[cef_log.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15488132/cef_log.txt)
[cef_log.previous.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15488144/cef_log.previous.txt)

**Comment by Felzow47** [comment]
Got the same error and i can't get in stable SteamOS since im using family share beta 

If you want my log tell how

**Comment by TrainDoctor** [comment]
@AurelioB thank you for the report, but I'm merging this report into #631, @Felzow47 I'll post instructions in #631 for you.

**Comment by Felzow47** [comment]
> @AurelioB thank you for the report, but I'm merging this report into #631, @Felzow47 I'll post instructions in #631 for you.

Ok thx im going to #631 and post my log !
