### ISSUE TITLE
[BUG] Decky Loader does not load into QAM after the latest Steam Deck Beta client update

### ISSUE THREAD

**Issue by dshk0718** [SteamDeckHomebrew/decky-loader#631]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

After the latest Steam Client Beta update the Decky Loader fails to load along with other plugins.
The reason why I am creating a new issue for this is because it was working up until this 5/27/2024 and 5/28/2024 Steam Deck Beta client update hit.
Looking at the logs myself, I found out that it failed to inject Decky Loader through CEF as shown in the log here:
![ksnip_20240529-122652](https://github.com/SteamDeckHomebrew/decky-loader/assets/22249997/c2a83413-4b1b-4470-9d24-0f3b32c886e4)

I reproduced this same issue on the stable SteamOS 3.5.19. Thus, I believe the Steam beta client is the issue here, not the OS.

I have tried reinstalling but did not help. Also, at the time of writing this issue, the pre-release version of the Decky Loader is behind the stable version, which is v2.12.0, which is to say there isn't a pre-release version I can use to fix this issue.

Bug reproduction steps:
1. Go to settings and opt for Steam Deck Beta client.
2. Apply the update and restart Steam.
3. Decky Loader along with other plugins will fail to inject/load.

Note: Some plugins that save the configurations to the Steam client like CSS Loader and Animation Changer still work though.
Also, I would like to note that I am not running Syncthing or any other application service at port 8080 or 1337 (other than `steamwebhelper` at port 8080, which I believe is necessary):
![ksnip_20240529-124905](https://github.com/SteamDeckHomebrew/decky-loader/assets/22249997/34f2cea4-c399-4f1b-b915-e1d357cb9cc2)

### Expected Behaviour

Decky Loader should inject successfully and show up in the Quick Access Menu (QAM) in the Steam Deck Beta client.

### SteamOS version

SteamOS 3.6.3 Beta

### Selected Update Channel

Stable

### Backend Logs

[deckylog.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15488202/deckylog.txt)
The same log but with better syntax highlighting if you prefer this:
[plugin_loader.log](https://github.com/SteamDeckHomebrew/decky-loader/files/15488218/plugin_loader.log)

### Frontend Logs

[cef_log.previous.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15488716/cef_log.previous.txt)
[cef_log.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15488718/cef_log.txt)

**Comment by TrainDoctor** [comment]
@dshk0718 good report. @AurelioB, going to merge #630 into this issue. Please make sure to copy your report into this issue. Cheers.

**Comment by Felzow47** [comment]
[deckylogs.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15489131/deckylogs.txt)
[cef_log.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15489132/cef_log.txt)
[cef_log.previous.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15489133/cef_log.previous.txt)

**Comment by TrainDoctor** [comment]
> Here is my log
> 
> [deckylogs.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15489131/deckylogs.txt) [cef_log.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15489132/cef_log.txt) [cef_log.previous.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15489133/cef_log.previous.txt)

Please make sure to include the details like verifying you don't have anything running on 8080 or 1337 etc and any details that could root out other issues.

**Comment by Felzow47** [comment]
> > Here is my log
> > [deckylogs.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15489131/deckylogs.txt) [cef_log.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15489132/cef_log.txt) [cef_log.previous.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15489133/cef_log.previous.txt)
> 
> Please make sure to include the details like verifying you don't have anything running on 8080 or 1337 etc and any details that could root out other issues.

Ok but normaly i uninstalled syncthing so 🥲 but i will check that and edit my Message

**Comment by dshk0718** [comment]
@TrainDoctor I've used the instruction provided here in this issue by this contributor: https://github.com/SteamDeckHomebrew/decky-loader/issues/491#issuecomment-1916686121
> Providing Logs
In order to aid in analyzing your issue, you need to provide us with the logs files for the Plugin Loader and any associated plugins that you may have an issue with.
You can extract the logs from your Steam Deck by running the following commands in desktop mode (or via an SSH connection):

```bash
journalctl -b all -u plugin_loader.service > ~/homebrew/logs/plugin_loader.log
tar -czf ~/Desktop/DeckyLogs.tgz -C ~/homebrew/logs .
```
> Please attach the resulting DeckyLogs.tgz file from your desktop onto this ticket.

**Comment by micsama** [comment]
me too. please help us
[DeckyLogs.tgz](https://github.com/SteamDeckHomebrew/decky-loader/files/15489260/DeckyLogs.tgz)

**Comment by dshk0718** [comment]
As for the port usage reports, here is the snippet (so that anyone who comes across this issue doesn't have to copy from the screenshots above):
```bash
lsof -i :8080 -sTCP:LISTEN +c 0
lsof -i :1337 -sTCP:LISTEN +c 0
```
You can copy and paste this into your terminal (Konsole).

**Comment by borconc** [comment]
[cef_log.previous.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15490358/cef_log.previous.txt)
[cef_log.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15490359/cef_log.txt)
[deckylogs.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15490360/deckylogs.txt)

here are my logs for the same issue

**Comment by Felzow47** [comment]
> [cef_log.previous.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15490358/cef_log.previous.txt) [cef_log.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15490359/cef_log.txt) [deckylogs.txt](https://github.com/SteamDeckHomebrew/decky-loader/files/15490360/deckylogs.txt)
> 
> here are my logs for the same issue

As @TrainDoctor  told me
Please make sure to include all the details like verifying you don't have anything running on 8080 or 1337 etc these port are used by decky and any details Who could help

Give SteamOS info 
What version of decky is used 
And if you have modified the read-only filesystem at any point?

**Comment by Epic62790** [comment]
getting the same issue and i dont have anything installed other than decky

**Comment by AAGaming00** [comment]
Check if it's fixed in the latest prerelease, if it works well for you all i'll put out a new stable release

**Comment by taylor85345** [comment]
> Check if it's fixed in the latest prerelease, if it works well for you all i'll put out a new stable release

I can confirm that the latest prerelease resolved the issue for me

**Comment by dshk0718** [comment]
> Check if it's fixed in the latest prerelease, if it works well for you all i'll put out a new stable release

@AAGaming00 Thank you for the quick fix! I also can confirm that the latest release fixed the issue.
Since the issue is resolved, I will close this issue.
