### ISSUE TITLE
This is not a compliment.

### ISSUE THREAD

**Issue by suerfang** [SteamDeckHomebrew/decky-loader#635]
### Please confirm

- [X] I have searched existing issues
- [ ] This issue is not a duplicate of an existing one
- [ ] This is not a request for a plugin

### Feature Request Description

Here is a version to install on Windows 10 to use Steam Link. I looked for how to add add-ons on the PC, but I couldn't find anything to use in Big Picture mode and then connect it to Steam Link, but I couldn't find anything.

**Comment by TrainDoctor** [comment]
We do not provide official windows support and will not.
