### ISSUE TITLE
[BUG] Missing Decky Loader icon in QAM

### ISSUE THREAD

**Issue by AkazaRenn** [SteamDeckHomebrew/decky-loader#640]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

1. Install the latest version of Steam Beta (ver. 1719420706 the one with Game Recording)
2. Find that the Decky Loader icon is missing in QAM
3. Note that the CSS plugin still functioned

### Expected Behaviour

Decky Loader icon should appear in QAM

### SteamOS version

SteamOS 3.6.7

### Selected Update Channel

Prerelease

### Have you modified the read-only filesystem at any point?

No

### Backend Logs

[deckylog.txt](https://github.com/user-attachments/files/15994184/deckylog.txt)

### Frontend Logs

[cef_log.txt](https://github.com/user-attachments/files/15994182/cef_log.txt)
[cef_log.previous.txt](https://github.com/user-attachments/files/15994183/cef_log.previous.txt)

**Comment by AkazaRenn** [comment]
https://deckthemes.com/themes/view?themeId=fa803fc3-a391-4cec-9721-7b6c33b13b74
This theme also tops working, might just be that they changed the class name.

**Comment by dshk0718** [comment]
I was going to report this same issue.

Here are my logs:

Backend logs:
[plugin_loader.log](https://github.com/user-attachments/files/15994497/plugin_loader.log)

Frontend logs:
[cef_log.previous.txt](https://github.com/user-attachments/files/15994561/cef_log.previous.txt)
[cef_log.txt](https://github.com/user-attachments/files/15994562/cef_log.txt)

**Comment by lyndonguitar** [comment]
Would like to report the same issue with mine. same version and all. However this is expected as this is a new beta update from Steam.

**Comment by SubElement** [comment]
Just wanted to chime in and say I’m experiencing the same issue.

**Comment by PartyWumpus** [comment]
Issue is being investigated, thank you all for your logs and for reporting this

**Comment by AAGaming00** [comment]
Should be fixed in the latest prerelease, please test

**Comment by lzq960605** [comment]
> Should be fixed in the latest prerelease, please test
Fixed, testing completed

**Comment by lzq960605** [comment]
You can close this issue now

**Comment by SubElement** [comment]
> Should be fixed in the latest prerelease, please test

I can confirm this is fixed with 3.0.0pre1
