### ISSUE TITLE
[BUG] Decky Loader crashes when searching with words with spaces in between

### ISSUE THREAD

**Issue by dshk0718** [SteamDeckHomebrew/decky-loader#643]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

When I try to search for games or anything through the search bar in the game mode, Decky Loader crashes _if_ there is a space between the search words.
Here is the video of me reproducing the bug:
https://github.com/SteamDeckHomebrew/decky-loader/assets/22249997/d56bb777-9135-4454-8ff9-f4ecfe9081b7

To reproduce:
1. Start typing in the search bar in the game mode.
2. After the first word, add a space then start typing a new word.
3. The Decky Loader should have crashed and shown the error message.

### Expected Behaviour

Decky Loader should not crash when searching for things in the game mode UI.

### SteamOS version

SteamOS 3.6.8 Beta

### Selected Update Channel

Prerelease

### Backend Logs

[plugin_loader.log](https://github.com/user-attachments/files/16020685/plugin_loader.log)

### Frontend Logs

[cef_log.previous.txt](https://github.com/user-attachments/files/16020691/cef_log.previous.txt)
[cef_log.txt](https://github.com/user-attachments/files/16020692/cef_log.txt)

**Comment by dshk0718** [comment]
FYI, this is happening on the current latest pre-release version v3.0.0-pre1.

**Comment by AAGaming00** [comment]
Steam problem, but our error detection is detecting the decky router wrapper when it shouldn't be.

**Comment by dshk0718** [comment]
@AAGaming00 What do you suggest we do? I guess we wait for Valve to release a new Steam Client update that would fix this issue?

**Comment by AAGaming00** [comment]
Yes, because it happens without decky. Report it to valve.

**Comment by dshk0718** [comment]
Done. https://github.com/ValveSoftware/steam-for-linux/issues/11034
