### ISSUE TITLE
Decky loader not loading in current steam beta release

### ISSUE THREAD

**Issue by ppyporpeem** [SteamDeckHomebrew/decky-loader#646]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [ ] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

After updating to the latest steam beta release (for the game record functionality) plugins no longer load on the side bar.

### Expected Behaviour

Plugins should appear on the sidebar

### SteamOS version

Steam os 3.6.8

### Selected Update Channel

Prerelease

### Backend Logs

-

### Frontend Logs

-

**Comment by PartyWumpus** [comment]
Please try updating decky via desktop mode, this issue should already be resolved.
