### ISSUE TITLE
[BUG] After the Steam OS update, the plugin has disappeared.

### ISSUE THREAD

**Issue by shuntal** [SteamDeckHomebrew/decky-loader#649]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

I had the plugin installed and it was working correctly. After some updates to Steam OS, the Decky icon no longer appears, and the plugins don't work either.

### Expected Behaviour

The icon should still appear after the updates.

### SteamOS version

steam os 3.6.8

### Selected Update Channel

Stable

### Backend Logs

i cant see it

### Frontend Logs

-

**Comment by ruifcastro** [comment]
This happen to a friend of mine too. The last time this happen I reinstalled Decky and everything appeared again (all his pluggins).

I will be with him later and will do the same. I hope it fixes it. Both of us have the same setup but it only happens to him.

Beta Steam OS and prerelease Decky this time. Last time he had Stabel Steam OS and Stable Decky

**Comment by Lordtechnik** [comment]
> This happen to a friend of mine too. The last time this happen I reinstalled Decky and everything appeared again (all his pluggins).
> 
> I will be with him later and will do the same. I hope it fixes it. Both of us have the same setup but it only happens to him.
> 
> Beta Steam OS and prerelease Decky this time. Last time he had Stabel Steam OS and Stable Decky

You can fix it by updating  by decky to the release instead of the stable. I had the same problem, and I just tried that and it worked. Hopefully this helps!
