### ISSUE TITLE
[BUG] Deleting a screenshot while its open crashes the decky frontend.

### ISSUE THREAD

**Issue by Pigney** [SteamDeckHomebrew/decky-loader#650]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

In gamemode take a screenshot, go to the media tab and open the screenshot, press the delete button and confirm.
Decky crashes claiming its likely caused by the Decky Frontend.

### Expected Behaviour

Should return to empty media tab instead of crashing.

### SteamOS version

SteamOS 3.7 Main

### Selected Update Channel

Prerelease

### Have you modified the read-only filesystem at any point?

No

### Backend Logs

[deckylog.txt](https://github.com/user-attachments/files/16101318/deckylog.txt)

### Frontend Logs

[cef_log.txt](https://github.com/user-attachments/files/16101320/cef_log.txt)
[cef_log.previous.txt](https://github.com/user-attachments/files/16101321/cef_log.previous.txt)

**Comment by AAGaming00** [comment]
This is a steam issue, our error source detection just has some bugs rn
