### ISSUE TITLE
[BUG] Decky stopped working after the SteamOS 3.6.8 Beta update

### ISSUE THREAD

**Issue by Sythog** [SteamDeckHomebrew/decky-loader#659]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

Decky disappeared from QAM. 
CSSs from the CSS Loader plugin are still applied though.

Yes, I tried to install the stable version.
Yes, I tried to reinstall the prerelease version.

### Expected Behaviour

Decky appears in QAM.

### SteamOS version

SteamOS 3.6.8 Beta

### Selected Update Channel

Prerelease

### Backend Logs

[deckylog.txt](https://github.com/user-attachments/files/16265196/deckylog.txt)

### Frontend Logs

[cef_log.txt](https://github.com/user-attachments/files/16265198/cef_log.txt)
[cef_log.previous.txt](https://github.com/user-attachments/files/16265199/cef_log.previous.txt)

**Comment by DulinDuskhawk** [comment]
Same here. 
Also tried a uninstall en reinstall with prerelease version. 
(kept the config at uninstall though)

**Comment by TrainDoctor** [comment]
We're aware of the issue, our primary patch maintainer is away and will work to fix the issue asap. Please have patience. Thanks.

**Comment by Coleayres** [comment]
Yep same here at least everything is still deckyified

**Comment by Sythog** [comment]
@TrainDoctor any chance that you can give at least some ETA?

**Comment by WerWolv** [comment]
ETA is 12 hours from now. If it hasn't arrived by then, please read this message again.

**Comment by Spanky3651** [comment]
Any update on a fix?

**Comment by Spanky3651** [comment]
Prerelease v3.0.0-pre5 seem to fix this issue for me.

**Comment by danfozzy** [comment]
How did you install the pre5? Installing using the stable or pre release still doesn't get it working for me?

**Comment by DulinDuskhawk** [comment]
Just used the normal installer on desktop, choose pre-release. 
Nothing special.

**Comment by Sythog** [comment]
Pre5 works! 
Thanks!

**Comment by KibSquib48** [comment]
Latest decky prerelease isn't working anymore after today's Beta update, missing from QAM but CSS is still active just like in the og post

**Comment by TrainDoctor** [comment]
> Latest decky prerelease isn't working anymore after today's Beta update, missing from QAM but CSS is still active just like in the og post

Please gather logs as the original issuer filer did.

**Comment by AAGaming00** [comment]
Fixed in the latest prerelease.
