### ISSUE TITLE
Move homebrew folder into ~/.local/share ($XDG_DATA_HOME)

### ISSUE THREAD

**Issue by logan2611** [SteamDeckHomebrew/decky-loader#66]
It makes more sense to have the homebrew folder be located in ~/.local/share as that is where most programs put theirs (including Steam). It is also a lot tidier in my opinion.
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by TrainDoctor** [comment]
I've brought this up and suggested that homebrew be a link to your suggested folder (with a different name) but for the moment things are progressing quite quickly that I can't say that this will be implemented anytime soon. A helpful and needed inclusion though. Thanks for the feedback!

**Comment by TrainDoctor** [comment]
This issue will be replaced by a formal issue for the team, we will be using symlinks to XDG compliant directories created through the installer for main releases.
