### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by Evgen-GAS** [SteamDeckHomebrew/decky-loader#660]
### Please confirm

- [ ] I have searched existing issues
- [ ] This issue is not a duplicate of an existing one
- [ ] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [ ] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

Всем привет. Decky Loader установил,захожу в стим нажимаю   ... смотрю вилка добавилась ,после чего выбираю ее и выбираю магазин .... и не чего просто крутится колесо загрузки и не чего не происходит .

### Expected Behaviour

Удолял ставил заново и не чего. 

### SteamOS version

3.5.19

### Selected Update Channel

Stable

### Have you modified the read-only filesystem at any point?

нет

### Backend Logs

[deckylog.txt](https://github.com/user-attachments/files/16274433/deckylog.txt)

### Frontend Logs

я не знаю как копировать журнал инерфейса и где что искать

**Comment by WerWolv** [comment]
Please reopen your issue in English
