### ISSUE TITLE
Custom `requirements.txt` for plugins.

### ISSUE THREAD

**Issue by matbee-eth** [SteamDeckHomebrew/decky-loader#665]
Would love to supply a list of requirements for the backend python plugin.

**Comment by TrainDoctor** [comment]
You can already do this for local work but we specifically do not handle any package management when building plugins because it would massively increase the complexity we would have to debug during CI/CD.

**Comment by TrainDoctor** [comment]
Apologies, misunderstood the question. @suchmememanyskill should be able to take a look at that.
