### ISSUE TITLE
Several anecdotal reports of plugin loader maybe causing QAM hangs

### ISSUE THREAD

**Issue by notimp** [SteamDeckHomebrew/decky-loader#67]
on new (stable) firmware:

see:
https://old.reddit.com/r/SteamDeck/comments/uzgmiv/steamos_locks_up_after_pressing_quick_access/

I have experienced extended hangs on QAM appearing after you press the ... button, as well as hangs on the new firmware (system needed to be hard powered down).

Dont have a perfect way to replicate, but launching retroarch and playing paper mario (n64) in mupen64plus-next with glide64 after an hour or so playing (maybe shorter, causes those long delays on qam appearing or until it becomes responsive , without a fault).

So seems worse over time (maybe?) So memory leak?

**Comment by Jay2645** [comment]
I am also getting this. Only plugin I have installed is the Spotify plugin. Can get it fairly reliably by pressing the QAM physical button from Stellaris after about 3 hours ingame on the latest Steam Deck firmware (beta branch).

**Comment by TrainDoctor** [comment]
I have been encountering lag since I started working with the team on the plugin. I think it's a big of a "known issue with no known cause" but addressing it's been on the backend with the continued work on the move to react etc. I feel confident in saying that this issue will be addressed come the release of that feature update and if not then than after. Thanks for keeping us on our toes!

**Comment by HugLifeTiZ** [comment]
I had this happening too, and because I use my Deck primarily docked (which means I can't interact with the plugins anyways), I uninstalled the plugin loader and the issue went away.

**Comment by loseryoda** [comment]
Same issue, forced to power down the deck, uninstalling it until it's fixed

**Comment by TrainDoctor** [comment]
During testing of the react update we've noted significant improvements in performance. If any of you would like to confirm these improvements or confirm the issue's existence you can use the contrib script on the react-frontend-plugins branch.

If replication of this issue doesn't occur during the release-candidate period for the react update, this issue will be closed.
Cheers.

**Comment by rhossack** [comment]
The hangs/softlocks I get apparently as a result of having this Plugin Loader installed is the biggest source of frustration I have when using my Steam Deck, by far. I'll try out the react branch this weekend if it will help.

It's an issue I hit maybe 2-5 times a day when I'm playing actively, so it should be pretty obvious when it isn't messing up. Not to mention, the general bad performance is something I'm used to.

**Comment by TrainDoctor** [comment]
> The hangs/softlocks I get apparently as a result of having this Plugin Loader installed is the biggest source of frustration I have when using my Steam Deck, by far. I'll try out the react branch this weekend if it will help.
> 
> It's an issue I hit maybe 2-5 times a day when I'm playing actively, so it should be pretty obvious when it isn't messing up. Not to mention, the general bad performance is something I'm used to.

We're moving to get a usable alpha out for testers asap, but we're having to adapt our new plugin distribution system and also bundling the new version properly etc. Appreciate your feedback.

**Comment by TrainDoctor** [comment]
This issue is considered resolved with internal testing. If the issue occurs again  the team will re-open as needed. Thanks for your feedback and information everyone.

**Comment by rhossack** [comment]
> This issue is considered resolved with internal testing. If the issue occurs again the team will re-open as needed. Thanks for your feedback and information everyone.

When I saw this, I finally got around to updating my version of Plugin Loader. The first time I pressed the QAM button, my Steam Deck hanged... Are you sure this has been fixed, or did I somehow not grab the version with the fix?

**Comment by TrainDoctor** [comment]
> > This issue is considered resolved with internal testing. If the issue occurs again the team will re-open as needed. Thanks for your feedback and information everyone.
> 
> When I saw this, I finally got around to updating my version of Plugin Loader. The first time I pressed the QAM button, my Steam Deck hanged... Are you sure this has been fixed, or did I somehow not grab the version with the fix?

The latest release does not have this fix, that is correct. The pre-release version we are preparing to publish will contain the fix. The issue has been closed to reduce clutter and make it easier for devs to understand our current scope. Keep your eyes out for the pre-release soon:tm:!
