### ISSUE TITLE
[BUG] 3.0.0-Pre6 bricks Game Mode

### ISSUE THREAD

**Issue by spudpiggy** [SteamDeckHomebrew/decky-loader#671]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

**For anyone affected by this issue: If you have a USB keyboard you can connect, hold `Ctrl+Alt+;` (semicolon) to boot into Desktop mode. From there you can uninstall/downgrade.**

I installed the latest update and my Steam Deck can no longer boot into Game Mode. Not even Steam itself can be opened in desktop. (it's working enough for my bindings to work, but if i try opening a window of it then nothing happens)
I had to boot into Desktop Mode and uninstall Decky Loader using a USB keyboard (and SSH to get my logs to make this issue)
I found [a Reddit thread](https://www.reddit.com/r/SteamDeck/comments/w1xm5w/steam_deck_wont_turn_on_when_ever_i_press_the/) full of people complaining about this exact issue.
***Please revoke this update as it is causing people to brick.***

This is off-topic, but to stop this from happening again there should be a way to stop Decky from loading with a button combo on the deck itself. (You can't rely on everyone having the means to connect a USB keyboard, since the device can't do it out of the box.)

### Expected Behaviour

Generally, I would expect such an update to **not** brick my device, so as to keep it in a usable state.

### SteamOS version

SteamOS 3.6.8 Beta (build 20240626.100

### Selected Update Channel

Prerelease

### Have you modified the read-only filesystem at any point?

I definitely have but I don't remember what exactly I've done

### Backend Logs

[deckylog.txt](https://github.com/user-attachments/files/16531874/deckylog.txt)
Ignore any entries before the 7th of August, 2024

### Frontend Logs

[cef_log.previous.txt](https://github.com/user-attachments/files/16531915/cef_log.previous.txt)
[cef_log.txt](https://github.com/user-attachments/files/16531916/cef_log.txt)
Ignore any entries before the 7th of August, 2024

**Comment by kotovasia5120** [comment]
similarly

**Comment by AAGaming00** [comment]
> but to stop this from happening again there should be a way to stop Decky from loading with a button combo on the deck itself.

Planned.

This update doesn't cause the brick, the issue is the usage of non global DFL plugins on Steam Beta. It just only happens with this update because Decky 2.0 cannot load on Steam Beta

**Comment by kotovasia5120** [comment]
> > but to stop this from happening again there should be a way to stop Decky from loading with a button combo on the deck itself.
> 
> Planned.
> 
> This update doesn't cause the brick, the issue is the usage of non global DFL plugins on Steam Beta. It just only happens with this update because Decky 2.0 cannot load on Steam Beta

For example, I have Steam 3.5.19

**Comment by kotovasia5120** [comment]
> Кажется, меня это тоже коснулось. Использование USB-клавиатуры, похоже, не работает для меня 😞

Ctrl+Alt+; not work combination, but after a few reboots I was able to switch to desktop mode using the usual method.

**Comment by milroneth** [comment]
> > Кажется, меня это тоже коснулось. Использование USB-клавиатуры, похоже, не работает для меня 😞
> 
> Ctrl+Alt+; not work combination, but after a few reboots I was able to switch to desktop mode using the usual method.

You need to use the key where the semicolon is on the default US layout, a couple keys left of the enter key. If your keyboard displays symbols localized only in another language layout, then your semicolon might be the wrong key.

**Comment by PascalLeroi** [comment]
Got the same problem and could finally get it to work after trying to use the key combination several times. After the uninstall the steamdeck works again. Tried installing the latest pre again and it was back to issues of not being able to start to gamemode. Luckily I could get to desktop mode once again and uninstall deckyloader once more. So seems like the latest pre does not play nicely with steam stable 3.5.19

**Comment by milroneth** [comment]
The problem is not the prerelease itself, but certain plug-ins that you have that haven't been update to use newer methods and are so incompatible by now that things break. If you remove those or update them to newer versions as their developers push them out, it all works fine.

There's a partial list of those that cause problems in the homebrew Discord, or you can just delete all of them in your plug-ins folder and start re-introducing them one by one so you'll know what causes the crashes.

**Comment by Roki100** [comment]
nah bro, seeing this after getting the deck bricked is annoying

decky loader just lost one user, goodbye

**Comment by pokeparadox** [comment]
Working fine here, thanks!🙂

**Comment by kotovasia5120** [comment]
pre9 working

**Comment by AAGaming00** [comment]
pre9 fixes an unrelated issue, but thanks for the testing regardless!

**Comment by soonic6** [comment]
For people from germany, it is strg+alt+ö  for booting into desktop mode. Spam it, don't hold it.

**Comment by LennardF1989** [comment]
Wish I had known the ctrl+alt+; thing before I did a soft-reset by reinstalling just Steam OS xD

**Comment by Cybolic** [comment]
This just happened to me after upgrading to the stable 3.0 release. I've never experienced the boot-loop issue before, so having this issue after upgrading to the version that was supposed to prevent boot-loops was somewhat surprising.
I would recommend somehow checking for incompatible plugins before allowing an upgrade to finalise.

**Comment by AAGaming00** [comment]
The original cause of these boot loops was fixed, you might have somehow found a different one. Send your plugin list (there's a script to do it for you) and we'll look into it.

**Comment by AAGaming00** [comment]
Additionally, decky should disable itself after 3 failed startups

**Comment by TrainDoctor** [comment]
> The original cause of these boot loops was fixed, you might have somehow found a different one. Send your plugin list (there's a script to do it for you) and we'll look into it.

In particular, if you file a new issue that issue walks you through how to collec
