### ISSUE TITLE
[BUG] Black screen but still hear sound

### ISSUE THREAD

**Issue by Dag102** [SteamDeckHomebrew/decky-loader#675]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

When I downloaded the newest prerelease, my deck would get halfway through the boot animation, then the screen goes black and it becomes unusable. I can still hear the music I added through a plug-in, so it seems to be working on some level. Tried booting in a reverted version but can’t change decky as I can’t get to it. Would appreciate any help! 

### Expected Behaviour

Booting normally 

### SteamOS version

Steam o.s, the second newest release 

### Selected Update Channel

Prerelease

### Have you modified the read-only filesystem at any point?

No

### Backend Logs

Can’t run my deck that far 

### Frontend Logs

Can’t run my deck that far

**Comment by AAGaming00** [comment]
Update decky to v3.0.0-pre9

**Comment by AAGaming00** [comment]
You can enter desktop mode by spamming Ctrl alt semicolon

**Comment by AidanNotFunny** [comment]
this happened to me on vacation

I've been wanting to play fallout so bad I eternally curse whatever Decky developer made this bug

**Comment by TrainDoctor** [comment]
> this happened to me on vacation
> 
> I've been wanting to play fallout so bad I eternally curse whatever Decky developer made this bug

Pre-release is called pre-release and not stable for a reason. You assume a certain amount of risk for breaking changes both on our part and on the part of valve. We are future proofed against this going forward. Please don't return unless you have anything helpful to say.

**Comment by TrainDoctor** [comment]
This issue has been resolved and steps have been taken to prevent plugins from causing UI loops like this in future.
