### ISSUE TITLE
[BUG] <title> cheatdeck Desktop mode crash pop-up window

### ISSUE THREAD

**Issue by lzq960605** [SteamDeckHomebrew/decky-loader#689]
### Please confirm

- [ ] I have searched existing issues
- [ ] This issue is not a duplicate of an existing one
- [ ] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

![Screenshot_20240822_174807](https://github.com/user-attachments/assets/693a69c5-62f9-456f-9c02-62339f4b7954)
![Screenshot_20240822_174828](https://github.com/user-attachments/assets/a374a45b-0b11-4c82-9026-1bb9e326e490)
![Screenshot_20240822_174843](https://github.com/user-attachments/assets/b7d51792-ca31-43fc-a25d-1166d75fffe1)

### Expected Behaviour

cheatdeck Desktop mode crash pop-up window

### SteamOS version

steam os 3.5.19

### Selected Update Channel

Prerelease

### Backend Logs

[deckylog.txt](https://github.com/user-attachments/files/16708709/deckylog.txt)

### Frontend Logs

[cef_log.previous.txt](https://github.com/user-attachments/files/16708740/cef_log.previous.txt)
[cef_log.txt](https://github.com/user-attachments/files/16708741/cef_log.txt)

**Comment by doZennn** [comment]
The log looks exactly like the SteamGridDB plugin crash, except your plugin is named "封面下载" for some reason? Where did you get it?

**Comment by lzq960605** [comment]
> The log looks exactly like the SteamGridDB plugin crash, except your plugin is named "封面下载" for some reason? Where did you get it?

Just a localized version of SteamGridDB, translated a bit

**Comment by doZennn** [comment]
Oh okay, is this something you did yourself or can I get it publicly anywhere?

**Comment by lzq960605** [comment]
> 哦，好吧，这是你自己做的吗？或者我可以在任何地方公开获得它吗？

别人做的

https://gitee.com/songy171/decky-chs

**Comment by PartyWumpus** [comment]
Looks like that modified version of the plugin is out of date compared to the original one from the plugin store. (we don't really offer support 3rd party plugins by the way)

**Comment by TrainDoctor** [comment]
This is also not the correct place to file this issue. Please file this issue with the person who's making the modified version of the plugin.
