### ISSUE TITLE
Plugin order

### ISSUE THREAD

**Issue by iamPanka** [SteamDeckHomebrew/decky-loader#691]
### Please confirm

- [ ] I have searched existing issues
- [ ] This issue is not a duplicate of an existing one
- [ ] This is not a request for a plugin

### Feature Request Description

Can you make a setting to order the installed plugins alphabetically or by other parameters?

**Comment by TrainDoctor** [comment]
This is insufficient detail. If you'd like to properly fill out the feature request then we will be willing to read it.
