### ISSUE TITLE
[BUG] Steam Deck Black Screen + Color Glitch (I've shared error image)

### ISSUE THREAD

**Issue by teberzin** [SteamDeckHomebrew/decky-loader#692]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

I’ve just bought a new steam deck oled and wanted to install "decky loader". After the installation, I switched to gaming mode and I got a black screen (after time passed and I heard the opening sounds.) The screen became like this slowly.

When I restarted the steam deck and I open the log I saw this error. Wipe and uninstalling "decky loader" fixed the issue.

![image](https://github.com/user-attachments/assets/b596666f-6ad0-441f-9dbe-573b845bdf81)

> _(Image 1: showing the error that I got.)_

![image](https://github.com/user-attachments/assets/3835ecb4-e9be-44f1-95a2-f80c3fc31efa)

> _(Image 2: showing the color glitch I got after black screen)_

### Expected Behaviour

.

### SteamOS version

SteamOS 3.6.9

### Selected Update Channel

Stable

### Backend Logs

.

### Frontend Logs

.

**Comment by PartyWumpus** [comment]
We don't distribute an exe (because we aren't on windows), so it's strange that you'd see an error related to one. Where did you install decky from?

**Comment by teberzin** [comment]
> We don't distribute an exe (because we aren't on windows), so it's strange that you'd see an error related to one. Where did you install decky from?

Github. I downloaded it through the ".desktop" file that I've downloaded from the front page of the githun project page.

**Comment by AAGaming00** [comment]
> We don't distribute an exe (because we aren't on windows), so it's strange that you'd see an error related to one. Where did you install decky from?

this is an unreal engine game error on their clipboard wtf

**Comment by PartyWumpus** [comment]
> this is an unreal engine game error on their clipboard wtf

:skull: I was reading it on my phone

**Comment by TrainDoctor** [comment]
We don't have any information to go on to actually help you with your issue and it's unlikely the color issue is to do with Decky. If you can collect the logs that the issue asked you to collect instead of just entering a period then we can help you. Closing issue until logs and pictures of install process are provided.

**Comment by AAGaming00** [comment]
Also something of note, check if your deck is undervolted, because the color bands on the OLED indicate a hard crash
