### ISSUE TITLE
[Request] Decky loader session?

### ISSUE THREAD

**Issue by Hyphaed** [SteamDeckHomebrew/decky-loader#699]
### Please confirm

- [ ] I have searched existing issues
- [ ] This issue is not a duplicate of an existing one
- [ ] This is not a request for a plugin

### Feature Request Description

I would like to be able to select Decky loader as a session on GDM, to run directly steam

wouldn't be that more optimized that run Steam from inside gnome session?

**Comment by PartyWumpus** [comment]
Wouldn't be particularly "more optimized", but (assuming I'm understanding you correctly) this is already possible, using something like [gamescope-session-steam](https://github.com/ChimeraOS/gamescope-session-steam/tree/main) as seen in chimeraOS and bazzite.
