### ISSUE TITLE
[BUG] <decky does not load after most recent steam update>

### ISSUE THREAD

**Issue by ask-compu** [SteamDeckHomebrew/decky-loader#700]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

after the latest steam update decky no longer loads, even after running the decky installer again

i also noticed that the steam update disabled developer mode, but enabling it again does not seem to fix the problem

### Expected Behaviour

loading as normal

### SteamOS version

SteamOS 3.5.19

### Selected Update Channel

Stable

### Decky Loader Version

Unknown, can't check since decky no longer loads

### Plugin Info

not applicable, decky itself is not loading

### Backend Logs

[deckylog.txt](https://github.com/user-attachments/files/16972641/deckylog.txt)

### Frontend Logs

[cef_log.previous.txt](https://github.com/user-attachments/files/16972642/cef_log.previous.txt)
[cef_log.txt](https://github.com/user-attachments/files/16972643/cef_log.txt)

**Comment by TrainDoctor** [comment]
We're aware and are minutes away from getting a release out in stable to fix the issue. It will also be the first stable release of Decky V3.

**Comment by ask-compu** [comment]
> We're aware and are minutes away from getting a release out in stable to fix the issue. It will also be the first stable release of Decky V3.

ok i wasn't sure since i didn't see any issues or announcements on github here about it

**Comment by TrainDoctor** [comment]
> > We're aware and are minutes away from getting a release out in stable to fix the issue. It will also be the first stable release of Decky V3.
> 
> ok i wasn't sure since i didn't see any issues or announcements on github here about it

Intentional on my part. Didn't want to move a large amount of users onto an unstable branch if possible.

**Comment by ask-compu** [comment]
yes that seems to have fixed it, now i just need CSS loader themes to get updates (or CSS loader itself?)
