### ISSUE TITLE
[BUG] Discord server link invalid

### ISSUE THREAD

**Issue by erik-hasse** [SteamDeckHomebrew/decky-loader#713]
### Please confirm

- [X] I have searched existing issues
- [x] This issue is not a duplicate of an existing one
- [x] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [x] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

When I visit decky.xyz/discord, it redirects to an invalid Discord Invite. I suspect someone needs to regenerate the invite and update the website redirect.

I suppose this should probably be an issue in [SteamDeckHomebrew/deckbrew.xyz](https://github.com/SteamDeckHomebrew/deckbrew.xyz), but I want to make sure it gets seen.

### Expected Behaviour

It should redirect to a valid invite

### SteamOS version

NA

### Selected Update Channel

Stable

### Decky Loader Version

NA

### Plugin Info

NA

### Backend Logs

NA

### Frontend Logs

NA

**Comment by PartyWumpus** [comment]
The link works fine for me, you've likely been banned for some reason. (trying to join a server you're banned from looks the same as the link being invalid)

**Comment by erik-hasse** [comment]
Huh, weird. I guess it's on Discord's end (or maybe Firefox's). I tried in private browsing and it redirected to the Discord app as expected and I joined.

Sorry 'bout that.
