### ISSUE TITLE
[BUG] v3.0.1 doesn't work in the latest beta 

### ISSUE THREAD

**Issue by AkazaRenn** [SteamDeckHomebrew/decky-loader#717]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [x] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

After switching to the latest beta version of Steam client, Decky Loader stops working. It doesn't show an entry in the QAM and all plugins except CSS Loader are not functioning. Interestingly v3.0.0 still works. It is obtainable by installing from the prerelease channel.

Steam Client:
```
1729208001
Thu, Oct 17 19:14 UTC -05:00
Thu, Oct 17 18:39 UTC -05:00
```

### Expected Behaviour

It should be functioning properly.

### SteamOS version

Steam OS 3.5.19

### Selected Update Channel

Stable

### Decky Loader Version

v3.0.1

### Plugin Info

The script doesn't work. However, I didn't do any changes on the plugins before switching to Beta channel so that shouldn't be the problem.

### Have you modified the read-only filesystem at any point?

No

### Backend Logs

[deckylog.txt](https://github.com/user-attachments/files/17446704/deckylog.txt)

### Frontend Logs

[cef_log.txt](https://github.com/user-attachments/files/17446705/cef_log.txt)
[cef_log.previous.txt](https://github.com/user-attachments/files/17446706/cef_log.previous.txt)

**Comment by eXhumer** [comment]
> After switching to the latest beta version of Steam client, Decky Loader stops working.

Expected. Use pre-release version of Decky Loader for Beta / Preview channel.

> Interestingly v3.0.0 still works. It is obtainable by installing from the prerelease channel.

Are you sure about this? The current pre-release version of Decky-Loader is [v3.0.4-pre1](https://github.com/SteamDeckHomebrew/decky-loader/releases/tag/v3.0.4-pre1) and it works with the latest SteamClient update.

**Comment by AkazaRenn** [comment]
@eXhumer you are right it's v3.0.4-pre1 in the prerelease channel, sorry I misread it
