### ISSUE TITLE
[BUG] <title>uninstalldecky

### ISSUE THREAD

**Issue by Lola4everr** [SteamDeckHomebrew/decky-loader#723]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

I’ve been trying to uninstall decky for days now. I’ve followed step by step instructions and still I don’t get the option to uninstall. I’m so over this. I really want decky off my deck. Please help. Ty

### Expected Behaviour

uninstall decky loader completely off my deck

### SteamOS version

steamos 3.5.7 stable

### Selected Update Channel

Stable

### Decky Loader Version

v3.0.0-pre12

### Plugin Info

decky loader

### Backend Logs

deckylog.txt 

### Frontend Logs

cef_log.txt

**Comment by eXhumer** [comment]
> I’ve followed step by step instructions and still I don’t get the option to uninstall

What steps? There are two different uninstallation options provided. Which one did you follow?

**Comment by eXhumer** [comment]
If neither of the mentioned methods work for you, just run the following commands. It will delete all decky-loader & related files completely.

```
sudo systemctl disable --now plugin_loader.service
sudo rm -f "/home/deck/.config/systemd/user/plugin_loader.service"
sudo rm -f "/etc/systemd/system/plugin_loader.service"
sudo rm -rf "/home/deck/homebrew/"
sudo rm "/home/deck/.steam/steam/.cef-enable-remote-debugging"
```
