### ISSUE TITLE
[BUG] Plugins Disappearing after a restart of the Steam Deck

### ISSUE THREAD

**Issue by KylerNyhagen** [SteamDeckHomebrew/decky-loader#724]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

Decky 3.0.4 working just fine when I install my plugins - Cheatdeck for example works as intended. However, when I restart the Deck, Decky loader is still there, but no plugins are installed. I have to re-install my plugins.

I've tried both stable and prerelease

This happens with any plugin I have tried.

### Expected Behaviour

Plugins should not uninstall

### SteamOS version

SteamOS 3.6.20 Beta Channel

### Selected Update Channel

Prerelease

### Decky Loader Version

v3.0.4

### Plugin Info

I've tried animation changer 1.3.1, cheat deck0.4.1

### Have you modified the read-only filesystem at any point?

If I did, I don't really remember doing so.

### Backend Logs

[VVyjFqmz.txt](https://github.com/user-attachments/files/18115756/VVyjFqmz.txt)

### Frontend Logs

[cef_log.txt.txt](https://github.com/user-attachments/files/18115773/cef_log.txt.txt)
[cef_previous.txt](https://github.com/user-attachments/files/18115820/cef_previous.txt)

**Comment by Zodiaksl** [comment]
Can confirm,

Also on SteamOS 3.6.20
Branch: Beta

Decky: 3.0.4
Channel: Prerelease

None of my plugins are showing up.

**Comment by jakal323** [comment]
Confirming as above; switching to the stable branch of SteamOS caused the plugins to reappear.

**Comment by eXhumer** [comment]
The plugins are not being uninstalled. The decky-loader frontend UI seems to be having issues with the latest beta client. Stick to the stable client until it is fixed.

**Comment by AAGaming00** [comment]
fixed in v3.0.5-pre1

**Comment by ynhhoJ** [comment]
> fixed in v3.0.5-pre1

Fixed for me too!
Thx!

**Comment by quuinnn** [comment]
fixed for me aswell

**Comment by CaneonBall** [comment]
Happening again on v3.0.5 Stable Channel with SteamOS 3.6.20 Stable Channel

**Comment by TrainDoctor** [comment]
Closing for now unless we get concrete evidence that this is returning for a large amount of users.
