### ISSUE TITLE
install error,XDG_RUNTIME_DIR (/run/user/1000) is not owned by us (uid 0), but by uid 1000! 

### ISSUE THREAD

**Issue by crazyAJ** [SteamDeckHomebrew/decky-loader#732]
### Bug Report Description

install decky and input pwd, then i receive an error log. 'XDG_RUNTIME_DIR (/run/user/1000) is not owned by us (uid 0), but by uid 1000! (This could e.g. happen if you try to connect to a non-root PulseAudio as a root user, over the native protocol. Don't do that.)'. what can i do ?

### Expected Behaviour

-

### SteamOS version

3.6.21

### Selected Update Channel

Prerelease

### Decky Loader Version

-

### Plugin Info

install decky_installer.desktop

### Backend Logs

-

### Frontend Logs

![Screenshot_20241221_214911](https://github.com/user-attachments/assets/d6b61c70-6dad-43df-8196-3c3598f073a6)

**Comment by eXhumer** [comment]
This is a warning that you can safely ignore.

Have you checked if the Decky icon appeared in Game Mode? If so, then the installation was successful. Make sure to install the pre-release version of Decky, since you seem to have Beta SteamOS / Client installed.

**Comment by crazyAJ** [comment]
i find a way to deal install this plugin. 

step1:
mkdir -p /tmp/$USER-runtime
export XDG_RUNTIME_DIR=/tmp/$USER-runtime

step2:
curl -L https://github.com/SteamDeckHomebrew/decky-installer/releases/latest/download/install_release.sh | sh
curl -L https://github.com/SteamDeckHomebrew/decky-installer/releases/latest/download/install_prerelease.sh | sh

**Comment by crazyAJ** [comment]
this is error screenshot

![Screenshot_20241222_000901](https://github.com/user-attachments/assets/63b07214-3573-4062-b9e5-6fe13f7b8b36)

**Comment by crazyAJ** [comment]
@eXhumer Double click to start installing the pre-version program from desktop mode, and then an error message will appear indicating that the installation was unsuccessful. After several attempts, the installation cannot be completed correctly

**Comment by kurtn2005** [comment]
> i find a way to install this plugin.
> 
> step1: mkdir -p /tmp/$USER-runtime export XDG_RUNTIME_DIR=/tmp/$USER-runtime
> 
> step2: curl -L https://github.com/SteamDeckHomebrew/decky-installer/releases/latest/download/install_release.sh | sh curl -L https://github.com/SteamDeckHomebrew/decky-installer/releases/latest/download/install_prerelease.sh | sh

Thanks mate! It worked for me.
