### ISSUE TITLE
Loader - Automatic Update Checking for plugins

### ISSUE THREAD

**Issue by TrainDoctor** [SteamDeckHomebrew/decky-loader#82]
Only major question is between automatic updates or user-prompting before installing a new update.

**Comment by NGnius** [comment]
I'd recommend against automatic updates, except possibly as an opt-in feature.

I'd prefer a prompt, because it gives users control over updating to something potentially buggy. Windows is a good example of why that's important

**Comment by TrainDoctor** [comment]
> I'd recommend against automatic updates, except possibly as an opt-in feature.

My fault in terms of clarity. I had no intent to force users to update by default. Although I do think that downloading latest updates in the background would be a good idea to as it would mean easy and quick installs.
